### ISSUE TITLE
Allow possible resize of image button

### ISSUE THREAD

**Issue by graph-kgrondin** [rivafarabi/deckboard#10]
Something, i use an image for the button and it's great and sometimes i want to use svg icon without going in photo to resize it to fit great.

**Comment by rivafarabi** [comment]
Did you use the scroll wheel to resize the image when you create/edit a shortcut?

**Comment by graph-kgrondin** [comment]
Oh! i didn't notice that! Maybe we need to have some texte or something to tell us we can resize with scroll wheel!
