### ISSUE TITLE
deckboard no longer connects to streamlabs obs

### ISSUE THREAD

**Issue by dauthiatull** [rivafarabi/deckboard#100]
as of today deckboard no longer connects to streamlabs obs

**Comment by rivafarabi** [comment]
Did you match the port correctly in the deckboard setting and streamlabs obs Setting->Developer->Websocket menu?

**Comment by dauthiatull** [comment]
I did now. the option was disabled and hidden after the last slobs update. had to re add the --adv-settings to the startup link. its all good now
