### ISSUE TITLE
[BUG]Spotify & twitter 25.7.2023

### ISSUE THREAD

**Issue by Gh0stSnipu1** [rivafarabi/deckboard#1001]
Twitter is now called "X" and it revoked all app permissions so it wount login anymore in 2.1.4 stable version.
Also Spotify aint working even its premium account. 

This error comes from twitter "X" 
Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by GAMINGCHATS** [comment]
Same error from Spotify for me. 
  Application error 
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by rivafarabi** [comment]
Thanks for the info. It should work now. Kindly let me know on your end.

**Comment by GAMINGCHATS** [comment]
> Thanks for the info. It should work now. Kindly let me know on your end.

Now when I try to connect Spotify I'm getting this error: 
 INVALID_CLIENT: Invalid redirect URI

**Comment by rivafarabi** [comment]
Wait for another minutes. The changes may be not applied yet

**Comment by GAMINGCHATS** [comment]
> Wait for another minutes. The changes may be not applied yet
Ok.

**Comment by Gh0stSnipu1** [comment]
Now it works just fine. Thank you very fast update \o/
