### ISSUE TITLE
[FEATURE REQUEST] Run non predefined shell commands

### ISSUE THREAD

**Issue by zany130** [rivafarabi/deckboard#1004]
**Is your feature request related to a problem? Please describe.**
Currently, you can run predefined shell commands but there is no way to run an arbitrary command from your phone

**Describe the solution you'd like**
a solution similar to https://www.unifiedremote.com/remotes/command

**Describe alternatives you've considered**
unified remote

**Additional context**
Been using Unified remote for a while and just learned about this awesome software today. I much prefer the interface of this app and how you can have multiple boards for different things, but I  miss a few features from unified remote.

**Comment by schousda** [comment]
You already can run powershell scripts for example or any other command line.
Or did i get the request wrong?

**Comment by zany130** [comment]
But you have to specfiy them before hand on the desktop app. With unified remote you get a text box to enter any command you want on the phone and it will output it like this

<img src="https://www.unifiedremote.com/remotes/raw/unifiedremote_remotes_master/main_command/ignore/screen.png"/>

**Comment by zany130** [comment]
@rivafarabi  would this be something worth looking at? saw github-actions closed the issue
