### ISSUE TITLE
Does not differentiate Left/Right modifiers

### ISSUE THREAD

**Issue by falo2k** [rivafarabi/deckboard#101]
I've got macros recorded for my Razer keyboard and used in Discord that differentiate between left and right modifier keys (e.g. left Ctrl vs right Ctrl).  Deckboard seems to be interpreting them all as Left Ctrl, so some macros cannot work.

**Comment by rivafarabi** [comment]
Feature added in [v1.9.41-rc2](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.41-rc2) (Release Candidate/Beta)
