### ISSUE TITLE
[FR] Sliders / Scroll Wheels

### ISSUE THREAD

**Issue by LividJava** [rivafarabi/deckboard#1011]
**Is your feature request related to a problem? Please describe.**
Needing to adjust volumes, or other sliders in stepped increments is frustrating when you want more granularity. A previous version of Deckboard had a solution to this issue this version here. [(2.0.0-beta1)](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.0-beta.1)

**Describe the solution you'd like**
A re-implementation of this feature in current versions of deckboard.

**Describe alternatives you've considered**
I am so far using a board dedicated solely to increment and decrement volume sliders, with varying increments, for each audio source I'd like to adjust.

**Additional context**
This feature has been seen implemented but was removed for one reason or another? (half baked?) Hopefully we can see this in deckboard once again sometime in the near future!

**Comment by rivafarabi** [comment]
Sorry for the long wait. The volume slider is included in version [3.0.0-rc10](https://v3.deckboard.app/releases/3.0.0-rc10).

Client app version 3.0.7 (Beta) is also required to access this feature.
