### ISSUE TITLE
[BUG] [EXPERIMENTAL] Advanced boards do not update automatically.

### ISSUE THREAD

**Issue by LividJava** [rivafarabi/deckboard#1018]
**Describe the bug**
When creating an Advanced board, the selected option does not appear. Requiring the user to switch boards for the views to update.

**To Reproduce**
1. Create an advanced board
2. Select any type of new panel

**Expected behavior**
Upon creation, The new panel should be shown immediately to the user.

**Screenshots**

**Server App (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 3.0.0-rc0

**Client App (please complete the following information):**
_Client App was not tested_

**Required files**
- database.db (Will Email upon Request)
- [log.log](https://github.com/rivafarabi/deckboard/files/13463121/log.log)

**Comment by LividJava** [comment]
Demonstration Video
https://github.com/rivafarabi/deckboard/assets/7604544/68922b9d-4081-483d-9254-1cda19871fc6

**Comment by rivafarabi** [comment]
Thanks for the info. will look further into the issue.

**Comment by rivafarabi** [comment]
Sorry for the late update.

The bug has been fixed in 3.0.0-rc1.
