### ISSUE TITLE
Bug: Selecting OBS Audio Device control function breaks the program

### ISSUE THREAD

**Issue by aKuhTV** [rivafarabi/deckboard#102]
When/After selecting the OBS Audio Device Control function in the dropdown menu the function-specific options don't change as they should. Clicking Cancel closes the menu, but the program won't respond to any clicks on the UI buttons anymore. (See GIF video)

Reinstalling and deleting the deckboard folder in the user directory does not fix this.

![deckboardbug](https://user-images.githubusercontent.com/11634943/51084529-a1608280-172b-11e9-9867-37e7052b9573.gif)

**Comment by rivafarabi** [comment]
Thanks for the info. I'll put this on bug list for now

**Comment by AngelicDivine** [comment]
thats whats going on with mine lol

**Comment by rivafarabi** [comment]
Solved in version 1.2.7
