### ISSUE TITLE
[BUG] [EXPERIMENTAL] "Live View" still allows you to add panels to the Advanced boards

### ISSUE THREAD

**Issue by LividJava** [rivafarabi/deckboard#1023]
**Describe the bug**
When using the "Live View" to allow you to use buttons directly within Deckboard. You can still add and remove panels in the Advance Boards

**To Reproduce**
1. Enable "Live View"
2. Navigate to an Advanced Board
3. Attempt to interact with the present panels.

**Expected behavior**
The panels that are not present should be hidden like in other boards. You should not be able to add or remove panels in the "Live View"

**Screenshots**
![image](https://github.com/rivafarabi/deckboard/assets/7604544/8602c0f3-6bc5-4cce-904e-8929cca2edb2)

**Server App (please complete the following information):**
 - OS: Windows 10
 - Version 3.0.0-rc0

**Client App (please complete the following information):**
Not Applicable

**Required files**
See #1022 (To my knowledge the files have not changed)

**Additional context**
Apologies for all the recent bug reports. But I figure making them is better than being unaware of them and flying blind.

**Comment by rivafarabi** [comment]
Thanks for the info. The bug has been fixed in [3.0.0-rc1](https://github.com/rivafarabi/deckboard/releases/tag/v3.0.0-rc1)
