### ISSUE TITLE
[FEATURE REQUEST] GET Requests in Background

### ISSUE THREAD

**Issue by joshrosario310** [rivafarabi/deckboard#1031]
**Is your feature request related to a problem? Please describe.**
An app I use has a GET request API to run certain actions.

**Describe the solution you'd like**
Would like a simple GET call to a URL

**Describe alternatives you've considered**
Currently, using the Open Webpage action which opens the GET request in a new window. I just need to close these manually after. If this could have an option to run in the background and close the page after load, that would also work.

**Additional context**

**Comment by Simego** [comment]
hi @joshrosario310 , i think this can be done with this: https://github.com/golpilolz/deckboard-callurl
it's also available at deckboard extension downloads list (inside deckboard), give it a try

**Comment by joshrosario310** [comment]
This is exactly what I was looking for, definitely did not see it in the extensions library. Thank you!
