### ISSUE TITLE
[BUG] Custom images do not changed based on Active/Inactive states

### ISSUE THREAD

**Issue by Neopopulas** [rivafarabi/deckboard#1033]
**Describe the bug**
When making buttons - in this case 'toggle voice changer' for voicemod - you have an Inactive and Active button. These buttons - like all buttons - can have a custom image (even a gif) uploaded to the button. These images appear as expected on the board. However, when you push the button to switch between Active and Inactive, the custom overlay image does not change - the default icon _under_ the image does change though.

**To Reproduce**
1. Go to any board, create a button, select any option that has an Active/Inactive state - for example Voicemod -> Toggle Voice Changer. 
2. Click on the button you want to change, and then upload the image you want as the overlay
3. Save the image and repeat the process with the second button - make sure the image is different so you can tell if it works or not
4. Save the new button
5. Simple tap the button on your device of choice. You will see that the overlay image does not change, even though the button is activated.

**Expected behavior**
When using an Active/Inactive button option, the custom image you load should change based on the state of the button

**Screenshots**

**Server App (please complete the following information):**
 - OS: Windows 11
 - Version: 3.0.0-rc4

**Client App (please complete the following information):**
 - OS: Android 13
 - Version: 3.0.3

**Comment by rivafarabi** [comment]
Fix for this is available on server app version [3.0.1](https://www.deckboard.app/releases/3.0.1) and client app version 3.1.02
