### ISSUE TITLE
[FEATURE REQUEST] Change background for custom invisible icons

### ISSUE THREAD

**Issue by qouxly** [rivafarabi/deckboard#1034]
I hate it when I want to use custom images like .png and as soon as I saved the button, the invisible background turns black. So if I want use a black icon I can't see it at all.

Please change it so when I use an image with invisible pixels(alpha 0) just use the normal background color of the button

This is the icon for example:
![image](https://github.com/rivafarabi/deckboard/assets/102686564/aebcdcf9-7f54-462e-82fa-f38f3672cb8a)
I save it and it turns into this:
![image](https://github.com/rivafarabi/deckboard/assets/102686564/e57c1099-e3f3-4074-8f32-1f13d9cf75e0)

**Comment by BeboBabaYellow** [comment]
YES!! this is such a big issue with me, for my case i just enter the image last and then NEVER MESS with that button again

**Comment by rivafarabi** [comment]
Do you have the example of the color setting displayed on New/Edit Button popup that resulting the issue above? So far I cannot replicate it.

**Comment by qouxly** [comment]
I'm sorry, however I can't replicate the problem, so I can't give you any example. Maybe because I now use the newest beta version and not the release. It works for me now so thanks for your help.

**Comment by Yellowbebo** [comment]
this isn't exactly an "example" type of thing but more of an explanation, if i enter an image with a transparent background, then try to change the image or remove it and input another, sometimes it triggers something that removes the transparent background and fills it in with black
not sure why.. or how this happens but it does

**Comment by Yellowbebo** [comment]
here's an image of a button that is SUPPOSED to be an image of the github logo
![image](https://github.com/rivafarabi/deckboard/assets/73755040/17e8cc51-b808-44b3-979d-605b9d3c901b)

this is the original image
![github](https://github.com/rivafarabi/deckboard/assets/73755040/e157edd4-55bf-4642-9094-b3305e63d1b0)
..nevermind just realised it broke the picture again (yes you heard that right, deckboard actually CORRUPTED THE ORIGINAL IMAGE)

THIS is the original image
![github icon TAKE 2](https://github.com/rivafarabi/deckboard/assets/73755040/e3fd60c1-5f66-4ba7-bcc2-cb84a06eab25)

**Comment by qouxly** [comment]
Are you using the pre-release version? If not, is that perhaps the problem? Since I am using the pre-release version, I can no longer reproduce the problem. This could fix it for you too

**Comment by Yellowbebo** [comment]
im on pre-release 6

**Comment by rivafarabi** [comment]
Fixed in version 3.0.0-rc8
