### ISSUE TITLE
[FEATURE REQUEST] Customizable sections for Advanced Boards

### ISSUE THREAD

**Issue by hexandcube** [rivafarabi/deckboard#1039]
Currently, Advanced boards are quite limited due to the large margins and padding of the sections, so there's a lot of blank space on the screen. It would be great if the padding, margins, and background color of sections was customizable. That way, we could create a board that fills the entire screen (just like a basic board), but supports the features of an advanced board.

Also, changing the padding of the board itself would be a nice addition.

**Comment by rivafarabi** [comment]
Due to the plan of deprecating the advance board in the next beta release, I will close this issue. ([Reference](https://twitter.com/rivafarabi/status/1783177091426681229))
