### ISSUE TITLE
[FEATURE REQUEST] Vertical Sliders

### ISSUE THREAD

**Issue by hexandcube** [rivafarabi/deckboard#1040]
Would be nice if there was a way to change the orientation of the slider section, so that sliders are vertical instead of horizontal

**Comment by Yellowbebo** [comment]
i second this.. but dont know if there's a like button on issues

**Comment by rivafarabi** [comment]
Will include this in 3.1.0. Still prioritizing the bug fixes for the stable release of version 3.0.0

**Comment by rivafarabi** [comment]
Sorry for the long wait. The vertical slider has been introduced in version [3.0.0-rc10](https://v3.deckboard.app/releases/3.0.0-rc10).

If you find any issue with the feature, let me know. Thank you
