### ISSUE TITLE
Junior Jumble (VERY IMPORTANT ISSUE, MAKES APP UNUSABLE)

### ISSUE THREAD

**Issue by Yellowbebo** [rivafarabi/deckboard#1044]
**Describe the bug**
..just.. look
![image](https://github.com/rivafarabi/deckboard/assets/73755040/14f05218-eeaf-4c0e-8ebe-d76a324974a4)

**To Reproduce**
1. Have a crap ton of buttons and boards set up
?. ???

**Expected behavior**
I expect to NOT HAVE TO PLAY A CROSSWORD PUZZLE every time deckboard starts but we dont always get what we want now do we (not mad, just joking)

**Screenshots**
![image](https://github.com/rivafarabi/deckboard/assets/73755040/72ad2b0c-0b1a-41a0-8b0d-da334a5921a9)

**Server App (please complete the following information):**
 - Windows 10
 - Version 22h2 or whatever its called (22H2)..

**Client App (please complete the following information):**
 - OS: Andoird.. adnroid.. android
 - Version 12

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)
I STILL DONT KNOW HOW TO FIND THIS, i'll get it in a bit but i wanna get this issue posted first
[Database + Log for Jumble.zip](https://github.com/rivafarabi/deckboard/files/14225697/Database.%2B.Log.for.Jumble.zip)

**Additional context**
deckboard 3.0.0 Rc-5 or smth like that

**Comment by hexandcube** [comment]
Yeah, 3.0.0-rc5 completely breaks existing basic board layouts, and it's impossible to fix them without manually re-creating the board.

**Comment by rivafarabi** [comment]
Just to make sure, are the two buttons on the bottom supposed to be displayed on server app as well?

**Comment by Yellowbebo** [comment]
no, this is a 7x4 board.. or a 4x7, i forgot which format is right
essentially those buttons are floating in the void, i did discover since then that some DUPLICATE buttons have been created, and that deleting the duplicates fixes these buttons, but i've opted to keep this screen as is because

- the image and info about this board could help solve the issue
- void funy
- there is **1 Duplicate** here, but **2 Void spaces** aswell

**Comment by rivafarabi** [comment]
thanks for the info. will patch it asap

**Comment by rivafarabi** [comment]
The fix for this issue is live on version [3.0.0-rc6](https://github.com/rivafarabi/deckboard/releases/tag/v3.0.0-rc6)

If the issue persist, please open a new ticket. Thank you
