### ISSUE TITLE
Streamlabs OBS connectivity

### ISSUE THREAD

**Issue by itsjustDuvvy** [rivafarabi/deckboard#105]
So, I've been trying to get this software set up with SLOBS, but their WebSockets section no longer looks like it used to. I'm not finding the port, no idea where to put it, etc. I can't seem to get it to work, and the SLOBS support people have no idea what I'm talking about when I ask them about the WebSocket settings.

**Comment by itsjustDuvvy** [comment]
Okay, that's the problem. How do I open it with --adv-setting? I asked the SLOBS people and they had no clue. I was never able to enable it before, this is all entirely new to me.

**Comment by rivafarabi** [comment]
Here's the step to open SLOBS with adv-settings

1. right click the SLOBS shortcut
2. click *Properties *
3. *--adv-settings *on Target field after the file directory (look like
this
https://www.digitalcitizen.life/sites/default/files/img/pin_shortcuts_taskbar/pst3.png
).

The rest of the steps you can look it up here
https://github.com/rivafarabi/deckboard/wiki/Streamlabs-OBS-Setup

**Comment by digitalfiz** [comment]
I am having the same connectivity problems. Running with -adv-setting gave me the developer options and the websocket boxes are checked but still not able to connect.

**Comment by digitalfiz** [comment]
I changed the port and it worked...
