### ISSUE TITLE
[BUG] Importing boards doesn't work properly in 3.0.0-rc6

### ISSUE THREAD

**Issue by hexandcube** [rivafarabi/deckboard#1050]
**Describe the bug**
Attempting to import an exported board in version 3.0.0-rc6, results in an empty board with unusable button slots (clicking on them doesn't open the button customization window). The boards also appear empty on the client app.

**To Reproduce**
1. Export a basic board with buttons from settings
2. Attempt to import the board in version 3.0.0-rc6
3. The boards will get imported from the JSON file, but with empty button slots

**Expected behavior**
The board should be imported with all butons

**Screenshots**
![image](https://github.com/rivafarabi/deckboard/assets/41151156/f743ec9d-b10d-47b7-a1f7-c4938814779e)

**Server App:**
 - OS: Windows 11 23H2 (Build 22631.2861)
 - Version: 3.0.0-rc6

**Client App:**

N/A

**Required files**
- [database.db (zipped)](https://github.com/rivafarabi/deckboard/files/14425504/database.zip)
- [log.log](https://github.com/rivafarabi/deckboard/files/14425508/log.log)

**Additional context**
N/A

**Comment by rivafarabi** [comment]
Thank you for waiting. The fix is included in the latest beta version [3.0.0-rc7](https://github.com/rivafarabi/deckboard/releases/tag/v3.0.0-rc7)

If you still having this bug, please open a new issue thread
