### ISSUE TITLE
[BUG] icons

### ISSUE THREAD

**Issue by sabiron** [rivafarabi/deckboard#1054]
**Describe the bug**
The PC application icons cannot be customized with images, GIFs or labels as you advertise on your website with the phrase "Full customization"

**To Reproduce**
1. Go to ''
3. Fill a value to '...'

**Expected behavior**

**Screenshots**

**Server App (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 1.9.0]

**Client App (please complete the following information):**
 - OS: windows 10
 - Version [e.g. 1.9.60]

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

**Additional context**

**Comment by Yellowbebo** [comment]
you haven't included ANY of the requested info besides a description of the problem
i'd try to help but im not that experienced and there is not enough info to fix this problem (in my opinion)

**Comment by sabiron** [comment]
I haven't provided more information because I don't think it's a bug.
The thing is that on the website you say that you can put custom icons, gifs and more as button icons, but I can't find that functionality in the program, where I can only choose "font awesome" icons.

I'll give you a link to an image capture  ->

https://prnt.sc/lGufuJD3u85E

https://prnt.sc/NhilgJVbAOqp

https://prnt.sc/WwMssEMB8SMu

https://prnt.sc/DskWUFYgcBTx

https://prnt.sc/lvvz0QNhzyqq

**Comment by rivafarabi** [comment]
you can click the button preview to open image selection dialog or just drag and drop image file to the image preview.
