### ISSUE TITLE
Pro version of the app is not working

### ISSUE THREAD

**Issue by alexonpeace** [rivafarabi/deckboard#1055]
![WhatsApp Image 2024-03-13 at 01 21 33_dfe7ae42](https://github.com/rivafarabi/deckboard/assets/47172928/05bd1db5-ce0e-429f-a38e-0a0e8583142f)
**Describe the bug**
The pro version of the app is not working

**To Reproduce**
1. Go to playstore
2. Click on search
3. Fill a value to deckboard pro
4. click install
5. open deckboard pro
6. connect to pc via ip
7. See error

**Expected behavior**
it should work

**Screenshots**

**Server App (please complete the following information):**
 - OS: Windows
 - Version [e.g. 1.9.0]

**Client App (please complete the following information):**
 - OS: Android 12
 - Version 3.0.5

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

**Additional context**
[log.log](https://github.com/rivafarabi/deckboard/files/14577971/log.l
[database.zip](https://github.com/rivafarabi/deckboard/files/14577981/database.zip)
og)

**Comment by rivafarabi** [comment]
What version of server app are you using?

**Comment by LividJava** [comment]
issue is present here on linux with server app 2.1.4 (Appimage)

**Comment by LividJava** [comment]
@rivafarabi bump.
any word on this being fixed?

**Comment by rivafarabi** [comment]
Have you tried the latest beta version yet? If yes, is the same thing
happens using that release?

**Comment by LividJava** [comment]
Trying beta now, it seems to work with the Beta server app (3.0.0-rc7)

**Comment by rivafarabi** [comment]
Closed, due to the issue has been solved in the beta version,
