### ISSUE TITLE
App flip

### ISSUE THREAD

**Issue by Zvobrandir** [rivafarabi/deckboard#106]
The application does not flip if I rotate the device 180 degrees (on android 4.2.1). 
On Android 8.0.0 works normal.

**Comment by Zvobrandir** [comment]
On Android 4.2.1 requires a double tap for any action (even for the "Home" or "Back" button).
On Android 8.0.0 works with single tap.

**Comment by rivafarabi** [comment]
This app currently targeted for Android 4.4 and above. No future plan for improvement for older version
