### ISSUE TITLE
[FEATURE REQUEST] - Setting to specify which display (monitor) to open on

### ISSUE THREAD

**Issue by ondrovic** [rivafarabi/deckboard#1062]
**Is your feature request related to a problem? Please describe.**
I have a 7in touch panel display that I use, and it would be nice to have deckboard launch on that monitor by default

**Describe the solution you'd like**
A setting that allow yous to select which monitor the interface is displayed on

**Describe alternatives you've considered**
You have to manually move the window to the monitor you wish to use on

**Additional context**
```js
const { app, BrowserWindow, screen } = require('electron')

let win

app.whenReady().then(() => {
  const displays = screen.getAllDisplays()
  const externalDisplay = displays.find((display) => {
    return display.bounds.x !== 0 || display.bounds.y !== 0
  })

  if (externalDisplay) {
    win = new BrowserWindow({
      x: externalDisplay.bounds.x + 50,
      y: externalDisplay.bounds.y + 50
    })
    win.loadURL('https://github.com')
  }
})
```

**Comment by rivafarabi** [comment]
Thanks for the feedback and sorry for the late reply.
I have included the features you requested here and #1061 in beta version [3.0.0-rc9.2
](https://v3.deckboard.app/releases/3.0.0-rc9.2)
![image](https://github.com/rivafarabi/deckboard/assets/4427494/ae99311b-e489-4396-89a3-da017fc9dc3f)

If you have another feedback. Please open another thread. Will close this issue alongside the other one
