### ISSUE TITLE
[BUG]: Incompatibility Issue with Non-Monochromatic Emojis in Dackboar's Predefined Text Pasting Feature

### ISSUE THREAD

**Issue by Miderson99** [rivafarabi/deckboard#1068]
Describe the bug
The predefined text pasting feature in Dackboar does not support non-monochromatic emojis, causing them to be displayed incorrectly or missing when pasted on a target device.

To Reproduce

Define a macro or predefined text containing non-monochromatic emojis.
Attempt to paste the predefined text on a target device, such as a mobile device.
Observe that non-monochromatic emojis are not displayed correctly or are missing.
Expected behavior
Non-monochromatic emojis should be displayed correctly when pasting predefined texts using the Dackboar application's macro feature. The emojis should retain their original appearance without distortion or omission.

![ProblemWithPastEmogisNon-monochromatics](https://github.com/rivafarabi/deckboard/assets/146260190/bf3d3147-f696-437d-a107-c64ae81050b0)
![ProblemWithpasteEmogisIndeckboard](https://github.com/rivafarabi/deckboard/assets/146260190/820e6dba-b047-4b39-bd6b-07a8cd0ce6cf)

**Comment by rivafarabi** [comment]
Can you tell me which version of server app you use right now?

**Comment by Miderson99** [comment]
![versionDeckBoardApp](https://github.com/rivafarabi/deckboard/assets/146260190/3520e5c5-cf6b-42c6-b402-69d63d66e8c7)

**Comment by rivafarabi** [comment]
Thank you for the feedback. The emoji support for "Type Text" action has been added [3.0.0-rc9.3](https://v3.deckboard.app/releases/3.0.0-rc9.3).
