### ISSUE TITLE
[BUG] Type Text: "Enter" not sent

### ISSUE THREAD

**Issue by schousda** [rivafarabi/deckboard#1072]
Hello,

looks like the behaviour of "Type Text" changed.

I have some buttons like this:

```
"My text

"
```
Before the update the Enter and that way the text was sent.
Now i only get the text.

OS: Windows 11
v3.0.0-rc8

OS: Android 11
Version 3.0.6 beta

**Comment by rivafarabi** [comment]
Have you confirmed the exact text printed on other app like NotePad?

**Comment by schousda** [comment]
Yes, i tested this. The Enter after the text is missing.

I also created a Multi-Action like shown in the screenshot.
In the word "hello" always one "l" is missing and also the Enter from the second text after the Tab is missing.
![image](https://github.com/rivafarabi/deckboard/assets/21222928/af9af878-88c1-4a52-9312-3b02ac5b2563)

**Comment by schousda** [comment]
I also noticed a long delay in an other Multi-Action, which looks like the one from the screenshot.
![2024-04-28_12-12-34](https://github.com/rivafarabi/deckboard/assets/21222928/3e1714cf-cd25-4a62-9253-c2dba02e4794)

**Comment by rivafarabi** [comment]
It seems the issue only appears on Windows. Will add this for next 3.0.0-rc9 release

**Comment by rivafarabi** [comment]
Sorry for the long wait. The issue has been fixed in version [3.0.0-rc10](https://v3.deckboard.app/releases/3.0.0-rc10).

If you still face the same issue. Please open a new thread. Thank you
