### ISSUE TITLE
[BUG] Boards don't load on client app when on server version 3.0.0-rc8

### ISSUE THREAD

**Issue by hexandcube** [rivafarabi/deckboard#1073]
**Describe the bug**
After updating the server app to 3.0.0-rc8, no boards load on the client app (which is updated to the latest beta version on the Google Play store - v.3.0.6). After connecting, the screen is white, and the board list on the app is empty.

**To Reproduce**
1. Open the server app on version 3.0.0-rc7 
2. Open the client app on Android and connect to the server (Everything will work fine)
3. Update the server app to version 3.0.0-rc8 (App will disconnect during update)
4. Press reconnect on the client app after the update of the server app is finished (The app will connect and everything will work fine, I assume that's because the boards are still loaded in memory)
5. Disconnect from the server 
6. Reconnect to the server
7. Boards won't load now

**Expected behavior**
Boards should be displayed on the mobile app properly after connecting

**Screenshots**
![image](https://github.com/rivafarabi/deckboard/assets/41151156/2cf88599-37b4-4286-bca4-c06bb5f5b72a)

**Server App (please complete the following information):**
 - OS: Windows 11 23H2 (build 22631.3447)
 - Version: 3.0.0-rc8

**Client App (please complete the following information):**
 - OS: Android 12
 - Version: 3.0.6

**Required files**
- database.db: [database.zip](https://github.com/rivafarabi/deckboard/files/15138239/database.zip)
- log.log: [log.log](https://github.com/rivafarabi/deckboard/files/15138242/log.log)

**Additional context**
Downgrading the server app to 3.0.0-rc7 fixes the issue

**Comment by rivafarabi** [comment]
Thanks for the info, I've just released a hot fix for this particular issue ([v3.0.0-rc9](http://v3.deckboard.app/releases/3.0.0-rc9))

**Comment by rivafarabi** [comment]
Some of the icons on the client side probably not match with what you see on server app (example: @ and * icons). This visual bug on client app will be patched later

**Comment by rivafarabi** [comment]
Closing this issue. Please open a new thread if the bug persist
