### ISSUE TITLE
[BUG] Avanced Keyboard on small screens 

### ISSUE THREAD

**Issue by longopy** [rivafarabi/deckboard#1074]
**Is your feature request related to a problem? Please describe.**
When I use the tool on small screens, the advanced dashboard does not display correctly. 

**Describe the solution you'd like**
maybe let you adjust the zoom of each screen independently?

**Comment by rivafarabi** [comment]
Due to the plan of deprecating the advance board in the next beta release, I will close this issue. ([Reference](https://twitter.com/rivafarabi/status/1783177091426681229))
