### ISSUE TITLE
[BUG] multimedia controls do nothing

### ISSUE THREAD

**Issue by PinkMan456** [rivafarabi/deckboard#1076]
As the title says when i press on the multimedia controls button they do nothing.

**Comment by rivafarabi** [comment]
Please provide all of these details:

**Server App:**
 - OS: [e.g. Windows]
 - Version [e.g. 1.9.0]

**Client App:**
 - OS: [e.g. Android 9]
 - Version [e.g. 1.9.60]

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

**Comment by PinkMan456** [comment]
Windows 11
3.0.0-rc9

Android 13
Pro Version 2.1.1

I can't send the database.db
[log.log](https://github.com/rivafarabi/deckboard/files/15141155/log.log)

**Comment by PinkMan456** [comment]
[database.zip](https://github.com/rivafarabi/deckboard/files/15141171/database.zip)

**Comment by rivafarabi** [comment]
Version 3.0.0-rc9 is a beta release of version 3, you also need to use the version 3+ of the client app which is also still in beta. The client app's beta version can only be downloaded by joining Google Play beta program on Google Play's Deckboard app page
![image](https://github.com/rivafarabi/deckboard/assets/4427494/38fd6aba-3bdf-41ef-b303-d5b946ee1437)

**Comment by PinkMan456** [comment]
I got the beta version downloaded and still nothing.

**Comment by rivafarabi** [comment]
version 3.0.6?

**Comment by PinkMan456** [comment]
Yes

**Comment by rivafarabi** [comment]
Can you tell me what type of control you try to achieve? (Play/Pause, Prev, Next, etc)

**Comment by PinkMan456** [comment]
Any multimedia controls just do nothing. Play/pause, next, prev, volume all do nothing.

**Comment by rivafarabi** [comment]
It seems the issue only appears on Windows. Will add this for next 3.0.0-rc9 release

**Comment by rivafarabi** [comment]
Sorry for the long wait. The issue has been fixed in version [3.0.0-rc10](https://v3.deckboard.app/releases/3.0.0-rc10).

If you still face the same issue. Please open a new thread. Thank you
