### ISSUE TITLE
[BUG] JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Dking07** [rivafarabi/deckboard#1078]
**Describe the bug**
This error is happening every time I try to use an 'Advance Keyboard Macro' button.

**Screenshots**
![image](https://github.com/rivafarabi/deckboard/assets/117837111/f4d82646-dea0-4090-8386-d735e5ceb746)

**Server App:**
 - OS: Win 10
 - Version 3.0.0-rc9

**Client App:**
 - OS: Android 11
 - Version 1.9.80

**Comment by rivafarabi** [comment]
Thanks for feedback. The bug fix will be included in version 3.0.0-rc10 this week

**Comment by rivafarabi** [comment]
Sorry for the long wait. The issue has been fixed in version [3.0.0-rc10](https://v3.deckboard.app/releases/3.0.0-rc10).

If you still face the same issue. Please open a new thread. Thank you
