### ISSUE TITLE
[BUG] Does not load backup

### ISSUE THREAD

**Issue by Peppe-73** [rivafarabi/deckboard#1079]
**Describe the bug**

Hi, I installed version 3.0.0-rc9, after formatting the PC and reinstalling the software it didn't load the boards' backup correctly.

**Comment by rivafarabi** [comment]
If you don't mind, can you send the boardjson file here or through support@deckboard.app?

**Comment by Peppe-73** [comment]
Hi, as requested, I sent you an email attaching the backup file boardjson

**Comment by rivafarabi** [comment]
It seems the issue occurred when importing boards from version 2 into version 3 server app.
Will patch this week

**Comment by Peppe-73** [comment]
Thank you

**Comment by rivafarabi** [comment]
Fixed in version [3.0.0-rc9.2](https://v3.deckboard.app/releases/3.0.0-rc9.2)

If you found another issue, please open another thread. Thank you.

**Comment by Peppe-73** [comment]
Hi, I downloaded the new version, the backup loaded correctly, thanks
