### ISSUE TITLE
[BUG] Type Text: Same character in a row problem

### ISSUE THREAD

**Issue by schousda** [rivafarabi/deckboard#1080]
If there is the same character in a row in a "Type Text" action, Deckboard does not send all of them.

My Button:
![image](https://github.com/rivafarabi/deckboard/assets/21222928/8a3234d4-dd58-4c23-ac6f-ea9c693a7aac)

The result:
```
Hallo
Test
```

OS: Windows 11
v3.0.0-rc10

OS: Android 11
Version 3.0.6 beta

**Comment by rivafarabi** [comment]
Thanks for the info. Patch for this bug will be released around 8-9 May
