### ISSUE TITLE
[BUG] it just won't load

### ISSUE THREAD

**Issue by Sc4rl3t-Shad0w** [rivafarabi/deckboard#1081]
i tried everything to load my board on my phone but it keep saying "the device can't connect to your computer", i tried the tips said on the help sections but it don't work too (the USB one is too hard for me)

Computer:
-OS: Windows  11 Professionnal 23H2
-App: vestion 2.1.4

Phone:
-Xiaomi POCO F5
-OS: Xiaomi HyperOS 1.0.5.0, androud version is 14 UKQ.230804.001
-app version: 2.1.1 (reason ?)

**Comment by rivafarabi** [comment]
Have you checked this [page](https://github.com/rivafarabi/deckboard/wiki/Troubleshoot)?

**Comment by Sc4rl3t-Shad0w** [comment]
i worked thank you i just had a problems in the firewall Deckoard wasn't set correctly

**Comment by rivafarabi** [comment]
Great! Closing this issue
