### ISSUE TITLE
[FEATURE REQUEST] Touch mode on launch

### ISSUE THREAD

**Issue by longopy** [rivafarabi/deckboard#1085]
I have seen that in the new version (3.0.0-rc9.2) a new functionality has been added to indicate on which screen you want the application to appear. 
I am currently using the application on a small touch screen connected to my computer as a secondary screen and I have been loving it.
I thought it might be nice to also have the option to decide if you want the application to appear in touch mode when you start it.

Thank you for your work

**Comment by rivafarabi** [comment]
Thank you for the feedback. Both "Enable at Launch" and "Always on Top" (#1086) Touch mode settings  have been added in [3.0.0-rc9.3](https://v3.deckboard.app/releases/3.0.0-rc9.3).
