### ISSUE TITLE
[BUG] Text only lowercase / no line feed

### ISSUE THREAD

**Issue by schousda** [rivafarabi/deckboard#1087]
The "Type Text" action only outputs lowercase text.
It also seems to ignore most of the new feeds.

My Button:
![image](https://github.com/rivafarabi/deckboard/assets/21222928/e4aeca48-f88c-4d23-b26e-051d47ccc64c)

Result:
```
 testtesttest
 test
```

OS: Windows 11
v3.0.0-rc9.2

OS: Android 11
Version 3.0.7

**Comment by rivafarabi** [comment]
Thank you for the feedback. Issue has been fixed in [3.0.0-rc9.3](https://v3.deckboard.app/releases/3.0.0-rc9.3).
