### ISSUE TITLE
[BUG] Multi Actions + Copy & Paste 

### ISSUE THREAD

**Issue by schousda** [rivafarabi/deckboard#1090]
If i copy a text to paste it into a Multi Actions output, i don't get the expected result.

My button:
![image](https://github.com/rivafarabi/deckboard/assets/21222928/ba6efb20-05d8-4bce-a947-38434df07ef4)

The result after i copy "Hello" and press the button:
`Test @Test @`

Expected Result:
`Test @Hello`

Windows 11
v 3.0.0-rc9.3

Android 11
v 3.0.7

**Comment by rivafarabi** [comment]
Thanks for the feedback. The fix will be ready in 1-2 days

**Comment by rivafarabi** [comment]
This issue has been fixed in version 3.0.0-rc9.4. 
If you find another issue, please open another thread. Thank you.
