### ISSUE TITLE
[BUG] Difference between "Line Feed" and "Enter"

### ISSUE THREAD

**Issue by schousda** [rivafarabi/deckboard#1091]
I noticed a difference between older releases and v3:

Before, when i had a text like

`Test

`

a "Enter" was used and the text was sent to a chat for example.

Now it seems, like the app sends a Line Feed, because i get a new line, but the text isn't sent.

Works as designed or is it a bug?
If no but: What would be the best workaroud?
I use it maninly for different twitch chats.
Thanks.

Windows 11
v 3.0.0-rc9.3

Android 11
v 3.0.7

**Comment by rivafarabi** [comment]
Starting from 3.0.0-rc9.3 and upcoming stable version 3.0.1 in June, for app stability and performance in mind, the app won't simulate Enter key to achieve new line, instead you can use Multi Actions that use combination of "Type Text" and "Keyboard Macro" actions, with "Keyboard Macro" keypress set as "ENTER"
