### ISSUE TITLE
[BUG]Multi Action: Add Keyboard Macro

### ISSUE THREAD

**Issue by schousda** [rivafarabi/deckboard#1092]
Create a new Button
Select "Multi Actions"
Add a "Keyboard Macro"
Switch to "Sequence Input"
Press a key, for example "SHIFT"
Delete the input with the "x" to correct it
Press a key, for example "CTRL"
Press a key, for example "v"

Expected result:
`CONTROL + V`

Result:
`SHIFT + CONTROL + V`

The old values are not deleted and pasted to the field again, if you reset the field and enter a different keypress.

Windows 11
v 3.0.0-rc9.3

Android 11
v 3.0.7

**Comment by rivafarabi** [comment]
This issue has been fixed in version 3.0.0-rc9.4. 
If you find another issue, please open another thread. Thank you.
