### ISSUE TITLE
[BUG]Android Material U Icon completely blank

### ISSUE THREAD

**Issue by Arbee4ever** [rivafarabi/deckboard#1094]
**Describe the bug**
The Android App Icon is completely blank when using the Material U Design

**To Reproduce**
1. Use an Android Version with Material U available
2. install Deckboard
3. Enable Symbol Designs in Design Settings

**Expected behavior**
It should show the Deckboard logo with Material Colors

**Screenshots**
![Screenshot_20240514-161810.png](https://github.com/rivafarabi/deckboard/assets/45911516/b11c1ca1-234d-4244-9883-df68ce24ad17) Deckboard and Deckboard Pro icons side by side

**Server App (please complete the following information):**
 - OS: None
 - Version None

**Client App (please complete the following information):**
 - OS: Android 14
 - Version 3.0.7 Build 20046

**Comment by rivafarabi** [comment]
Thanks for the info. The themed icons for both version have been fixed in version 3.0.8
