### ISSUE TITLE
[BUG] Text color options

### ISSUE THREAD

**Issue by schousda** [rivafarabi/deckboard#1096]
Hello,

today i noticed, that the options to change the text color of the buttons are missing.

Older version:
![image](https://github.com/rivafarabi/deckboard/assets/21222928/62f4c132-8d62-4e33-88a1-80ca9fd3530c)

Now:
![image](https://github.com/rivafarabi/deckboard/assets/21222928/d8e50cf5-4acc-44c3-89fb-274a1d0398f6)

Windows 11
v 3.0.0-rc9.4

**Comment by rivafarabi** [comment]
What macro action you selected on the editor?

**Comment by schousda** [comment]
It does not depend on the kind of button.
The text color is missing in general as far as i can see.

**Comment by rivafarabi** [comment]
Fixed in version [3.0.0-rc9.5](https://v3.deckboard.app/releases/3.0.0-rc9.5). Thank you.
