### ISSUE TITLE
[FEATURE REQUEST] Automatic delay entries on Advanced Keyboard Macros

### ISSUE THREAD

**Issue by sebbett** [rivafarabi/deckboard#1100]
While editing an Advanced Keyboard Macro, it would help if delays of a set length could be added automatically between each keyboard action. Adding delays in manually after the fact is tedious.
![Screenshot_20240610_002229](https://github.com/rivafarabi/deckboard/assets/95005339/4549ba65-4d4f-4ea8-8b2b-00a3979446d7)

Thank you in advance :)

**Comment by rivafarabi** [comment]
Thanks for the feedback. Will make sure to add this on version 3.0.1 roadmap

**Comment by sebbett** [comment]
Absolute chad

**Comment by rivafarabi** [comment]
Fixed in version [3.0.2](https://www.deckboard.app/releases/3.0.2)

**Comment by sebbett** [comment]
Fuck Yeah my guy
