### ISSUE TITLE
[BUG] Where is New macro: Graph

### ISSUE THREAD

**Issue by alexonpeace** [rivafarabi/deckboard#1104]
**Describe the bug**
Where is New macro: Graph

**To Reproduce**
1. Go to 'Deckboard'
2. Click on '+'
3. Fill a value to 'The damn macro'
4. It doesn't exist

**Expected behavior**
It should be in the list to add

**Screenshots**

**Server App (please complete the following information):**
 - OS: Windows
 - Version 3.0.0

**Client App (please complete the following information):**
 - OS:  Android 9
 - Version 3.1.0

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

**Additional context**

**Comment by rivafarabi** [comment]
The only macro displayed as a graph in the app are Twitch's "Display Follower Count" and "Display Viewer Count"
As for the "System Info" extension that shows hardware status will be available to download around 16:00 UTC

**Comment by rivafarabi** [comment]
Hi, just released the [System Info](https://github.com/rivafarabi/deckboard-system-info) extension.
You can find it on _Extensions > Downloads_
![image](https://github.com/rivafarabi/deckboard/assets/4427494/8e978220-2f53-4dd7-98b9-9cfd1179e495)

I am closing this issue. If you have an issue with the said extension, please open a new issue on the [extension repository](https://github.com/rivafarabi/deckboard-system-info)
