### ISSUE TITLE
[FEATURE REQUEST] new extension request

### ISSUE THREAD

**Issue by pxlfl4me** [rivafarabi/deckboard#1105]
It would be perfect to create an integration with voicemeter, in previous versions there was a third-party extension but now with 3.0 I can't find it anymore.

Thx in advance!

**Comment by rivafarabi** [comment]
Hi, I just released Voicemeeter Control extension version 1.5.0 for specifically compiled for server app version 3.0.0+.
You can find it on the extension page
![image](https://github.com/rivafarabi/deckboard/assets/4427494/d6249162-1398-4853-8720-b58198b4181c)

**Comment by pxlfl4me** [comment]
I tried and actually now I find it, the only thing is that I'm encountering a problem, if I use the toggle strip parameter option, the parameter at the desired index if active is deactivated, but if I click it a second time it doesn't reactivate, would you know give me a way to solve?
