### ISSUE TITLE
[BUG] Mouse Position doesn´t work

### ISSUE THREAD

**Issue by Alex23030** [rivafarabi/deckboard#1109]
Hello, since the Update to 3.0.0 the Action Mouse Control; Move to Position doesn´t work.
I have allreade installed Deckboard completly new. But it doesn´t work.
Has someone else this Problem?

Server
 - OS: Win 11
 - Version 3.0.0

Client
 - Version 3.1.0

**Comment by rivafarabi** [comment]
Thanks for the info. It is confirmed as a bug. Will patch it as version 3.0.01, release schedule estimated tomorrow (17th June)

**Comment by rivafarabi** [comment]
Fix for this is available on patch version [3.0.1](https://www.deckboard.app/releases/3.0.1)
