### ISSUE TITLE
[FEATURE REQUEST] Empty Buttons or Remove Buttons Feature

### ISSUE THREAD

**Issue by balki97** [rivafarabi/deckboard#1110]
It would be great to have a feature to have empty buttons that does nothing. The main purpose of that is purely visual. If we can set up the button to have the same color of the background it will allow for better visual experience.  I'll show examples by images down below.

How it looks right now
![Deckboard_3miiLWE8ZT](https://github.com/rivafarabi/deckboard/assets/37090035/24121b16-2d72-4e2b-8311-4b2a7891d33e)

How It would like if the request was implemented:
![Untitled-1](https://github.com/rivafarabi/deckboard/assets/37090035/1aec44d7-61cd-4a1f-90b0-2116c3d18c54)

**Comment by rivafarabi** [comment]
Thanks for the feedback. This feature is already existed in the client app though, you can hide them by setting the "Hide blank buttons" configuration as on.

And yes, it would be nice if the same configuration applied on the server app too. I'll take note for future update.
