### ISSUE TITLE
[BUG] Infinity loading after update 3.0.0

### ISSUE THREAD

**Issue by Serjois** [rivafarabi/deckboard#1112]
After I updated the deckboard to the latest version, it stopped working. Even after reinstalling the program, I just see an endless loading. On PC.

![image](https://github.com/rivafarabi/deckboard/assets/144670996/b0163611-9df9-428d-ba83-96a91685a3aa)
**Server**
 - OS: Windows 10 Home
 - Version: 3.0.0

**Client App:**
 - OS: Android 13
 - Version 3.1.0

**Required files**
- database.db
- log.log
[Log and database.zip](https://github.com/user-attachments/files/15856543/Log.and.database.zip)

**Comment by rivafarabi** [comment]
Try to delete the database.db file

**Comment by Serjois** [comment]
> Try to delete the database.db file

Thanks, it helped. But I found out if I delete an empty board, then the program gets into an endless loading again

https://github.com/rivafarabi/deckboard/assets/144670996/3b7a46aa-eb8e-47b3-9480-15f7f88b82bd

**Comment by rivafarabi** [comment]
To prevent this from happening, in version (https://www.deckboard.app/releases/3.0.1), delete board option won't be shown if the app only has one board. 

For those who are already affected by this issue (has no board saved and infinite loading screen), the app will generate a default board ("My Board") so it can be loaded normally.

I am closing this. Feel free to open a new thread if the same issue still occurred on the latest patch.
