### ISSUE TITLE
[BUG] Buttons shrinking on client side

### ISSUE THREAD

**Issue by MightyCrusier** [rivafarabi/deckboard#1113]
**Describe the bug**
When you set a custom image on a button with text, it shrinks to a size of the text when viewed on phone. However, it shows just fine on the desktop app.

**Screenshots**
What it looks like on desktop app:
![Zrzut ekranu 2024-06-16 171150](https://github.com/rivafarabi/deckboard/assets/39172116/1c58a00d-09b9-4d1a-ac5f-4a2ce287ec28)

What it looks like on phone:
![Screenshot_20240616_171213](https://github.com/rivafarabi/deckboard/assets/39172116/1fe4fabd-976c-4cec-961c-ccc1ee0bbf47)

**Server App (please complete the following information):**
 - OS: Windows 11
 - Version 3.0.0

**Client App (please complete the following information):**
 - OS: Android 13
 - Version 3.1.01

**Required files**
[log.log](https://github.com/user-attachments/files/15858836/log.log)

[database.zip](https://github.com/user-attachments/files/15858838/database.zip)

**Comment by rivafarabi** [comment]
Thanks for the feedback. The fix will be included in today's patch

**Comment by rivafarabi** [comment]
Fix for this bug is available on client app version 3.1.02
