### ISSUE TITLE
[BUG] Buttons don't get duplicated with duplicating a board

### ISSUE THREAD

**Issue by hexandcube** [rivafarabi/deckboard#1119]
**Describe the bug**
When duplicating a board, the new board has no buttons. Only the layout and background of the board are duplicated.

**To Reproduce**
1. Duplicate Board

**Expected behavior**
A board should be duplicated with all buttons and sliderws

**Screenshots**
N/A

**Server App (please complete the following information):**
 - OS: Windows 11
 - Version 3.0.0-rc-9.5 - 3.0.1 (Stable)

**Client App (please complete the following information):**
N/A

**Required files** (Note: Those files are from 3.0.0-rc-9.5)
- [database.db](https://github.com/user-attachments/files/15921048/database.zip)
- [log.log](https://github.com/user-attachments/files/15921056/log.log)

**Additional context**
N/A

**Comment by rivafarabi** [comment]
Fixed in version [3.0.2](https://www.deckboard.app/releases/3.0.2)
