### ISSUE TITLE
OBS microphone toggle in  Multi Action [BUG]

### ISSUE THREAD

**Issue by lnaccarato** [rivafarabi/deckboard#1120]
**Describe the bug**

There is a problem when we select the microphone in multi action. It does not confirm the action resulting in non-execution.

**To Reproduce**
1. Go to 'New Button'
2. Click on 'multi action> edit> add action.'
3. Fill a value to '.Action=Audio source control>Select microphone>Toggle Mute'

**Expected behavior**

mute or unmute the microphone.

**Screenshots**
I![image](https://github.com/rivafarabi/deckboard/assets/173462827/80a2088f-0a74-4c3d-907d-af4cd6f4ef54)

**Server App (please complete the following information):**
 - OS: Windows 
 - Version 10

**Client App (please complete the following information):**
 - OS: Android

 - Version 11

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)[log.log](https://github.com/user-attachments/files/15926890/log.log)

**Additional context**
Your App is the best !

**Comment by rivafarabi** [comment]
Fix will be added in tomorrow's update. Thanks for the feedback

**Comment by mordang7** [comment]
Issue still present in 3.0.2 fix unfortunately.

**Comment by rivafarabi** [comment]
Do you mind share the screenshot or screen capture showing the bug/issue?

**Comment by mordang7** [comment]
Thank you for your help, as you can see in this picture, my mic in OBS is
active, the icon on the PC side of Deckboard has updated its state to
active, but the icon on the Android app - even though it does work - will
just stay in the inactive state.

**Comment by rivafarabi** [comment]
The main issue mentioned in the first post has been resolved in version [3.0.2](https://www.deckboard.app/releases/3.0.2)
While the issue mentioned by @mordang7 here and in #1121 has been fixed in version [3.0.3](https://www.deckboard.app/releases/3.0.3)

Feel free to open a new thread if you still face this bug.

Closing this.
