### ISSUE TITLE
Discord deckboard extension BUG

### ISSUE THREAD

**Issue by GAMINGCHATS** [rivafarabi/deckboard#1124]
**Describe the bug**
When I go to authorize deckboard bot in discord the authorize button is grayed out

**To Reproduce**
1. Follow [this guide](https://github.com/aislandener/discord-deckboard)
2. Make any buttons as you want
3. try to authorize the bot/app
4. See bug

**Expected behavior**
The authorize button not be grayed out

**Screenshots**
![image](https://github.com/rivafarabi/deckboard/assets/90594728/a6439922-fd37-4c53-b8a7-b8e8d48a169a)

**Server App (please complete the following information):**
 - OS: Windows 11 23H2
 - Version: 3.0.1

**Client App (please complete the following information):**
 - OS: Android 14
 - Version: 1.9.80

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

[deckboard-errors.zip](https://github.com/user-attachments/files/15987383/deckboard-errors.zip)

**Comment by BabyBluJ-wall** [comment]
Yea im having the same issue with discord and deckboard. Just started today as yesterday i was able to authorize it.

**Comment by GAMINGCHATS** [comment]
> Yea im having the same issue with discord and deckboard. Just started today as yesterday i was able to authorize it.

How did you fix it?

**Comment by BabyBluJ-wall** [comment]
> > Yea im having the same issue with discord and deckboard. Just started today as yesterday i was able to authorize it.
> 
> How did you fix it?

I have no idea i logged on today and it wont authorize

**Comment by Simego** [comment]
still works for me but i think it's better to add an issue over at https://github.com/aislandener/discord-deckboard instead

**Comment by BabyBluJ-wall** [comment]
> still works for me but i think it's better to add an issue over at https://github.com/aislandener/discord-deckboard instead

I got it to work again. Anytime discord wants authorization make sure you scroll down on that page all the way, it registers that way.
