### ISSUE TITLE
[BUG] Phone screen brightening does not work in the deckboard app

### ISSUE THREAD

**Issue by skynereidof** [rivafarabi/deckboard#1126]
Screen brightening on your phone doesn't work in the deckboard app

I increased the screen brightness to 100%, all applications are very bright, but the deckboard is terribly dark.

Phone - Motorola e20
Computer - Fedora 40 Linux
[log.old.log](https://github.com/user-attachments/files/16043807/log.old.log)

**Comment by rivafarabi** [comment]
Thanks for the feedback. I will look into it

**Comment by rivafarabi** [comment]
I've brought back in-app brightness setting and "Use system brightness" toggle setting in client app version 3.1.4
The "Brightness" setting will be shown when you toggle off "Use system brightness".

Please feel free to open another ticket if you face the same issue.

Closing this.
