### ISSUE TITLE
[BUG] Derckboard not working on windows 10 Orca Slicer

### ISSUE THREAD

**Issue by jbrenes76** [rivafarabi/deckboard#1128]
**Describe the bug**
Deckboard works well on all my pc apps, but not on orca slicer a 3D slicer program for 3D printers.

**To Reproduce**
1. Have Deckboard working
2. Make a test run on other apps to see its working
3. Open -Orca Slicer- test Deckboard

**Expected behavior**
Deckboard just does not work on the app, its like something is blocking specificly the macros and keypress on the app. I tried using Control+6 macros did not work, then sequence macros recorded...that did something kind of worked but said this error.: "**_A JavaScript error occurred in the main process,Uncaught Exception:Error: Invalid key code specified.at Tmeout._onTmeout
at listOnTmeout,at process.processTmers_**"

**Server App (please complete the following information):**
 - OS: Windows
 - Version 10

**Client App (please complete the following information):**
 - OS: Android
 - Version Latest at writing / 03.07.2024

**Comment by rivafarabi** [comment]
Thanks for the feedback. Just fixed this issue. I will release the patch tomorrow.

**Comment by rivafarabi** [comment]
The fix for this issue has been included in the latest version [3.0.4](https://www.deckboard.app/releases/3.0.4)

If you face another issue, feel free to open a new thread. Thank you.

Closing this.

**Comment by jbrenes76** [comment]
Woa thx! I'm not really a good programmer or anything it just dabble on
this.... It's good to know I contributed a bit to a program that I use
everyday. Thank you buddy and have a good day.... The bug was killing me
because I used deck board on just about everything..... It's good to know I
get to use it now on my 3D printing dive.... Have a good day friend.
