### ISSUE TITLE
[BUG] Extension buttons not working on mobile for recent versions

### ISSUE THREAD

**Issue by Simego** [rivafarabi/deckboard#1129]
**Describe the bug**
Buttons on mobile show "NO DATA" and nothing works after some recent updates, works fine on PC.

**To Reproduce**
1. Add a Discord Deckboard extension
2. Add toggle button
3. Open mobile app
4. "NO DATA" shown, button doesn't work (works on PC)

**Expected behavior**
Button should change text and work

**Screenshots**
![image](https://github.com/user-attachments/assets/015c295c-bb47-44af-a354-be859f7b13a2)
![image](https://github.com/user-attachments/assets/f2b303f2-4b7f-4135-816e-961617c489ac)

**Server App (please complete the following information):**
 - OS: Windows
 - Version 3.0.4

**Client App (please complete the following information):**
 - OS: Android
 - Version 3.1.4

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

**Additional context**
This issue started a while back, i mentioned about it as well here: https://github.com/rivafarabi/deckboard/issues/1121#issuecomment-2188464101

Can you also provide some way to know how to implement proper toggle buttons?
The code for this is not present in any place, only in native deckboard features, i want to improve the other extension for better use.

**Comment by rivafarabi** [comment]
Can you send me the database.db file (located in `C:\Users%USER%\deckboard`)
I can't replicate this issue yet.

**Comment by rivafarabi** [comment]
OK I finally able to replicate the issue. 

And for some reason, the latest released extension file (version [1.1.3](https://github.com/aislandener/discord-deckboard/releases/tag/v1.1.3)) has version 1.1.2 contents (will notify the maintainer soon) 

That's why I cannot replicate the issue using version "1.1.3", and finally able to by using the code from the repo's main branch

Will look into this this weekend.

**Comment by Simego** [comment]
> OK I finally able to replicate the issue.
> 
> And for some reason, the latest released extension file (version [1.1.3](https://github.com/aislandener/discord-deckboard/releases/tag/v1.1.3)) has version 1.1.2 contents (will notify the maintainer soon)
> 
> That's why I cannot replicate the issue using version "1.1.3", and finally able to by using the code from the repo's main branch
> 
> Will look into this this weekend.

Thanks, i wasn't able to get the db yet..

I've seen some people mentioning they couldn't update to 1.1.3 as well maybe it's related

also, since it's kind of related to same types of button, do you have some examples on how to implement toggle buttons with 2 styles for extensions? pressed and not pressed etc, like exists for OBS audio sources natively in Deckboard, thanks a lot!

**Comment by Simego** [comment]
@rivafarabi it's working now on the new version, thanks!
