### ISSUE TITLE
cannot create buttons to open programs

### ISSUE THREAD

**Issue by Chris-FireFox** [rivafarabi/deckboard#113]
im missing the option to create button on the app to open programs / folders and the like. the system line under types i can select is greyed out and cannot be selected and i cant figure out how to do it with the other options avalible
![deckboard](https://user-images.githubusercontent.com/21243628/51788090-5b1f1080-217a-11e9-862e-d1a27bf8da7b.gif)

**Comment by rivafarabi** [comment]
The options is scrollable. It should show the rest of the actions
