### ISSUE TITLE
[BUG] Keyboard Macro Tabulator doesn´t work

### ISSUE THREAD

**Issue by Alex23030** [rivafarabi/deckboard#1130]
Keyboard Macro "Tabulator" doesn´t work in Version 3.0.5

Thanks for fixing

**Comment by rivafarabi** [comment]
Do you mean "tab" key?

**Comment by Alex23030** [comment]
Yes, Tab Key doesn´t work. Also in Version 3.0.6

**Comment by rivafarabi** [comment]
Ok found the problem. Will patch it this weekend.
But, just to make sure, may I know the whole keypress sequence you have tried?

**Comment by Alex23030** [comment]
Thanks for fixing.
The whole sequence was: Tab, Arrow Left, CTRL+V, Tab, CTRL+C
But also Tab as Single Keypress doesn´t work.

**Comment by rivafarabi** [comment]
Is that button for one button or separately? Care to give me a screenshot?

**Comment by Alex23030** [comment]
It doesn´t work as Keyboard Macro and also in Multi Action
![Screenshot 2024-08-02 090927](https://github.com/user-attachments/assets/29cab2f9-8cdc-46e3-ba31-64147152a269)

**Comment by rivafarabi** [comment]
Sorry for the long wait. the fix is included in version [3.0.7](https://www.deckboard.app/releases/3.0.7).

If you find a new or related issue, please open a new thread.
Thank you
