### ISSUE TITLE
[BUG] No "Open File" action in Multi Actions Sequence action options

### ISSUE THREAD

**Issue by joao-carmassi** [rivafarabi/deckboard#1133]
**Describe the bug**
There is no button to open file in a multi action sequence.

**Screenshots**
![image](https://github.com/user-attachments/assets/b427a97f-b9ae-400f-a020-21de093240ab)
![image](https://github.com/user-attachments/assets/a32b527e-e340-4890-b74b-dbc4f23fd31b)

**Server App (please complete the following information):**
 - Windows
 - Version 3.0.6

**Comment by rivafarabi** [comment]
Thanks for the finding. Will fix this in the next patch release

**Comment by rivafarabi** [comment]
Sorry for the long wait. The fix is included in version [3.0.7](https://www.deckboard.app/releases/3.0.7).

If you find a new or related issue, please open a new thread.
Thank you
