### ISSUE TITLE
[FEATURE REQUEST] LibreHardwareMonitor Extension

### ISSUE THREAD

**Issue by Chinchillus** [rivafarabi/deckboard#1137]
**Is your feature request related to a problem? Please describe.**
Yes, Open Hardware Monitor doesn't display my cpu usage correctly, I use latest Windows 11 and my CPU is i5-11400F

**Describe the solution you'd like**
Integration with LibreHardwareMonitor because its newer and it supports newer CPU's 

**Describe alternatives you've considered**
Changing something in OHM so it displays usage and temperature correctly

**Additional context**
![image](https://github.com/user-attachments/assets/a27fc81c-1fe0-4afb-98b1-d3941321bf37)

**Comment by rivafarabi** [comment]
Hi, I've just released an extension for displaying Libre Hardware Monitor data. It is available to download on Deckboard. 

If you have an issue with the extension, please open a issue to its repository [here](https://github.com/rivafarabi/deckboard-librehardwaremonitor)

![image](https://github.com/user-attachments/assets/b4a73313-2f75-4145-bde4-ea80d503a7a4)
