### ISSUE TITLE
[BUG] With extendable buttons

### ISSUE THREAD

**Issue by Trane20121** [rivafarabi/deckboard#1139]
**Describe the bug**
Hello, as you can see from the screenshot, i' m unable to extend the volume sliders (OBS and Windows both). I've already tried older versions but without succeed to resolve the bug...I've the same bug with the librehardwaremonitor-extension, i' cant extend the graph

**To Reproduce**
1. Click on 'add button',
3. Under OBS section, select Audio Volume Control,
4. Add.

**Expected behavior**
As you shown on the website, i would be able to extend the audio slider

**Screenshots**
![image](https://github.com/user-attachments/assets/9ec9565b-0cd2-4837-95ef-2c7a034e5246)
![image](https://github.com/user-attachments/assets/5a798b03-75c6-49c3-b8c0-088d048337ad)

**Server App (please complete the following information):**
 - OS: Windows 11 23H2,
 - Version 3.0.7 (i've tried older versions too like: 3.0.0-rc9.4.)

**Comment by rivafarabi** [comment]
Have you tried resize it on the server app like shown in the video?
https://github.com/user-attachments/assets/19f9ae1a-7377-4c6f-b08e-aab4bd6b6d26

**Comment by Trane20121** [comment]
> Have you tried resize it on the server app like shown in the video? https://github.com/user-attachments/assets/19f9ae1a-7377-4c6f-b08e-aab4bd6b6d26

After other unistall and installation, with deep clean of all files. It does work now...Thank you

**Comment by Trane20121** [comment]
> Have you tried resize it on the server app like shown in the video? https://github.com/user-attachments/assets/19f9ae1a-7377-4c6f-b08e-aab4bd6b6d26

After other unistall and installation, with deep clean of all files. It does work now...Thank you
