### ISSUE TITLE
[Request] Pro users to define own button grid.

### ISSUE THREAD

**Issue by Nenniana** [rivafarabi/deckboard#114]
I'd like to request that Pro users would be able to define their own button grid.

This would include changing the number of buttons, like 6x5, 7x7 and so forth. This would of course also change the size of the buttons. 
This would give more control at the users' fingertips while using a tablet or other bigger device.

**Comment by rivafarabi** [comment]
I've been experimenting 5x6 grid for tablet only. But stopped halfway because I was focused on migrating the app with new framework. 

Now the work is done, I can work on it. Hopefully the feature will be completed in mid-February :)

**Comment by rivafarabi** [comment]
custom grid features added on version 1.4.0
