### ISSUE TITLE
No data - Streamlabs - Slider icon[BUG]

### ISSUE THREAD

**Issue by eleniagn** [rivafarabi/deckboard#1148]
**Describe the bug**
Added a slider to control audio from **Streamlabs** and in the companion app it shows up as "No data". To test, I also added a system audio control slider, and this one works fine. So I assume there's something wrong with streamlabs integration. All other streamlabs buttons work fine.
  
**To Reproduce**
1. Go to 'Deckboard'
2. Click on 'Add new button -> Streamlabs -> Add valume control'
3. Go to android companion app
4. See error "No Data"

**Server App (please complete the following information):**
 - OS: Windows
 - Version: 3.0.8

**Client App (please complete the following information):**
 - OS: Android 10
 - Version 3.1.5

I tried on a different tablet and phone and it has the same issue

**Comment by eleniagn** [comment]
Any updates on this? If you need more information, let me know!

Thanks!

**Comment by rivafarabi** [comment]
Hi, sorry the development kind of slow right now. The patch expected to be released this weekend.
Sorry for the inconvenience

**Comment by rivafarabi** [comment]
Thanks for reporting this issue! We've addressed it, and the fix has been implemented in version [3.0.9](https://www.deckboard.app/releases/3.0.9). Closing this issue now. Feel free to reopen if further assistance is needed.
