### ISSUE TITLE
Android App Blank White Screen Android 5.1

### ISSUE THREAD

**Issue by TheSeanFischer** [rivafarabi/deckboard#116]
Downloaded on Anroid 5.1 but the screen just popps up white, nothing on screen.

**Comment by rivafarabi** [comment]
Can you tell me what version you used on both your PC and phone?

**Comment by BassDudu** [comment]
Same problem on Android 4.4.2 with an Asus Tablet.
Windows 10 and Deckboard 1.2.7 
It works fine with my phone.
Do you need more info ?

**Comment by rivafarabi** [comment]
is the bug started right after the app opened or when the app tried to navigate to board page?

**Comment by BassDudu** [comment]
Directly when I launch the app. I can't do anything on the app.

**Comment by SEBSOfficiel** [comment]
I have the probleme my version android is 4.2.2. 
Windows 8.1

**Comment by rivafarabi** [comment]
As far as the data goes, the issue only occurred on some devices that run OpenGL ES ver 2. 

At this point it, it can't be fixed, unless the team behind Flutter, the framework I used to create the app, address this issue.

**Comment by f2bacon** [comment]
my samsung galaxy tablet worked fine for years until yesterday (11/17/22). there were no updates done. i changed my grid size and when i went to refresh the board, it's a white screen. switching the board size doesnt solve the problem. uninstalling deckboard on the tablet doesnt fix it either
