### ISSUE TITLE
Extensions for Deckboard

### ISSUE THREAD

**Issue by rivafarabi** [rivafarabi/deckboard#119]
Here is the list of working extension for Deckboard

- [Power Control](https://github.com/rivafarabi/deckboard-power-control) - Shutdown and restart functions for Deckboard

If you want to get your own extension listed, just write it down.

**Comment by BorjaLagarejo** [comment]
I followed the steps, but I get this error

![image](https://user-images.githubusercontent.com/25508619/52540761-9b42dd80-2d8d-11e9-8432-11c942837409.png)

**Comment by rivafarabi** [comment]
> I followed the steps, but I get this error
> 
> ![image](https://user-images.githubusercontent.com/25508619/52540761-9b42dd80-2d8d-11e9-8432-11c942837409.png)

Have you installed the extension according the step in this [page](https://github.com/rivafarabi/deckboard/wiki/Extensions)?

**Comment by BorjaLagarejo** [comment]
I have tried several ways, but I have already found the solution.
The instructions are a little messy.

![image](https://user-images.githubusercontent.com/25508619/52585419-f7147180-2e34-11e9-8066-4781a60c284b.png)


Greetings, thanks for responding so fast.

**Comment by MaximeL** [comment]
> 
> 
> I have tried several ways, but I have already found the solution.
> The instructions are a little messy.
> 
> ![image](https://user-images.githubusercontent.com/25508619/52585419-f7147180-2e34-11e9-8066-4781a60c284b.png)
> 
> Greetings, thanks for responding so fast.

Can you provide what was your workaround ? I want to develop extension too and have similar issues. 
The documentations for building extension miss some explanation and have some error.

**Comment by BorjaLagarejo** [comment]
> > I have tried several ways, but I have already found the solution.
> > The instructions are a little messy.
> > ![image](https://user-images.githubusercontent.com/25508619/52585419-f7147180-2e34-11e9-8066-4781a60c284b.png)
> > Greetings, thanks for responding so fast.
> 
> Can you provide what was your workaround ? I want to develop extension too and have similar issues.
> The documentations for building extension miss some explanation and have some error.

Hi @MaximeL , sorry for the delay, I've been a little busy.

The steps I have followed are in the documentation https://github.com/rivafarabi/deckboard/wiki/Extensions

Note that the extensions folder is created with the deckboard installation.
Located in `C: \Users {user-name}\ deckboard`

![image](https://i.imgur.com/LCUzRg0.png)

Then in the "extensions" folder, clone the project, you can use it as an example for your future extensions.
https://github.com/rivafarabi/deckboard-power-control

Make sure the application is closed, then run it again (it will take a while).

![image](https://i.imgur.com/AGHuD7S.png)


Hope that helps, best regards

**Comment by MaximeL** [comment]
Thanks for the reply @BorjaLagarejo.  

Basically you tell me to make my extension from a copy of a existing and working one. It's a good workaround but it would be a good thing to improve the documentation of building extension to be able to create one from scratch and for non expert (like me).
I use deckboard, I really want to help by writing extension, and I find it also a good way to learn and improve in node and js. That why the workaround doesn't suit me, because more of just wanting it to work, I want to understand how it should work, what is core code, and what is extension code.

I listed some point to improve and raised some question about the documentation in this issue :   https://github.com/rivafarabi/deckboard/issues/318  

It would be very helpful for me and certainly other if you could answer some question and if @rivafarabi could update the doc according to these points.

**Comment by Liwixion** [comment]
Can someone make a discord extension to control discord please ?

**Comment by LinuxGamesTV** [comment]
Hi i wrote a Amarok Control Extension, like the Multimedia Control. The extension works quite well so far, except for the icons. They are not set automatically.

`	constructor() {
		super();
		this.name = 'Amarok';
		this.platforms = [PLATFORMS.LINUX];
                this.inputs = [
		    {
			label: 'Amarok',
			value: "amarok",
			icon: 'music',
			color: '#38761D',
                        input: [
                        {
				label: "Control",
				ref: "control",
				type: INPUT_METHOD.INPUT_SELECT,
                                items: [
                                {
					value: "play_pause",
					label: "Play / Pause",
					icon: 'play',
					fontIcon: 'fas',
                                }, {
					value: "stop",
					label: "Stop",
					icon: 'stop',
					fontIcon: 'fas',
                                }, {
					value: "next",
					label: "Next",
					icon: 'fast-forward',
					fontIcon: 'fas',
                                }, {
					value: "previous",
					label: "Previous",
					icon: 'fast-backward',
					fontIcon: 'fas',
                                }, {
					value: "stop_after_current",
					label: "Stop after the current Song",
					icon: 'eject',
					fontIcon: 'fas',
                                }, {
					value: "replay",
					label: "Replay",
					icon: 'redo',
					fontIcon: 'fas',
                                }, {
					value: "toggle_main_window",
					label: "Toggle Main Window",
					icon: 'clone',
					fontIcon: 'fas',
                                }, {
					value: "mute",
					label: "Mute",
					icon: 'mute',
					fontIcon: 'fas',
                                }, {
					value: "increase_volume",
					label: "Increase Volume",
					icon: 'volume-up',
					fontIcon: 'fas',
                                }, {
					icon: 'volume-down',
					fontIcon: 'fas',
					value: "decrease_volume",
					label: "Decrease Volume",
                                },
			    ]
			},
		    ]
		},
	    ];
        this.initExtension();
    }
`

**Comment by rivafarabi** [comment]
All extension related thread will be closed. Please report issue to each extensions' repository
