### ISSUE TITLE
[DEVELOPMENT STATUS] Streamlabs OBS, Mobile App Settings Configuration and More

### ISSUE THREAD

**Issue by rivafarabi** [rivafarabi/deckboard#12]
Hello guys. Farabi here!

As you know, from a number of reddit posts, there will be Streamlabs OBS support for Deckboard and other features such as button size setting, social media integrations, and more.

Unfortunately, I will postpone the development for couple weeks from now on because of health issue. It's okay, It's nothing serious, just need couple week of rest and I will continue the development once I get better.

Thanks for your understanding.

**Comment by ubergeekseven** [comment]
Thanks!

**Comment by graph-kgrondin** [comment]
Thanks for the update! Will be great iff you enable a release tab in github to see new feature. I know we can see them in the app, but it's great for people who discover the app to see a release tab here.
