### ISSUE TITLE
Multi Action

### ISSUE THREAD

**Issue by BorjaLagarejo** [rivafarabi/deckboard#122]
A suggestion that would be quite useful.

![image](https://user-images.githubusercontent.com/25508619/52871194-c80a4280-3149-11e9-8eb8-a3270ce6305c.png)

**Comment by rivafarabi** [comment]
love it. Gonna working on this next month.

**Comment by spesvictus** [comment]
You  could get streamdeck mini and see what features from Streamdeck  can be implemented on Deckboard. then go above and beyond.  

Also, you could work with iOS App Developer for porting Deckboard to iOS.
