### ISSUE TITLE
Can't play audio

### ISSUE THREAD

**Issue by Thosquey** [rivafarabi/deckboard#126]
I can create and set up buttons to play audio, but they're not working.
![deckboard_2019-02-21_16-01-49](https://user-images.githubusercontent.com/25712482/53178405-127c3b00-35f2-11e9-8260-c89febc8eb1a.png)
![deckboard_2019-02-21_16-02-36](https://user-images.githubusercontent.com/25712482/53178419-1c9e3980-35f2-11e9-8694-39eae1886554.png)
I tried with all the following format : mp3, aac, ogg, m4a, wma, flac, wav and even video ones such as mp4, avi and mov.
The button is here, I can tap it on my phone but nothing happens. Other functionnalities are working great.

**Comment by LeoMikaelson** [comment]
I too am having the same issue! Are there any solutions to this problem?

**Comment by LeoMikaelson** [comment]
Does it work on the pro version as literally I want to buy it!

**Comment by rivafarabi** [comment]
Finally found the fix. Going to release the  patch this weekend.

**Comment by Thosquey** [comment]
Perfect, thanks !
