### ISSUE TITLE
Automatic Update

### ISSUE THREAD

**Issue by Redorstone** [rivafarabi/deckboard#134]
Can you create a automatic update of the Windows app , if it's doesn't exist already ( i didn't find ) or a parameter in the setting or something like that please !!!

Thank you so much!

**Comment by RH-Code** [comment]
It would be great indeed to have the possibility to update the app from within the app instead of just getting a message that there's an update and having to go to the website to download.

**Comment by digitalfiz** [comment]
Or at least a link to the update in the popup so we don't have to go searching for the link would be a good start :P

Electron has some really neat tools to allow for automatic updates.
https://electronjs.org/blog/autoupdating-electron-apps

Update servers (both should be able to run on free heroku tier):
https://github.com/zeit/hazel
https://github.com/atlassian/nucleus

Not sure if your willing to go the extra step and do code signing but this article is good:
https://www.electron.build/auto-update
