### ISSUE TITLE
Problems with board sorting

### ISSUE THREAD

**Issue by tipek360** [rivafarabi/deckboard#137]
I wanted to sort my boards but application started to glitch when i wanted move with board.
Deckboard v1.3.0

Here is how it looks:
[Deckboard: Board sorting glitch - Gfycat](https://gfycat.com/meanalleasternnewt)
[Deckboard: Board sorting glitch - Google Drive](https://drive.google.com/open?id=1BTFObXv_tVj8mUyv_EsbVzEx4_WrV7Y9)

**Comment by SEBSOfficiel** [comment]
@rivafarabi I had this problem when I switched to my V1.3.0

**Comment by SEBSOfficiel** [comment]
I get the impression that the bug happens when we have more than 5 boards

**Comment by tipek360** [comment]
Nope it  too glitches when I have only 3 boards.

**Comment by SEBSOfficiel** [comment]
@tipek360 ok ;)

**Comment by SEBSOfficiel** [comment]
I tested well and I've got the first 2 boards that bug

**Comment by tipek360** [comment]
Issue was fixed many versions back but this issue was forgotten and it remain open.
