### ISSUE TITLE
1.2.0 issues: Android app can't connect to PC, PC app can't connect to OBS

### ISSUE THREAD

**Issue by darioriccioni** [rivafarabi/deckboard#14]
Hi. As the title says, I'm having issues with version 1.2.0 on PC. The Android app can't connect to my PC if I use 1.2.0, but if I use the old 1.0.5 app on PC both my smartphone and tablet can connect to it (devices automatically updated the Android app to 1.2.1). Adding to this, the 1.2.0 version on PC can't connect to OBS, while if I revert back to 1.0.5 it can connect. So, I don't know why but it seems 1.2.0 (at least for me) can't connect to anything.

**Comment by rivafarabi** [comment]
Did you use version 1.2.0 of the android app while connecting on version 1.2.0 of PC app?

**Comment by rivafarabi** [comment]
And did you use password authentication for your OBS connection?

**Comment by darioriccioni** [comment]
The version of the Android app used is 1.2.1, Windows firewall is set up already to allow connection to Deckboard and I tried both with and without password.

**Comment by darioriccioni** [comment]
Tried to completely uninstall and do a clean install on PC, smartphone and tablet. Now the Android app can connect to the PC, but the PC app still can't connect to OBS. Even tried reinstalling websocket but it didn't work.

**Comment by rivafarabi** [comment]
Have you tried changing the websocket port in both OBS Studio and Deckboard settings without the password?

**Comment by rivafarabi** [comment]
And it looks like I found a bug in websocket authentication. I'll fix this in the next patch ASAP.

**Comment by darioriccioni** [comment]
Sorry for the late reply. I tried changing the port and it worked, now works even if I put back the default 4444 port.

**Comment by rivafarabi** [comment]
Glad to hear that. Thanks for letting me know. I'll keep this issue open until websocket authentication issue solved.

**Comment by rivafarabi** [comment]
Fixed in version 1.2.3
