### ISSUE TITLE
JS ERROR

### ISSUE THREAD

**Issue by Maxeuh** [rivafarabi/deckboard#141]
Error when the program start. It's not possible to connect the app to the computer.
![image](https://user-images.githubusercontent.com/36711255/54049730-9ed75200-41dd-11e9-8156-82a290599103.png)

**Comment by Maxeuh** [comment]
> Error when the program start. It's not possible to connect the app to the computer.
> ![image](https://user-images.githubusercontent.com/36711255/54049730-9ed75200-41dd-11e9-8156-82a290599103.png)

**Comment by rivafarabi** [comment]
you need to run `npm install` in the extension folder (in your case C;/Users/maxen/deckboard/extensions/deckboard-power-control-master)

**Comment by Maxeuh** [comment]
Yeah! Thanks!
