### ISSUE TITLE
server application installation size

### ISSUE THREAD

**Issue by alfadormx** [rivafarabi/deckboard#144]
Hello,

I just wonder how come the installation size of an application like this is 500MB. Are all those dependencies necessary to be included in the final package? Is there not a way to actually remove the unused elements of those dependencies in order to make the installation size smaller?

Thanks,
HH

**Comment by nblackburn** [comment]
It's an Electron application so they generally are pretty large by default but it's including electron as part of that effectively doubling the size before even looking at the other dependencies.

**Comment by rivafarabi** [comment]
> It's an Electron application so they generally are pretty large by default but it's including electron in itself effectively doubling the size before even looking at the other dependencies.
> 
> Here are some of the dependencies making up the large size...
> 
> * unicode - 136.4mb
> * electron - 115.6mb
> * sqlite 3 - 27.6mb
> * rxjs - 8mb
> * vuetify - 4.7mb
> 
> ![image](https://user-images.githubusercontent.com/2931085/56315984-17bcb880-6151-11e9-82b6-03997855fa94.png)

thanks for the details. RobotJS also contributing to the installation size. It's around 50-80mb. Yeah, It's quite large and I'm still figuring out to reduce it for the last 2 months.

**Comment by alfadormx** [comment]
Thank you for the detailed reply guys! very illustrative indeed.
