### ISSUE TITLE
Different device for pro

### ISSUE THREAD

**Issue by yanki777** [rivafarabi/deckboard#148]
Greetings, I recently bought the pro version, but I can't install on my second phone (which uses same Google account) it requires purchase and when I tried to install via web on PC it says"An unexpected error has occured, please try again later." Should I refund and buy from other device?

**Comment by digitalfiz** [comment]
You shouldn't have to. If Google says you have to buy it again it might not
be the same Google account. I would verify that first.

**Comment by yanki777** [comment]
I solved somehow, i refunded and bought from other device. That do the trick. Thnx for the interest mate cheers
