### ISSUE TITLE
Keyboard Macro not recognized other than windows defaults

### ISSUE THREAD

**Issue by animeponch** [rivafarabi/deckboard#15]
I don't know how but macros other than those from windows (CTRL + C, CTRL + V etc.) are not executed.
For example: in OBS Studio I use hotkeys that allow me to do several things at a time. For example ALT + 1 allows me to disable more than one Source from a scene. If I execute the command from the keyboard I have no problems, even without having obs in the foreground, but when I launch the same command from deckboard, it is not recognized.

**Comment by rivafarabi** [comment]
Ok, it seems I can reproduce the bug you mentioned. I will try to fix em. Thanks for the report 👍

**Comment by animeponch** [comment]
I would also like to provide you with tips to improve the application.
Perhaps there is a better way to communicate them and if there is, I ask
you to tell me where to send them.

Anyway:

It would be useful, if the buttons could have more states such as "turned
on/off" or "Pressed / Unpressed" or again "Selected / Unselected", and, for
example, by having the opportunity to insert two types of different icons
that change depending on the state or, if not specified, the icon could
simply turn black and white.
It would be nice that the tabs on the pc could be sorted manually (maybe
through arrows or drag & drop)

If I can think of anything else I'll let you know. I'll also buy the PRO
version soon, in order to contribute.

I hope I have been helpful.

2018-08-02 12:00 GMT+02:00 Riva Farabi <notifications@github.com>:

**Comment by rivafarabi** [comment]
Fixed in version 1.2.3
