### ISSUE TITLE
Feature Progress for upcoming v1.4

### ISSUE THREAD

**Issue by rivafarabi** [rivafarabi/deckboard#152]
Here's the feature progress for the upcoming update.

- [x] Multiaction (50% Complete)
- [x] Custom grid size per board
- [x] Spotify volume control
- [x] Select spotify playlist by copy paste open.spotify,com url
- [x] Manual ADB service toggle

~~Finished features will be available on Release Candidate released on 28th April (Yes, I do RC now)~~
Version 1.4.0 will be released on 1st May ~~April~~  and patch for multiaction function scheduled on 6th May ~~April~~

**Comment by HeCodes2Much** [comment]
is this out now? it was the 28th yesterday :)

**Comment by rivafarabi** [comment]
@HeCodes2Much oops. Some typos we got there. I mean May, not april. Had to delay the release because some unexpected circumstances.

**Comment by aKuhTV** [comment]
How is it going with the multi-action patch?

**Comment by rivafarabi** [comment]
> How is it going with the multi-action patch?

Just wrapped up the development :) It will be available in couple of days.

**Comment by rivafarabi** [comment]
multiaction updated in version 1.4.1
