### ISSUE TITLE
button colour doesn't change on device

### ISSUE THREAD

**Issue by Scarecrow631** [rivafarabi/deckboard#155]
Using the pro app (didnt try with free) if I change the colour of a button on the server, it takes an app reset on my tablet for the colour changes to propagate

**Comment by Scarecrow631** [comment]
Further to that, if I then add another button (in this case, a folder) it reset the colours of the buttons.

[Here](https://i.imgur.com/dmAbIbL.png) is the server side
[Here](https://i.imgur.com/QONyp78.png) is the client side

**Comment by digitalfiz** [comment]
I noticed this too.

**Comment by rivafarabi** [comment]
Thanks for the report. I'll check this issue. Btw which version are you using on both platforms?

**Comment by digitalfiz** [comment]
I am using the 1.3.0 windows app and all updates on android are done. This has been the same for me for the last few updates though.

**Comment by Scarecrow631** [comment]
Same story here, 1.3 on the server and up to date on droid

**Comment by rivafarabi** [comment]
fixed in version 1.4.0
