### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by Scarecrow631** [rivafarabi/deckboard#157]
Just a few ideas off the top of my head after setting up deckboard for Star Citizen.

1. Being able to disable (or colour) the border around buttons
2. Trimming the amount of buttons on the server side, and more options there would be nice (5 x 3 comes to mind)
3. Setting default settings for buttons (colors and text positions)

That's all I got, thanks for making a kick ass app!

EDIT: Added 3rd point

**Comment by rivafarabi** [comment]
1. Absolutely love the idea
2. The next update (1.4.0, will be released on 1st April) will include this feature. It will include new larger grid size, 6x5 and 5x5 + all available layout in client side. Unfortunately 5x3 layout will not be available in initial release of the feature. More details coming soon.
3. Noted for future reference.

**Comment by Scarecrow631** [comment]
In relation to 1, you can sort of get around this by changing the button colour, but then you run into the issue i raised in https://github.com/rivafarabi/deckboard/issues/155#issue-435466679

Also I have seen you saying that 1.4 will drop April 1st, but its the end april, do you mean may 1st?

**Comment by AngelicDivine** [comment]
yea thats what im thinking im like am i going crazy or something XDD

**Comment by rivafarabi** [comment]
custom grid layout is available in version 1.4.0
