### ISSUE TITLE
Feature request - audio sample toggle

### ISSUE THREAD

**Issue by wociscz** [rivafarabi/deckboard#16]
Would be perfect if the app could toggle playing some sound (wav/mp3/ogg). So i'll be able to have screen with "sound emotes" :-)
I know that it is somehow possible with obs and toggling "media sources" but that is little bit complicated.
And it will be mega-super if this function has multiple triggers like 
1) start/stop/start button - with one button you will start the sound and with the same you will stop the sound (for longer jingles). pressing it again will play the sound from beginning.
2) start/pause/continue - with one button you will start the sound and with the same you will pause and next push will trigger continuing the sound.
3) hold button for looping - until you holding the button, the sound will loops 
4) play again button - if you press the button the sound will be played again from start...
5) general stop button - if some trigger is in action (for example 2) this button will stop all sounds and reset to silence.
?) some other trigger method?

So in general implement "audio" player with multiple triggering options...
Sorry if this is not the right place for "feature requests".

edit: and if you have paypal, put the address somewhere. I'll send you some bucks for the beer.
Regards,
Jan

**Comment by rivafarabi** [comment]
Have checked version 1.2.3? It has new action called "Play Audio". even though it only has one trigger like point number 4 you mentioned (play again button).

If you are from version 1.2.0 and experienced a bug where you can't install the update after downloaded it, please download version 1.2.3 [here](https://github.com/rivafarabi/deckboard/releases).

Nice suggestion tho. Thanks!

**Comment by wociscz** [comment]
Whoa that is spectacular :) So sorry for posting something what is already implemented...
I'm looking at releases but "play audio" didn't mentioned. 
Anyway Good Job!

**Comment by rivafarabi** [comment]
Oops... maybe i forgot :P Hope you enjoy it!
