### ISSUE TITLE
[v1.4.0 & v1.5.0] Order issue despite manually changing sort order

### ISSUE THREAD

**Issue by Yurlyn** [rivafarabi/deckboard#161]
The server just won't keep the order I've set it to. I have tried importing boards separately but no matter what I do, it's being stubborn and it keeps mixing up the order. When deleting a board it will also toss the order out the window and just places the boards in any order it wants.

Which is weird is that it seems to be consistent in what order the boards are placed even when importing them one by one until one is added or deleted. Right now it's just a pain to having to rearrange them constantly.

Also, as a more user readability related issue, could the base64 picture encoding be put in a separate file with an id so it can be retrieved through id means so the main board export file can be read by humans better? xD Or at least give the user the choice to do so.

**Comment by inexorous** [comment]
This also happens to me when adding a new board, the order of my boards gets jumbled up.

**Comment by Yurlyn** [comment]
Not sure if you had worked on this but it still happens in 1.5.0.
