### ISSUE TITLE
[Request] Custom Grid Layout

### ISSUE THREAD

**Issue by inexorous** [rivafarabi/deckboard#163]
I would like the option in Pro to be able to define custom numbers of columns / rows as currently the available layouts all only fill the top half of my screen on a OnePlus 6t (and a lot of new smartphones are getting wider displays):

![Screenshot_20190510-130108](https://user-images.githubusercontent.com/17802381/57525962-0caa1200-7324-11e9-9535-4ba1f43e0d83.jpg)

Failing that I'd like something like 7x4 grid layout. 

It looked like this might have been planned for 1.4 but I've got that installed but I don't get any option to customise.

**Comment by pGommes** [comment]
I totally agree, could be something in that style something else that I do not like is also the menu icon and the unnecessary scrolling effect just a fade or nothing up would be better than the scrolling effect.
![Screenshot_8](https://user-images.githubusercontent.com/29603439/57727991-2c657100-7669-11e9-8ef1-bd911a4bd826.png)
![Screenshot_27](https://user-images.githubusercontent.com/29603439/57727992-2c657100-7669-11e9-928b-b2b5c1eca0a6.png)

**Comment by DerFabsee** [comment]
Custom layout would be awesome!

**Comment by rivafarabi** [comment]
will be implemented once 1.6.0 going stable :)

**Comment by DerFabsee** [comment]
Sick! Thank you! <3

**Comment by ErwinMeulman** [comment]
I also looking for a solution to make a custom layout, higher than 6 x 5

**Comment by rfmarves** [comment]
I'm looking for the same feature!  Extremely needed now in this world of screen size diversity.

**Comment by rivafarabi** [comment]
Custom grid added in [v1.9.61](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.61)
