### ISSUE TITLE
Virtual keyboard or key list that includes F13-F24

### ISSUE THREAD

**Issue by digitalfiz** [rivafarabi/deckboard#164]
I would love to be able to use the higher number function keys but I dont have a keyboard with them so I can't use them in Deckboard. Its 12 extra unused keys that people could benefit from.

**Comment by rivafarabi** [comment]
you can use combination of SHIFT + F1 - F12 to create F13 - F24 key (Keyboard Macro only).

**Comment by digitalfiz** [comment]
Doh! Thanks!
