### ISSUE TITLE
Javascript error / 'page down' button / transparent background

### ISSUE THREAD

**Issue by Stannistor** [rivafarabi/deckboard#167]
Hello everyone,

I am a new user for Deckboard Pro. I made two test buttons. One was to run a program and another was a button press test with the button 'page down'. See screenshots for errors.  I was losing the connection also, but that is probably related to the errors. I did see previous topic about Javascript error, but it was closed and solved. 
![run-program-button](https://user-images.githubusercontent.com/50633913/57719427-0ac3b400-7680-11e9-971b-1e9358d8fac7.png)
![page-down-button-press](https://user-images.githubusercontent.com/50633913/57719507-33e44480-7680-11e9-892c-03782ace8190.png)

After some more testing it turns out that i can open programs. I have a feeling the error occured after editing the button (gave it another function). I tested a few keyboard macro's which all work except for example the 'page down' or 'page up' key. 

I also noticed when i go to edit an existing button that it doesn't always show the key i previously entered under keypress. Sometimes it does and sometimes it doesn't. Same when i used advanced macro and open the keypress editor which is empty sometimes. 

**Feature request:** If the dev reads this also, then my first feature request would be the option to select transparent background for buttons (would be nice in combination with vector graphics). Also custom image background for boards. Next to that maybe also a dropdown of icon font pack, but background is more useful (we can still find icons ourself).

#update: I tried a few games with keyboard macro's. I did have a problem where the key/button is only working once and after that it takes some time before it works again. I made for example a button to trigger beacon lights in Farming Simulator 17 which is just a keypress. It works once but then nothing. When pressing the same key on keyboard it is working as expected. I tried to use delays in advanced editor, but didn't made a difference. Any tips are welcome.

**Comment by rivafarabi** [comment]
thanks for the info regarding those non working keys. will be updated in the next patch

**Comment by Stannistor** [comment]
Thanks for the update

**Comment by BrunoSehnem** [comment]
I noticed that this error only happens with computers that do not have java installed
