### ISSUE TITLE
Multi Action Keyboard Macro

### ISSUE THREAD

**Issue by hutchy33** [rivafarabi/deckboard#169]
When I am setting up Multi Action and choosing 1. switch scene on obs then 2.  keyboard macro, the keyboard macro doesn't seem to work, also in the keyboard macro section on the multi action editor the option to choose the program to run on is empty.
![Annotation 2019-05-15 113623](https://user-images.githubusercontent.com/50661141/57769393-ab0fec00-7705-11e9-8845-9643de68d282.png)

**Comment by rivafarabi** [comment]
thanks for the info. Will be updated in next patch

**Comment by hutchy33** [comment]
Thank you :) Would it be possible to also add switch board into the multi action so I can switch board and automatically switch scene please?
