### ISSUE TITLE
[Request] Desktop mobile client

### ISSUE THREAD

**Issue by Tracehunter** [rivafarabi/deckboard#173]
Hey there, first thank you for the great job ! I'm a deckboard PRO owner, however as a Surface user, I'd LOVE to be able to have a native windows App !

Any chance for this in future ? I'd pay (and pretty sure many users as well) for a pro windows version !

**Comment by rivafarabi** [comment]
Actually I have plan for both web app of free version of Deckboard and desktop client in the future. But both Mac OS and Linux ports will be priority for now
