### ISSUE TITLE
No android update

### ISSUE THREAD

**Issue by AlfaJes** [rivafarabi/deckboard#174]
Hello, I'm having problems connecting the server with my androyd device, the version of the server is 1.4.1 and that of my android device is 1.4.0. In contrast there is no update available for android.

Desktop APP
![imagen](https://user-images.githubusercontent.com/13647372/58055570-6dc0b980-7b5e-11e9-82e3-7a1e55c4e744.png)

Android APP
![Screenshot_20190521-002443](https://user-images.githubusercontent.com/13647372/58055783-2a1a7f80-7b5f-11e9-996f-b63c76e4b495.png)

**Comment by rivafarabi** [comment]
Android client app updates monthly. As long as the current version of mobile app compatible with the latest update of desktop app, it won't be a problem as stated in app's google play update log
