### ISSUE TITLE
Uh-Oh

### ISSUE THREAD

**Issue by jadou7** [rivafarabi/deckboard#18]
I launch app on my Samsung j3 2016 and it is noted: "Can't connect to server. Check your PC's IP address and try again ."

**Comment by rivafarabi** [comment]
Hi jadou, is your computer connected to two networks at the same time (one
wireless network and wired lan)? And is your computer has any virtual
machine app (like virtual box or vmware) installed?

**Comment by joshstar** [comment]
I had the same issue, desktop app stating wrong ip/qr code. The ip it was showing was my virtual box network ip instead of my local wifi ip, running `ipconfig /all` I found my real local ip and that worked fine.

**Comment by rivafarabi** [comment]
I ran into the same issue with virtual box IP address myself. I already fixed it, but the update won't come out in couple of days. Sorry for the inconvenience

**Comment by jadou7** [comment]
[FIXED] It was virtual box that caused this .
