### ISSUE TITLE
5.0 RC1 portrait immersive bug

### ISSUE THREAD

**Issue by Revenger** [rivafarabi/deckboard#183]
Don't know if it's my phone but on 5.0 RC1 portrait mode still shows the Android status bar which is ontop of the first row of buttons.

Landscape mode works fine with being immersive.

I wouldn't mind if the buttons are moved down a bit in portrait mode to show the status bar as you can see there's plenty of space to spread the buttons in the default grid.

The buttons should be central on the page to be more uniform.

![Screenshot_2019-06-06-23-06-30-547_com rivafarabi deckboard pro](https://user-images.githubusercontent.com/597280/59045541-d9bb5580-88b2-11e9-9a9c-7f2f93b4a331.png)

**Comment by rivafarabi** [comment]
fixed on the latest version 1.5.1
