### ISSUE TITLE
Deck proportion 6 columns by 4 rows

### ISSUE THREAD

**Issue by guilhermelimait** [rivafarabi/deckboard#184]
Hi,
Sorry If I'm on the wrong place, but I would like to ask for the 6 columns by 4 rows, I've just bought the Pro version and the option shows it with little icons. As nowadays the phones are more large in landscape mode, it would help to fulfill the screen with buttons.

**Comment by rivafarabi** [comment]
Sorry for late response. Yes, It will be included in stable version of 1.5.0 alongside 6x3 and 5x3 layout

**Comment by DerFabsee** [comment]
So this should be available right now, right? Because I can't seem to find those options. :/ 
![image](https://user-images.githubusercontent.com/45405525/59966779-50965680-9521-11e9-9023-150705b22291.png)

**Comment by rss-dev** [comment]
It's actually there so the issue can be closed! :)

**
![image](https://user-images.githubusercontent.com/42423313/59967821-24ce9d00-9530-11e9-8b76-843ff8ab2d77.png)
**

**Comment by rivafarabi** [comment]
Yes. The new layout is available in version 1.5.0 (stable) and 1.5.2 (client)
