### ISSUE TITLE
Uh-oh! Problem.

### ISSUE THREAD

**Issue by Korakasdasd** [rivafarabi/deckboard#19]
I tried with my main PC and failed, the IP from my laptop just work fine, idk what can be the issue...?

**Comment by rivafarabi** [comment]
Is your PC connected to two networks at the same time (one
wireless network and wired lan)? Try checking your wireless network IP with ipconfig in cmd

**Comment by Korakasdasd** [comment]
Only wired conection, I also changed my IP couple times and dind't work.

**Comment by rivafarabi** [comment]
Have you check the firewall setting for the app?

**Comment by Korakasdasd** [comment]
Seems to be that, quiet strange, cuz I've check that before, now seems to
work! Great work with app, thanks for the support.

**Comment by rivafarabi** [comment]
You are welcome 👍
