### ISSUE TITLE
[Request] Audio Control in Streamlabs OBS or Pretzel.rocks

### ISSUE THREAD

**Issue by SirL0fty** [rivafarabi/deckboard#195]
Hi I would love audio control for streamlabs or pretzel.rocks.

Thanks

**Comment by rivafarabi** [comment]
at this point only, Streamlabs OBS only provide an API for muting the audio source, not full control like OBS 
Studio does. If future updates of SLOBS includes the full audio control API, I'll gladly to put those in the apps.
