### ISSUE TITLE
iOS App

### ISSUE THREAD

**Issue by Zelakto** [rivafarabi/deckboard#2]
Hi there! I just discovered this and I'm more than willing to try it out. However I was wondering if an iOS app would be coming in the future (more specifically, iPad Pro). I'd love to load it on there. Thanks!

**Comment by rivafarabi** [comment]
Hi Zelakto! I love and want to release the app for iOS, but because I don't have Apple Developer account, I will keep focused on Android version for the time being. Thanks!

**Comment by JamesAdams92150** [comment]
Have you planned for an IOS version?
