### ISSUE TITLE
Recurring disconnections 

### ISSUE THREAD

**Issue by joshstar** [rivafarabi/deckboard#20]
After 10-30 minutes the mobile app always loses connection to my pc, making me reconnect until it loses connection again after another 10-30 minutes.

I'm not sure how easy this would be to fix but it would be nice if the app could attempt to automatically reconnect a few times after loosing connection as a temporary solution.

App Version: v1.2.3 PRO
Mobile: Google Nexus 6p/Android 7.1.2
Desktop: Windows 10 Pro 1803

**Comment by rivafarabi** [comment]
I will look into this issue. Thanks for reporting.

**Comment by ObiwanKenoob** [comment]
I also had that issue.. 
That's the first thing keeping me from buying the pro version.

I see that it's been moved to done to the version 1.2.7 is there a timeline for releasing that version, as I just got 1.2.6 version rolled out.

**Comment by rZiMiZ** [comment]
Yeah, i keep disconnecting :(
