### ISSUE TITLE
Latest Version

### ISSUE THREAD

**Issue by dcodom** [rivafarabi/deckboard#201]
I just updated the windows version and the android version, and it messed up three buttons, and if I edit any  button, when I tried to fix. It breaks the app totally. I am able to edit the first button, but if you click save or cancel, the dialog box doesnt disappear.

**Comment by dcodom** [comment]
I am using the Deskboard Pro v1.5.2, paid version

**Comment by dcodom** [comment]
Also the above situation occurs even if not connected to the client.

**Comment by rivafarabi** [comment]
Can you send me the exported file of the board for me to review?

**Comment by dcodom** [comment]
Let me know if you need anything else.

**Comment by dcodom** [comment]
Guess I am not able to attach the file by itself, so I zipped it up.

[AllBoards.zip](https://github.com/rivafarabi/deckboard/files/3336907/AllBoards.zip)

**Comment by dcodom** [comment]
Ok... here is an update...

I tried to uninstall and then reinstall -- Same issue

I then removed the deckboard folder from my user folder, and imported what I attached,
and wahlah it all worked.

So it didnt like your deckboard-power-control add-on/extension being installed, or the import fixed something bad that existed previously.

I have saved the folder structure with files that was in my user folder if you want to look at them. Let me know. :-)

**Comment by dcodom** [comment]
I guess when you uninstall it doesnt get rid of the folder in the user directory. So a good option in the uninstaller would be to give an option to remove settings as well. So we can do a clean uninstall and if needed do a clean install. I only knew about the folder because it was part of your installation instructions for the extension.

**Comment by dcodom** [comment]
So the problem is resolved, but is a problem of some sort, so I have not closed the issue as of yet. I can do other testing with the old broken files that existed in the user directory. 

Just let me know what i can do to help you out.

**Comment by rivafarabi** [comment]
thanks for the update and noticing the issue in the extension. 

I will close this issue while fixing this extension issue related bug.
