### ISSUE TITLE
Java Issues

### ISSUE THREAD

**Issue by TechHouse420** [rivafarabi/deckboard#206]
I have tried adding volume up and volume down as well as a button to open steam. The all give java timeout errors.

I have uninstalled and reinstalled the latest Java rebooted same thing
Uninstalled deckboard rebooted reinstalled and same thing

Its inside the same network. My PC is running LAN and my phone is WiFi

Not too sure how to fix this issue. I saw it and had the credit in playstore so got it and now it doesnt work lol. Any help would be greatly appreciated. thank you.

![download](https://user-images.githubusercontent.com/52401504/60419686-ba0a0b00-9b9a-11e9-98b1-512585dcb830.png)

**Comment by rivafarabi** [comment]
Could you send me the exported file of the board for me to analyze? Thanks

**Comment by TechHouse420** [comment]
> Could you send me the exported file of the board for me to analyze? Thanks

Awesome! thank you for the help
