### ISSUE TITLE
Tablet mode showing only on portrait mode

### ISSUE THREAD

**Issue by guilhermelimait** [rivafarabi/deckboard#207]
HI all,
The tablet I'm using (Galaxy Tab 2 7") doesnt accept to change the screen mode to portrait even when I've checked/unchecked it on the options tab. 

If necessary, I can send an image tonight showing the error.

PS.: it works fine on my phone.

**Comment by digitalfiz** [comment]
Is rotation lock enabled on the tablet? Maybe that's causing an issue?

**Comment by guilhermelimait** [comment]
Hi! good point, but no, the rotation lock is disabled. It means, that other apps, works fine, just the deckboard doesn't ...

**Comment by guilhermelimait** [comment]
Hi, something have happened. 
It works fine now. Really haven't done anything, just restarted the tablet...

**Comment by guilhermelimait** [comment]
Please mark as solved.
