### ISSUE TITLE
[Request] Toggle Buttons

### ISSUE THREAD

**Issue by bgsteiner** [rivafarabi/deckboard#21]
I was wondering if there would be the possibility to add toggles to the buttons.

Such as for a mute switch where when pressed once it could be on color or icon and have it change on the next press.

It would also be nice if there could be two commands one for "on" and one for "off".

**Comment by lkd70** [comment]
+1

The ability to stop/pause playback of a particular (or even all) audio files triggered through the soundboard.

**Comment by meffcio** [comment]
Honestly, this is a must-have feature.

**Comment by Ionimera** [comment]
I'd like to see the possibility to change the background color, and possibly the icon color, as an indicator :)

**Comment by tiagolo** [comment]
> I'd like to see the possibility to change the background color, and possibly the icon color, as an indicator :)

I think this is a good alternative.

**Comment by jaketeaford** [comment]
I was about to post this suggestion but did a search first. I (and likely many others) would really like this feature! Being able to see which OBS scenes/sources are active at a glance like a Tri-Caster would be awesome and would add a lot to the app in my opinion. I see that it's in progress and I hope it gets added soon. :)

**Comment by jthunt** [comment]
I was looking for this feature as well.   Even if its just a two action button (two hotkeys or run two different programs).  Similar to the Multi Action option but with two states.

**Comment by jgthornburgh** [comment]
+1

**Comment by digitalfiz** [comment]
Make sure to thumbs up the main post instead of +1 comments they are better at showing interest and way less annoying :P

**Comment by shep2** [comment]
Says in release? Running 1.9.50. Don't see any toggling (I see the icon turn grayish when I first press it but nothing persistent). I think the thing here is the button press "momentary switch" (like just a key strike) or "toggle switch" (maintained push button).  This could be achieved by having an even number of presses icon picture vs odd number of presses (i.e. one could put a microphone with a line through it for muted or clean microphone for unmuted, the user could define the icon picture as green for unmuted and red for muted)? Heck, just define it as a circular array and it will automatically toggle! This way the status would be obvious and user definable. I don't see any "toggle" style information other than momentary gray blip.

Ideally with a toggle style press you could define even press action vs an odd press action (I could see where some keyboard short cuts for something like mute vs unmute being a different call).

This might be a little crazy, but then there is always the variant of toggle where the functionality can be N number of positions in a circular list/array. You would add an icon, action, and text in a list form (similar to how you are doing the multi-action). Then the program just iterates through the circular list and over indexing just wraps it back to the first state over and over again. An example of this action might be like my TV. I press the action once for mute, and it goes to 50% of set volume, press the action again and it goes to 0% of set volume, press the action again and it goes to 100% of set volume. Same with some of my lighting toggles.

Please and thank you!

**Comment by Simego** [comment]
Hi @rivafarabi , was this feature added? tried to find or a way in the code to make it work in an extension but i wasn't able to, is it possible for us to have a "clicked color" just to alter whenever you click the button? as background color, this will help A LOT without adding too much complexity

i mean this as an option for any kind of button, not only app-specific ones like OBS etc, thanks a lot!
