### ISSUE TITLE
Switching boards

### ISSUE THREAD

**Issue by 3d-Printers** [rivafarabi/deckboard#211]
when I use the option to "Switch Board" I get a RED screen with 
RangeError (Length):  Invalid value: Not in range 0 . . 6, inclusive 8

**Comment by DerFabsee** [comment]
Make sure your app on the phone is up to date. I had to manually update after v1.5.0 was released because Google didn't notify me/updated automatically.

**Comment by rivafarabi** [comment]
Make sure both of the apps (desktop and phone) is up-to-date to v1.5.0+
