### ISSUE TITLE
Upcoming version 1.6.0 (All about extensions)

### ISSUE THREAD

**Issue by rivafarabi** [rivafarabi/deckboard#212]
As stated in issue #208, Deckboard will have its own extensions repo. So all users can install the extensions straight from Extensions menu without complicated procedures.

![image](https://user-images.githubusercontent.com/4427494/60771158-c4358780-a10d-11e9-8909-7d959dc2269e.png)

If anyone interested building their own extension, please check out [deckboard-kit](https://github.com/rivafarabi/deckboard-kit) (still in development). Feel free to contribute to improve the CLI.

The release-candidate will be available mid July.

**Comment by shayenek** [comment]
Any chance of getting 8x5, 9x5, 8x4, 9x4 layouts?

**Comment by rivafarabi** [comment]
> Any chance of getting 8x5, 9x5, 8x4, 9x4 layouts?

Sorry for late reply. This will be considered in future release

**Comment by rivafarabi** [comment]
It's up! https://github.com/rivafarabi/deckboard/releases/tag/v1.6.0
