### ISSUE TITLE
Macros don't work properly ingame

### ISSUE THREAD

**Issue by pataya23** [rivafarabi/deckboard#216]
When I'm trying to use deckboard ingame, the keyboard macros are not working correctly.
For example, I create a button with the macro "W" (for walk forward). When the button is pressed, the character ingame is walking nonstop, until I press "W" on the keyboard(!) again, like they don't release the key.
The same with AKM, tried various things like delays or multiple "key up" events. Nothing worked.

I've tested it on 4 pc's (3x Win10 Pro; 1x Win7 Pro), tried with Star Citizen and Left4Dead. It doesn't matter if fullscreen or windowed screen. On desktop (text editor or explorer) it worked like a charm.

The last version where this still works is 1.3.0. With all versions above, the problem exists.

**Comment by pataya23** [comment]
bought the pro version, same issue. Can someone confirm the problem?

**Comment by rivafarabi** [comment]
Sorry for late reply. The bug fix will release in version 1.6.0-rc2 (beta) tomorrow.

**Comment by pataya23** [comment]
Wow, thanks for your work!

**Comment by rivafarabi** [comment]
The version [1.6.0-rc2](https://github.com/rivafarabi/deckboard/releases/tag/v1.6.0-rc2) is live. The version 1.5.3 should be up on Google Play a couple hours from now. Please open another issue if similar bug still exist in this version. Thanks for the feedback :)
