### ISSUE TITLE
Using Keyboard Macro?

### ISSUE THREAD

**Issue by WJRev** [rivafarabi/deckboard#219]
Not sure if this has been covered or not, so here goes...

Using Deckboard PRO for Elite Dangerous system board, and in theory should be perfect but some I am experiencing strange behavior that I hope is easily explained...

For example I have my landing gear button set as "G" so I set the keyboard macro, go basck to Elite and press my button, all works great. But then I press again to retract and nothing happens. If I Alt-Tab out of elite, and then back in it works fine. Any ideas?

Also it seems to work fine if I use keys like HOME/DEL etc

**Comment by rivafarabi** [comment]
several keypress action issues on game input is resolved in [v1.6.0](https://github.com/rivafarabi/deckboard/releases/tag/v1.6.0). You can reopen this issue if the bug is still there.
