### ISSUE TITLE
Cannot use some buttons on NUMPAD

### ISSUE THREAD

**Issue by tipek360** [rivafarabi/deckboard#22]
I wanted to setup macro which contains `*` `(NUMPAD_MULTIPLE)` or `/` `(NUMPAD_DEVIDE)` or `+` `(NUMPAD_PLUS)` or `-` `(NUMPAD_MINUS)`, When I press one of this buttons when I create MACRO in box for shortcut creation I see `O` when I press `/` or `J` when I press `*` or `M` when I press `-` or `K` when I press `+`.

**Comment by rivafarabi** [comment]
Sorry for late reply. I'll put this a bug for now. Thanks for the info.

**Comment by digitalfiz** [comment]
This is still happening in 1.6.2. Here is a video I made to illustrate https://imgur.com/a/f51qVhf

**Comment by rivafarabi** [comment]
Going to release the patch this weekend.

**Comment by rivafarabi** [comment]
numpad fix available in version 1.6.2

**Comment by digitalfiz** [comment]
Can confirm this is fixed
