### ISSUE TITLE
White page after Spotify login

### ISSUE THREAD

**Issue by pataya23** [rivafarabi/deckboard#223]
Don't know if this is an issue because of rc-version but...

After i press the login button for spotify connect, there only a white page is upcoming.
With 1.5.0 it works fine.

![deckboard-spotify](https://user-images.githubusercontent.com/45467019/61595840-77b57600-abfc-11e9-9562-0e280508f79a.png)

**Comment by rivafarabi** [comment]
Thanks for the info. I'll look into it.

**Comment by rivafarabi** [comment]
It's fixed https://github.com/rivafarabi/deckboard/releases/tag/v1.6.0
