### ISSUE TITLE
Deckboard 1.6.0-rc2 websocket config

### ISSUE THREAD

**Issue by DerFabsee** [rivafarabi/deckboard#224]
With Deckboard 1.6.0-rc2, Deckboard doesn't connect via "localhost". You have to change the IP manually to "127.0.0.1" in order to get websocket up and running. 
![image](https://user-images.githubusercontent.com/45405525/61596564-92d8b380-ac05-11e9-81d5-153431413c59.png)

**Comment by rivafarabi** [comment]
Thanks for the feedback I'll patch it for next release

**Comment by rivafarabi** [comment]
fixed in [stable](https://github.com/rivafarabi/deckboard/releases/tag/v1.6.0) version
