### ISSUE TITLE
Stream marker with a click 

### ISSUE THREAD

**Issue by ForthtuN** [rivafarabi/deckboard#225]
You should add the future to do a stream marker with twitch with Deckboard, alot of other tools have it including stream deck. Would be very nice to just be able to push it on the phone :)

**Comment by Yurlyn** [comment]
Ooh seconded! I have a G key of my keyboards whuch triggers my bot to save the time to a file (left over from before markers were a thing) and it also tosses a command in my chat that triggers Chatty (a Twitch chat app on pc) to set a marker. Weirdly enough Streamlabs Chatbot doesn't support it so this was my workaround. Unfortunately, the command shows in the chat and that could spoil things for the viewers so a button in Deckboard would be awesome :D

**Comment by rivafarabi** [comment]
👌

**Comment by rivafarabi** [comment]
It's up y'all! https://github.com/rivafarabi/deckboard/releases/tag/v1.6.0

**Comment by ForthtuN** [comment]
Thanks, amazing! Now i don't need my second computer near me anymore! Really GJ!
