### ISSUE TITLE
Clicking once but firing multiple events

### ISSUE THREAD

**Issue by SamKemp** [rivafarabi/deckboard#226]
I am currently having an issue where I press a button on my app and the event occurs twice, an example of this is using my app to say "!test" in my stream chat. This happens with all buttons

Desktop version 1.5.0. Android version: 1.5.3

![](https://pics.utmg.uk/Streamlabs_OBS_kr3xEY288m.png)

**Comment by rivafarabi** [comment]
Thank you very much for the info. Version 1.5.4 should be up couple hours from now.
