### ISSUE TITLE
Throwing error making stream marker not work

### ISSUE THREAD

**Issue by ForthtuN** [rivafarabi/deckboard#229]
When starting the stream, pressing "Start Stream" it instantly throws me a error message which make the Stream marker button not working in Streamdeck

![Streamdekck](https://user-images.githubusercontent.com/10890970/62100207-1727d800-b291-11e9-86ed-b8a3f6d4e40b.png)

**Comment by rivafarabi** [comment]
Thanks. I'll check this issue out.

**Comment by rivafarabi** [comment]
fixed in v1.6.1
