### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by powderedwater** [rivafarabi/deckboard#23]
Is there any possibility that I will be able to resize buttons or decrease the number of buttons in the future?

I have a particular use case where I am having guests come in and use Deckboard to control OBS. It would be great for people with eye problems and motor skill problems if I could limit everything to X amount of large buttons designed just for their needs/setup.

Let me know, this app is awesome and already so user friendly.

**Comment by rivafarabi** [comment]
Thanks for your feedback. The user setting for button's size is in the work right now alongside other setting configuration.
It is planned to release in two weeks from now on Android as beta release. I'll keep you updated.
