### ISSUE TITLE
[Bug] Tooltip Spotify button padding

### ISSUE THREAD

**Issue by YaFou** [rivafarabi/deckboard#232]
When you hover the Spotify button in the toolbar, the top padding is too big. We can see the bug in the image: ![Tooltip Spotify button padding](https://user-images.githubusercontent.com/33806646/62124427-781fd200-b2ca-11e9-8b6b-6be75b7b4546.png).

*Thank you for your attention.*

**Comment by rivafarabi** [comment]
fixed in v1.6.1
