### ISSUE TITLE
New stream marker won't work

### ISSUE THREAD

**Issue by ForthtuN** [rivafarabi/deckboard#235]
After pressing the marker button on my Pad, it still don't give any marker added to my stream. I need to manually go into my dashboard on twitch and add marker. The app won't just create one.

**Comment by ForthtuN** [comment]
Still not working

**Comment by MarTyNiDruid** [comment]
Same

**Comment by GARBAGEPLAY** [comment]
Still not fixed. Was about to buy the app but have no desire to now. This coupled with the fact that the app looses sync with ctl+shift+letter combos

**Comment by hargossath** [comment]
still not working, are you working on this issue?

**Comment by maxzamarripa** [comment]
I just found this thread. I thought I got an issue with my rig, reading it's a known issue helps. 
Looking forward to a fix

**Comment by Calmynt** [comment]
If it helps, neither the `Add Stream Marker`, nor the `Send Chat` feature and starting the message with `/marker` works. This is a pretty big issue.

**Comment by hargossath** [comment]
> If it helps, neither the `Add Stream Marker`, nor the `Send Chat` feature and starting the message with `/marker` works. I believe this might mean that either marker adding functionality is being blocked in general, or chats starting with `/marker` are being converted - since the message doesn't show up in chat.

i actually tried that workaround too XD

**Comment by maxzamarripa** [comment]
> If it helps, neither the Add Stream Marker, nor the Send Chat feature and starting the message with /marker works. I believe this might mean that either marker adding functionality is being blocked in general, or chats starting with /marker are being converted - since the message doesn't show up in chat.

I tried that too. I have a workaround, that isn't ideal but it suits my case when streaming from a console. And I'm not moving the PC or clicking around.

I did a macros multi-action.
0. Selecting the chat window 
1. Type text '/marker'
2. Delay (500 ms)
3. Enter
4. Delay  (500 ms)
5. Enter

The multiple ENTERS are to handle a popup from the chat. And the delays are for the async operation to work properly. 
I repeat this isn't ideal, but it might be helpful to someone.

**Comment by hargossath** [comment]
nice idea! good for you that you use a different device for streaming :/

**Comment by PatrickePatate** [comment]
same problem here !

**Comment by rivafarabi** [comment]
fixed in v1.9.85
