### ISSUE TITLE
[Request] Adding a way to add buttens for using tools in editing software 

### ISSUE THREAD

**Issue by AngelicDivine** [rivafarabi/deckboard#25]
I have been working with editing for awhile now. I wish to find a way to make my workflow better even though i don't have a second keyboard and setting up labels on my one keyboard is a pain if i can't remove them. 

Like i use DaVinci Resolve and setting up keys on the deck board to work with DR would help so so much. like if i wish to use the cut tool to cut out long wait and boring moments i wish to have it in a spot that helps me. If this makes sense 

I know your working really hard to work out bugs with OBS fixes and so on i just thought this would be a good addition to the deckboard. I think i could somehow get it to work by building a extension but i don't know how to write in code. I am still new to it. :P

**Comment by rivafarabi** [comment]
Sorry for late reply. The current focus for the app development is just maintain and improve the current available macros. So, unfortunately no new macros in the near future.

For the extensions (currently in beta) you need to learn Javascript/NodeJS. 

If you want to make an extension for a program, as long as that said program give you access to its API and the said API can be accessed by NodeJS (with native javascript or bundle it directly from the DLL) you can create extension for it.  Guide to create one [https://github.com/rivafarabi/deckboard/wiki/Extensions](here)
