### ISSUE TITLE
Correct Resolution for Images

### ISSUE THREAD

**Issue by Streethawk9081** [rivafarabi/deckboard#251]
Hi There,
Not really an issue, but more a request. Can you let me know what the best resolution for adding images to the Tiles is please.
As a suggestion, it would be good to also add this into the upload / edit Button page

**Comment by rivafarabi** [comment]
It depends on the device resolution and grid size of the board you use. I would say 450x450 px (high res setting) for grid size (6x5)

But I'm not encourage to use the image that exceed 1MB in size to avoid device memory issue. 

You can always pick low resolution option in Deckboard setting to convert all image you saved to the lowest.

And thanks for the suggestion :)
