### ISSUE TITLE
[Request] Voicemeeter Integration

### ISSUE THREAD

**Issue by derMiepz** [rivafarabi/deckboard#253]
Voicemeeter offers an API to directly call it's functions. This would make things a ton easier because you currently have to set up hotkeys with Voicemeeter's Macro Buttons and Deckboard which can be triggered by accident. 

I know that this is a bigger request but I'm really looking forward for this because I think that if people are using a "virtual" StreamDeck, they're also using a "virtual" audio mixer. :)

**Comment by Gelmo** [comment]
I have another request which is related to my Voicemeeter usage, but it does not require implementing anything specific to Voicemeeter.

I use Voicemeeter's Macro Buttons utility extensively, and I very much enjoy the customization it offers me. I use it for several things which cannot be done by Deckboard. Macro Buttons supports the ability to trigger a macro/script via MIDI. If Deckboard could simulate MIDI button inputs, it would be a fantastic bridge for using Voicemeeter's scripting interface.

**Comment by rivafarabi** [comment]
please check this [extension](https://github.com/rivafarabi/voicemeeter-control)
