### ISSUE TITLE
Every time i start deckboard i got a error

### ISSUE THREAD

**Issue by jerebtw** [rivafarabi/deckboard#258]
https://ibb.co/3r2j25m

**Comment by Vextalex** [comment]
I can confirm this. It happens to me the same way.

**Comment by rivafarabi** [comment]
This is known bugs in Steam Launcher extensions. Please delete the extension by deleting the steam-launcher.asar file located in C:/User/{USERNAME}/deckboard/extensions

**Comment by Vextalex** [comment]
Alright. Thanks, this seems to fix the problem.

**Comment by jerebtw** [comment]
Thanks, the problem is fixed.
