### ISSUE TITLE
Keyboard Macro Buttons Don't Work

### ISSUE THREAD

**Issue by silentsonata** [rivafarabi/deckboard#27]
So when creating a macro button, I set the shortcut combination and the desired application for it to run on. The button is there on my phone but when I press it nothing happens. I have tried this on multiple applications and multiple shortcuts. I am on windows 10 with deck board 1.2.5 on the desktop.

**Comment by silentsonata** [comment]
Any of them. I have tried ctl-alt-7, ctrl-shift-3, alt-P, and alot more
combos it just never triggers.

**Comment by walktheweb** [comment]
I reverted to server version 1.23. In this version you can type your macro combination. e.g function keys F13-F24.
1.25 server version is not detecting keys like '-'. I looks like there is an issue with the numpad keys.
Hope it will be fixed soon.
Keep up the good work! I like your program.

**Comment by rivafarabi** [comment]
Fixed on v1.2.6
