### ISSUE TITLE
[Request] Better ways to change boards - Current button issues, swipe, add button to go-to board

### ISSUE THREAD

**Issue by bfmello** [rivafarabi/deckboard#28]
Just began testing your app, it is amazing, but I've came across what I think is a minor issue - the button on the app to click and change boards either has a click area too small or is somewhat not as responsive as it could, because often I need to click it a few times until it goes to the Board selection screen.

It would be great if either the button or the click area to open the board selection was bigger or better responsive, or what I think it would be even better, allow users to create deck buttons to go diretctly to boards (just like the regular streamdecks), or implement a swipe motion left or right to cycle between the boards. It would add speed and save clicks to switch boards during a live stream.

**Comment by rivafarabi** [comment]
Thank for the feedback. Currently the app is getting rework to access some feature and fix the said bugs. Please see #30
