### ISSUE TITLE
[v1.7.0-rc2] Board order changed

### ISSUE THREAD

**Issue by Yurlyn** [rivafarabi/deckboard#281]
Server: v1.7.0-rc2
Client: 1.6.3

I've spent nearly all night upgrading my boards by deleting them and creating boards with random names to get to the amount of boards I originally had, renamed them to their proper name all in the hopes the order would stay as is. It seemed to work but then I renamed a board after adding a bunch of buttons throughout the different boards and my board order is messed up again.

Now I can just drag the boards to be in order again but restarting the server messes it all up again. To make it worse, the mobile app does not respect the order set in the server, even when the order is manually set.

When the order is messed up the mobile app will randomly switch boards at random intervals.

**Comment by rivafarabi** [comment]
May I know which version are you using on your PC?

**Comment by Yurlyn** [comment]
That's at the top of the message above, lol. It's 1.7.0-rc2 now but it already did this in 1.6.3, unfortunately. I've had another ticket open for this [here](https://github.com/rivafarabi/deckboard/issues/241) but the client is now 1.6.0 instead of 1.5.4.

Also, server 1.6.3 has an issue with connecting to OBS. While it says it's connected it actually isn't able to control OBS unless OBS is run first and then Deckboard. Which brings me to this issue here since I'll have to redo the order in the server though the client (1.6.0) doesn't respect them :/

**Comment by rivafarabi** [comment]
Oops sorry. I forgot to read the title. The fix is on the way, but
unfortunately the next patch will probably up for the next 2-3 days. (It's
already monday here :/)

**Comment by Yurlyn** [comment]
Lol, it's fine :P Oh, thanks for fixing it. Those 2-3 days won't matter. I can deal with it for now. Will the fix for the connection with OBS also be fixed? I think the user should be able to manually disconnect from OBS (and the other programs) just in case. It's also annoying when trying to type as the error popup comes up constantly if it is unable to connect. Had that just now but the password to OBS' websocket was wrong.

**Comment by rivafarabi** [comment]
can I have a screenshot of the error itself? Is the error come from
Deckboard or OBS websocket plugin?

**Comment by Yurlyn** [comment]
It's from Deckboard. It's the disconnect error on the bottom right of Deckboard.
![image](https://user-images.githubusercontent.com/42919979/66280005-e2e61e80-e8b4-11e9-86db-37942973bd95.png)

**Comment by rivafarabi** [comment]
closing this due to version 3 has different grid system
