### ISSUE TITLE
Setup was not completed successfully 

### ISSUE THREAD

**Issue by DjScribblez** [rivafarabi/deckboard#282]
![unknown (1)](https://user-images.githubusercontent.com/56238769/66278035-89113480-e873-11e9-87cd-fbb6fccec855.png)

Idk whats going on, but I paid for the app and I cant even use it

**Comment by rivafarabi** [comment]
Have you tried version 1.7.0-rc2
<https://github.com/rivafarabi/deckboard/releases/tag/v1.7.0-rc2>?

**Comment by DjScribblez** [comment]
I have and that as well failed but I did find a solution. I had to delete everything pertaining to the app. That includes going into the registry and finding anything that had to do with the app. After doing all that I was able to install it. Using 1.7.0 rn and its great. Cant wait to see what other extensions and features you will add!

Just a small suggestion I have for deckboard actions itself, within the "Switching Board" setting you should add an option that just goes to the previous board so people with alot of them dont have to scroll through and find the one behind. It is a lazy thing to not just search but it is just that little time saver

**Comment by f2bacon** [comment]
also having this issue. tried every release available on github. scrubbed the registry and program files folders
