### ISSUE TITLE
I can no longer contact obs in 1.7.0-rc3 update

### ISSUE THREAD

**Issue by Vextalex** [rivafarabi/deckboard#283]
I can no longer contact obs in 1.7.0-rc3 update. There will be no error message. I just can't get in touch.

**Comment by Vextalex** [comment]
I tried it on two computers and the same thing.

**Comment by rivafarabi** [comment]
Thanks for the info. I will look into it.

**Comment by firefloc** [comment]
same issue for me actualy i've found a no solution :')
block the app with asus gamefirst V
so @rivafarabi have you let posibility to no auto update?

**Comment by rivafarabi** [comment]
The bug has been fixed in version 1.7.0-rc4. Sorry for the inconvenience.

**Comment by firefloc** [comment]
thx ^^

Le sam. 12 oct. 2019 à 17:40, Riva Farabi <notifications@github.com> a
écrit :
