### ISSUE TITLE
[REQUEST] voicemeter extention

### ISSUE THREAD

**Issue by firefloc** [rivafarabi/deckboard#288]
can you make an deckboard extention to control voicemetter potato ?
an api can be found here https://www.vb-audio.com/Services/developers.htm
a lot of streamer use this virtual mix table I think it can be very usefull

**Comment by Yurlyn** [comment]
That'd be interesting! For now you could potentially use this maybe: https://github.com/gbevin/SendMIDI

I'm gonna see if I can set this up for myself as well. I'll keep you updated if I can get this to work.

**Comment by derMiepz** [comment]
I'd say this is a duplicate of https://github.com/rivafarabi/deckboard/issues/253

**Comment by rivafarabi** [comment]
please check this [extension](https://github.com/rivafarabi/voicemeeter-control)
