### ISSUE TITLE
[request] Voicemod extention 

### ISSUE THREAD

**Issue by firefloc** [rivafarabi/deckboard#289]
can you make a portage of streamdeck function for using voicemod (voice changing software)
the soft can be used with a streamdeck but not with deckboard I think it can be simple to interact with the protocol of voicemod 
the dev give an SDK : https://www.voicemod.net/sdk-for-developers/

**Comment by digitalfiz** [comment]
I would love this also. It's very difficult juggling short cut commands already then if you wanna add in a bunch for different voices its gets kinda crazy

**Comment by THEscienty** [comment]
Yes please, the DeckBoard does not detect Voicemod when it is in the background. And when it is in the taskbar and I press a key on the DeckBoard, Voicemod goes right in the middle of my screen whereas with the shortcuts on my keyboard it doesn't do that.

**Comment by Romeo-Johan74** [comment]
Yes add a Voicemod plugin please !

**Comment by rivafarabi** [comment]
Still in the process requesting SDK from Voicemod themself. I hope it goes
through.

**Comment by MickyMcfly** [comment]
Hello!
Still relevant? It's planned?

**Comment by Sourenics** [comment]
I'm also interested in this, how you guys use keybinds? I can't seem to make it work. I make a macro attached to "ç" key on the keyboard, that key makes a censor beep that mutes all voices and sounds and beeps, but can't add it to deckboard (I'm using deckboard pro)

**Comment by rivafarabi** [comment]
Voicemod integration is available in beta version [2.1.5-rc0](https://github.com/rivafarabi/deckboard/releases/tag/v2.1.5-rc0)

**Comment by filipe-oliveira-design** [comment]
> A integração do Voicemod está disponível na versão beta [2.1.5-rc0](https://github.com/rivafarabi/deckboard/releases/tag/v2.1.5-rc0)

Hello! My Deckboard won't connect to the voice mod. I'm using the Voicemod Pro version. It just has a note written: “Voicemod is not connected”. What do I have to do?
