### ISSUE TITLE
[Request] Option to change the network where the client listens for connections

### ISSUE THREAD

**Issue by bfmello** [rivafarabi/deckboard#29]
I've come across an issue when trying to connect the app to the client, that the client auto-selects any network your computer is connected and does not let you change it. There should be a config option on the client to allow the user to select which network the client should be listening for app connections.

My issue was that even though I only have one home network connected to my PC, I had VirtualBox installed on my machine due to work, so I had other "virtual host-only" networks running on my PC, and the client picked up automatically one of them (which I recognized for not having the home network IP mask), and I couldn't find any options on the client to select my home network for listening in; had to go into VirtualBox and delete the virtual networks so the Deckboard client would correctly select my home network to listen in, as it was the only one left available on the PC.

**Comment by rivafarabi** [comment]
Thanks for letting me know. 

Have you tried to refresh the IP address by clicking the refresh icon beside the displayed IP address? 

The app should get you your computer local IP address 192.168.[0-255].[0-255]. (Available in ver 1.2.5)

**Comment by rivafarabi** [comment]
Version 1.2.6 released. Feature to display all connected local network IP address added.
