### ISSUE TITLE
[Request] Separate Left Right key input

### ISSUE THREAD

**Issue by NotonAlcyone** [rivafarabi/deckboard#298]
separate follow key's input by position, it will be nice
![image](https://user-images.githubusercontent.com/15938440/67827660-f7b07d80-fb13-11e9-86ad-2186e49f0883.png)

## key list
* Shift -> LSHIFT, RSHIFT
* Ctrl -> LCTRL, RCTRL
* Win(command) -> LWIN, RWIN
* Alt -> LALT, RALT

**Comment by machineabuse** [comment]
This is a necessary feature to make Deckboard useable with flightsims like DCS and IL2 that broadly make use of left and right modifier differentiation.

**Comment by machineabuse** [comment]
Sorry for the bump, but as of late I've been building decks for DCS World and the absence of this feature has put up a roadblock in my ability to make any more progress.

Is this feature even in the realm of possibility? Else I should probably be searching for an alternative to complete my button board projects.

**Comment by poisonbl** [comment]
Looks like this is also covered in #101

**Comment by emerysteele** [comment]
Would love this feature. Created a python script with a bunch of keyboard shortcuts for input, and it uses left/right alt for separate commands.

**Comment by rivafarabi** [comment]
Feature added in [v1.9.41-rc2](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.41-rc2) (Release Candidate/Beta)
