### ISSUE TITLE
[UPDATE] Regarding upcoming ver. 1.2.6

### ISSUE THREAD

**Issue by rivafarabi** [rivafarabi/deckboard#30]
Just as the title said, the app will be delayed a bit for this month because the Android app is getting a rework from scratch to access some key features that impossible to do with current tools. Sorry for the inconvenience.

**Upcoming New Features**

- [x]  GIF support. 
- [x]  Buttons Haptic feedback
- [x]  'Switch board' button
- [x]  Orientation toggle
- [x]  Performance issue fix

**Comment by AngelicDivine** [comment]
I cant wait to see what the new app is going to look like.

Thanks so much @rivafarabi for making such a great app.

**Comment by rivafarabi** [comment]
1.2.6 released.
