### ISSUE TITLE
 problem with the keyboard macros

### ISSUE THREAD

**Issue by zefutoff** [rivafarabi/deckboard#300]
Hello to begin I apologize for my English which will not be correct to one hundred percent (I'm french) here I have to download deckboard and to perform an action on obs I must use the macros for example I want to perform the following combination : CTRL + 1 when I run it through the application all works when correctly but when I want to find my keyboard to write something and well it does not work I have to click on the ctrl key to get the hand on my keyboard! here I hope that you will be able to help me Thank you in advance. Zefut

**Comment by Yurlyn** [comment]
Could you make a screenshot of the Deckboard button's settings? Example: 
![image](https://user-images.githubusercontent.com/42919979/68258175-2491f280-0036-11ea-99ae-864b266a7cca.png)

**Comment by zefutoff** [comment]
thank you for your answer i remove the software and i reinstall them and it
worked 😊😂

**Comment by Yurlyn** [comment]
Good to hear it's fixed :D

**Comment by zefutoff** [comment]
Re it's still me not to panic I have no bug I had just suggestion to make
you even if I doubt that what I ask will surely take you months and months
of work but I still try this would be super-cool that deck board is
connected to discord imagine the possibilities that would be offered to us
would be incredible especially for a streamer that constantly uses Discord!
Thank you for reading my email! Zefut
