### ISSUE TITLE
OBS Transition

### ISSUE THREAD

**Issue by riccefarias** [rivafarabi/deckboard#304]
An option to change OBS Transition on buttons and macros please.

**Comment by rivafarabi** [comment]
Love the suggestion 👌

**Comment by rivafarabi** [comment]
Will be added in the next RC release this weekend :)

**Comment by riccefarias** [comment]
thanks.... waiting for that...

i will buy PRO to help us.

**Comment by rivafarabi** [comment]
Sorry for the wait. The feature has been added in version 1.8.1. Enjoy!
