### ISSUE TITLE
1.8.0 seems to be broke

### ISSUE THREAD

**Issue by digitalfiz** [rivafarabi/deckboard#305]
Just installed it all from scratch and the default board shows no buttons no matter the layout I choose and when I try to add more boards it acts like it did but no new boards show.

I was also able to delete the default board but now I can not add one back.

**Comment by rivafarabi** [comment]
Thanks for the info. Fix for the issue has been fixed in version 1.8.1.
Sorry for the inconvenience.

**Comment by digitalfiz** [comment]
Can confirm its fixed
