### ISSUE TITLE
[Request] Button to Launch Twitch ads

### ISSUE THREAD

**Issue by AkilisUi** [rivafarabi/deckboard#319]
Hey there,
First I wanted to say you're doing an AMAZING job and since I've got the pro app, it is like MAGIC !

Since I'm using SLOBS to stream, combining with Deckboard, and since SLOBS kinda shut down the ability of launching Twitch ads on stream, do you feel like there is a way to put an action button to launch Twitch ads during the stream ? I guess that would go with the Twitch API itself since you can now launch the ads from the new Twitch dashboard for streamers.

Thank you very much, don't hesitate to ask me for more details if needed !

P.-S. : Sorry for the french titles on the picture, it is said "Launch a 60 seconds ad" !
![Annotation 2019-12-05 103853](https://user-images.githubusercontent.com/58550879/70223128-73bd6700-174b-11ea-8095-33b57e06e613.png)

**Comment by rivafarabi** [comment]
Noted for next release candidate / beta

**Comment by rivafarabi** [comment]
added on 1.9.0-rc1
