### ISSUE TITLE
A JavaScript error occurred in the main process.

### ISSUE THREAD

**Issue by UJGA** [rivafarabi/deckboard#32]
The newest update causes an error when trying to connect.
![fesdxs](https://user-images.githubusercontent.com/21285278/46923919-ed404600-cfdb-11e8-9159-523d536be06b.png)

**Comment by AngelicDivine** [comment]
Was this for update 1.2.5? @UJGA

**Comment by UJGA** [comment]
I think. Whatever the newest automatic update is.

**Comment by AngelicDivine** [comment]
I would recommend to uninstall and reset your pc and reinstall it. Then if that does not work then i am not sure but i hope it helps if it works

**Comment by UJGA** [comment]
Darn I tried that earlier. Thanks for your help though

**Comment by AngelicDivine** [comment]
I just thought of something why not see if you have a java update and then after that uninstall the program and then restart your pc then reinstall it that should fix it also the new update is out so this might have been fixed in the 1.2.6 update

**Comment by Revenger** [comment]
Got a error when updating just now to the latest version 1.2.63.
Updated ok but the error popped up.

![update error](https://user-images.githubusercontent.com/597280/49335383-7876a900-f627-11e8-9584-1184a7ac63bd.JPG)

**Comment by rivafarabi** [comment]
> Got a error when updating just now to the latest version 1.2.63 from 1.2.62.
> Updated ok but the error popped up.
> 
> ![update error](https://user-images.githubusercontent.com/597280/49335383-7876a900-f627-11e8-9584-1184a7ac63bd.JPG)

Thanks for the info. Version 1.2.631 include the bug fix.

**Comment by rivafarabi** [comment]
solved in latest version

**Comment by Sujith-Fraidy** [comment]
This is again happening for me every one recommend to reinstall the video driver but it seems it does not work for me.

**Comment by KaygusuzBK** [comment]
This is again happening for me every one recommend to reinstall the video driver but it seems it does not work for me.
