### ISSUE TITLE
[1.9.0-rc1] Background image doesn't work

### ISSUE THREAD

**Issue by derMiepz** [rivafarabi/deckboard#322]
The new "image as background" feature doesn't work. When I select it, it only shows the image in the desktop program, not on the phone. I guess there will be an update for the app too?

**Comment by rivafarabi** [comment]
The update for the app (1.9.0) still in review by Google. It will be live in couple of hours

**Comment by derMiepz** [comment]
That's what I thought. Thanks for the quick reply! :)
