### ISSUE TITLE
Weird Multi Action behaviour

### ISSUE THREAD

**Issue by TheSwerik** [rivafarabi/deckboard#325]
Version 1.8.1
I tried to use the Same Keyboard shortcut (for muting my mic in Discord) once as a single Makro and once as part of Multi-Action. It only works standalone. The Multi-Action one doesnt function. 
![Single Action (works)](https://user-images.githubusercontent.com/47034061/71407780-4d993180-263c-11ea-9867-19fe3839be37.png)
![Multi Action 1](https://user-images.githubusercontent.com/47034061/71407778-4d009b00-263c-11ea-8a8d-6bf67e7900b2.png)
![Multi Action 2](https://user-images.githubusercontent.com/47034061/71407779-4d993180-263c-11ea-8d2a-6f63fd06c7fb.png)

**Comment by rivafarabi** [comment]
It is expected behavior if your macro for muting microphone is by hold press the key (in this case hold pressing the F8 key). 

Multi Actions is not capable handling hold press like other actions.

**Comment by TheSwerik** [comment]
Its not hold press, its just a press. Or at least i thought it was
