### ISSUE TITLE
FontAwesome support

### ISSUE THREAD

**Issue by ToeiRei** [rivafarabi/deckboard#329]
It would be great if we could FA icons for the buttons as it's the fastest way to get something working

**Comment by Yurlyn** [comment]
Can you not just manually download the ones you want and then add them to your buttons?

**Comment by rivafarabi** [comment]
The default icons for all buttons are Font Awesome icons. 
Currently experimenting to add button customization to select any icon from FA library.

**Comment by Yurlyn** [comment]
Ah I see. I'm just grabbing my icons from Roccat Power Grid and desaturize them lol

**Comment by ToeiRei** [comment]
> Ah I see. I'm just grabbing my icons from Roccat Power Grid and desaturize them lol
That is pretty much work.

FA itself is already used, so using that for icons is the next logical step.
