### ISSUE TITLE
Spotify not Working

### ISSUE THREAD

**Issue by SuperFat-Fat** [rivafarabi/deckboard#331]
Hello !
I have Spotify Premium and Deckboard 1.8.1 installed on my pc. (I use the PRO version by the way).
But when I want to log in to my Spotify account, I get an "Illegal Scope" and I can't do anything more.

**Comment by Gui-Romano** [comment]
Hello!!

l have the same issue here.

"Illegal Scope"

**Comment by walle81** [comment]
me too

**Comment by PadreAndrew** [comment]
Ditto

**Comment by rivafarabi** [comment]
The issue has been fixed. Thanks for the info :)
