### ISSUE TITLE
Deckboard 1.9.0 fails to launch Win10

### ISSUE THREAD

**Issue by RavenStreamer** [rivafarabi/deckboard#334]
I've just installed Deckboard on my Win10 computer and Deckboard Pro on my android phone. Program launches in Win10 after a reboot but if I close and subsequently try to relaunch the program it fails no execute. (I get the hourglass beside my mouse for a few seconds then nothing.)

**Comment by rivafarabi** [comment]
Closing this due to version 3.0.0+ built with upgraded framework.
