### ISSUE TITLE
Export/Import 

### ISSUE THREAD

**Issue by PadreAndrew** [rivafarabi/deckboard#335]
Created an 8X6 layout, all but four buttons used.  Ran export and tried to import onto my laptop only one button came across and the button is not part of the board I exported.
Exported board https://prnt.sc/qkvo8j
Imported board https://prnt.sc/qkvorx

**Comment by rivafarabi** [comment]
The fix for the issue is available in v1.9.1. You can open a new issue if the bug still occurring.
