### ISSUE TITLE
Delay Issue / Javascript error message

### ISSUE THREAD

**Issue by JonatanRaven** [rivafarabi/deckboard#336]
Hi there,

First of all I would like to thank you for a great app. However, I'm getting the following error message when I'm trying to excecute an advanced keyboard macro containing a delay.

![Annotation 2020-01-10 000844](https://user-images.githubusercontent.com/32624849/72115023-6cd2d700-333d-11ea-897d-7d94b35d9a0f.png)

If I remove the delay, the issue does not occur. The isue also disconnects my app from the server. Keyboard macro as perimage below:

![Annotation 2020-01-10 000845](https://user-images.githubusercontent.com/32624849/72115119-d9e66c80-333d-11ea-9067-f25300c11e20.png)

Thank you.

**Comment by rivafarabi** [comment]
Thanks for the info. I'll investigate the issue.

**Comment by rivafarabi** [comment]
The fix for the issue is available in v1.9.1. You can open a new issue if the bug still occurring.
