### ISSUE TITLE
 spotify playlist error

### ISSUE THREAD

**Issue by walle81** [rivafarabi/deckboard#337]
spotify is not finding any playlist

**Comment by rivafarabi** [comment]
Have you logged in to Spotify (Premium) service in Deckboard app?

**Comment by walle81** [comment]
yes, but when you put it to search it doesn't find and some it finds but doesn't accept the button creation
![Anotação 2020-01-11 134330](https://user-images.githubusercontent.com/59639030/72207484-714fda80-3478-11ea-8135-5b05a15b1bd8.png)

**Comment by walle81** [comment]
this is an example of when you find
![Anotação 2020-01-11 134619](https://user-images.githubusercontent.com/59639030/72207519-c855af80-3478-11ea-9c57-42830a675327.png)

**Comment by rivafarabi** [comment]
Thanks for the info. Yes, apparently only public playlists can show up in
the selection. I will look into it.

**Comment by Zurielvsn** [comment]
The playlist must be downloaded to appear?

**Comment by Zurielvsn** [comment]
Does the playlist have to be downloaded to appear?

**Comment by rivafarabi** [comment]
The bug fix for this issue has been released in version 1.9.2
