### ISSUE TITLE
[Error][SLOBS] A JavaScript error occurred in the main process 

### ISSUE THREAD

**Issue by FlyingOwlet** [rivafarabi/deckboard#34]
**Hi there.** I've gotten these errors when I try to connect to SLOBS.
When i click on the SLOBS button, a few seconds goes by until I get the first error(the biggest screenshot).
And the second error appears either a few seconds after the first one, or if I close SLOBS.

**Things I have tried**
I tried updating to the latest Java version.
Tried reinstalling both SLOBS and Deckboard

Thanks for reading, hope this helps.

Edit: Sorry if I should've posted on the first Java thread, not sure if these two issues are 100% related.

Images for reference

![deckboard_2018-10-21_14-11-24](https://user-images.githubusercontent.com/44338922/47266772-63dcc680-d53b-11e8-87fa-2d0c79ee7056.png)
![deckboard_2018-10-21_14-11-40](https://user-images.githubusercontent.com/44338922/47266773-63dcc680-d53b-11e8-8c41-1deeffffedd5.png)

**Comment by rivafarabi** [comment]
Thanks for the info. May I know the version you use when encountered these errors?

**Comment by FlyingOwlet** [comment]
Ah of course, currently running version 1.2.6.

And just for the sake of information, for java and SLOBS I'm currently running:
Java 8 Update 191
SLOBS 0.11.1

**Comment by rivafarabi** [comment]
Have you encountered these errors in previous version?

**Comment by FlyingOwlet** [comment]
Yeah, I've gotten these errors ever since you added support for SLOBS.

Little more information:
I've allowed access through the firewall for SLOBS, Deckboard and Java.
Tried disabling the firewall itself too.

**Comment by duartemelo** [comment]
I got this too.

**Comment by trogdorjr** [comment]
> 
> 
> I got this too when I click refresh to connect to my local network, allowed it on firewall, as java and SLOBS.
> ![screenshot_1](https://user-images.githubusercontent.com/43653646/48508982-dd6c8980-e847-11e8-8ffe-58cb62e1e4b2.png)

I'm getting this same error with the same steps to reproduce "click refresh to connect to my local network"

**Comment by henriqsena** [comment]
I'm getting this same error with the same steps to reproduce "click refresh to connect to my local network 
![image](https://user-images.githubusercontent.com/45789934/49804169-0bef5e80-fd39-11e8-83fe-03d343645f46.png)

**Comment by trogdorjr** [comment]
I was able to connect successfully by putting in the local IP address of my computer and tapping connect on the app on my tablet
