### ISSUE TITLE
Obs transitions bug

### ISSUE THREAD

**Issue by ther3y3s** [rivafarabi/deckboard#342]
When i press on a transition nothing happens

**Comment by rivafarabi** [comment]
Set Transition action only change the transition effect setting for the next scene transition

**Comment by ther3y3s** [comment]
Where i can set this? Because i'm looking in obs settings but i didn't find nothing

**Comment by rivafarabi** [comment]
By default, you can locate scene transitions panel right between Audio Mixer and Controls panel
![transition-1](https://user-images.githubusercontent.com/4427494/72432135-e0a33280-37c8-11ea-8c13-c3c10531cabf.png)

**Comment by ther3y3s** [comment]
Ah yeah i know, but when i press on transition tab from deckboard, on obs pre-selected transition doesn't change. 
For example. on deckboard i set fade transition and on obs is selected cut transition. If i press on deckboard fade transition, on obs remains selected cut transition

**Comment by rivafarabi** [comment]
Thanks for the info. The issue has been solved in version 1.9.2
