### ISSUE TITLE
Launch Error

### ISSUE THREAD

**Issue by Audric1320** [rivafarabi/deckboard#356]
every time I launch the app and every time I re-install I get this error at launch.

![explorer_jxSULbfH6d](https://user-images.githubusercontent.com/29382102/73118758-c07a2d00-3f99-11ea-9281-ab774b3a2f65.png)

**Comment by rivafarabi** [comment]
Is there any software in your PC that run on port 8500? Deckboard only use this port to run its server.

**Comment by Audric1320** [comment]
i resolved the problem by deleting all deckboard files and reinstalling the error was related to the steam launch extension.
