### ISSUE TITLE
Feature request; DELAY

### ISSUE THREAD

**Issue by f2bacon** [rivafarabi/deckboard#357]
I use deckboard for a lot of functionality and automation, and I think it would be MASSIVE to add delay/timers as an option. I currently have a "stream startup" button that toggles the stream, mutes my mic, and changes to my intro scene. when it's time to start i hit a mute toggle button that i made, and change scenes. i think it would be insane to be able to add something like a 5 minute timer so that after 5 minutes it automatically toggles my mic back on, and changes into another scene.

**Comment by rivafarabi** [comment]
have you tried using Multiaction? It has delay you can set in the action sequence.

**Comment by f2bacon** [comment]
> have you tried using Multiaction? It has delay you can set in the action sequence.

i am an absolute fool. i have no idea how i didnt see that. that's exactly what i was using and i didn't see it. sorry for bothering!!!!!!!
