### ISSUE TITLE
[Request] Phone Tilting

### ISSUE THREAD

**Issue by ObiwanKenoob** [rivafarabi/deckboard#36]
I use the app with my phone tilted. The issue I have is, that my charger is on the left side of my desk, and the app doesn't spin around if I change the bottom side of the screen. When I need to keep my phone plugged in, it get's annoying as there are more wires running in the middle of my desk.

It would be awesome if the app could change orientation like many others do.

Thanks!

**Comment by rivafarabi** [comment]
Noted. But for the time being the orientation can be toggled by clicking the phone icon on drawer.

**Comment by ObiwanKenoob** [comment]
So... I saw that you added this do dont on the projects..

I realize there is the button to change orientation.

So just to clarify what i meant, and to check if that's what have been updated to the mobile app or not.

My issue is that when i toggle to landscape mode, it only shows rotates to one side of the phone/tablet..
I've recently acquired a tablet, and i'd prefer to use it on a more angled position.. The way it works now is that I have to have my tablet on a upright position, which will block my monitor when it's on arms reach.. beacuse of that I need to leave the tablet on a more awkward position so that the screen keeps the right orientation..

**Comment by nbs3000** [comment]
Same issue for me, my tablet's USB cable is routed on my desk such that I'd like the tablet to be landscape with the cable going left (bottom of tablet is on left) - but Deckboard then goes upside down! Could we at least toggle through four orientations with the phone icon instead of two?
