### ISSUE TITLE
[REQUEST] Create Clip (Twitch)

### ISSUE THREAD

**Issue by Streethawk9081** [rivafarabi/deckboard#361]
Can you please add function to Create a Clip in Twitch.
Similar to the function available on Elgato Stream Deck

Thanks

**Comment by ForthtuN** [comment]
Its already there however its not been working since it was implented and does not seems to get fixed either. I changed to another software personally

**Comment by rivafarabi** [comment]
Yes it is already in the app. But for some people who experience the bug
where it always fails to add a marker, logout and re-login from Twitch,
then try add the marker again.

**Comment by Streethawk9081** [comment]
Thanks @rivafarabi 
Id love to know where in the app this is? From the responses, you mention "Add Marker" but this is not what I am trying to achieve. I want to create a clip.
This can be done on an Elgato StreamDeck, so figured the API / Connector must be available?

@ForthtuN 
What other software have you been using?
I dont want to move away from Deckboard, but maybe having both if you know of something that can create a clip?

**Comment by rivafarabi** [comment]
Added v1.9.86
