### ISSUE TITLE
Discord support

### ISSUE THREAD

**Issue by HeynKins** [rivafarabi/deckboard#365]
Hello Is it possible to add discord support? for mp3 sounds can be heard in a conversation?
https://discordapp.com/developers/applications/ 

Thanks :)

**Comment by AkilisUi** [comment]
Hi there !
Although it's a nice suggestion, I recommended you use an app like Voicemod or Voicemeeter on PC to get the sounds you launch from Deackboard to also be heard in Discord.
E.G. : Configure Voicemod as the primary source in wondows audio settings, select your mic as an entry in voicemod, then in discord, select voicemod as the default input.

I attached images as en example, sorry for the french titles, i cricled what you need to do ! :D

**Comment by terenc3** [comment]
Totally agree with @AkilisUi. Use a dedicated tool for this
