### ISSUE TITLE
Add Streamlabs Obs Integration improvements

### ISSUE THREAD

**Issue by Lakhwinder123** [rivafarabi/deckboard#369]
Please Add Some More Improvements Like Mute And Unmute All Audio Controls And Also Add Some Youtube integration like show ads.

**Comment by chrisbadley** [comment]
@Lakhwinder123 Do you mean like Action: Audio Control > Audio Device: *Your audio Device* > Toggle Mute.

**Comment by Lakhwinder123** [comment]
yup
