### ISSUE TITLE
[Request] A way to move buttons between boards

### ISSUE THREAD

**Issue by ObiwanKenoob** [rivafarabi/deckboard#37]
This would make it much easier to set up, instead of deleting the button from a board and then reprogramming it.

It would be nice to move it to a new board, as we move files into a folder with windows explorer.
Or at least something like Adding existing button as OBS has the possibility to add a scene or source that already exists to a new scene.

Would be very helpful :)

**Comment by ShadowCreator250** [comment]
In v1.5.0 you can right-click -> "cut" or "copy" on a button. Then go to the other board and right-click -> "paste" on a free field.

**Comment by rivafarabi** [comment]
> In v1.5.0 you can right-click -> "cut" or "copy" on a button. Then go to the other board and right-click -> "paste" on a free field.

Yep, the feature has been available around version 1.3.0. So I'm going to close this one.
