### ISSUE TITLE
Voicemod support for deckboard

### ISSUE THREAD

**Issue by YoiBoiGal8xy** [rivafarabi/deckboard#373]
Hi is there any way i can control voicemod through this

**Comment by AkilisUi** [comment]
Hi there !
I also use Voicemod and the simplest way to put things together (imo) was to simply use advanced shortcuts and put the shortcuts I used in Voicemod directly into Deckboard advanced shortcuts tiles, as followed :
![Voicemod voices](https://user-images.githubusercontent.com/58550879/76900454-ad008980-6899-11ea-8072-6e0a98329369.PNG)
![Deckboard Voices tiles](https://user-images.githubusercontent.com/58550879/76900469-b4c02e00-6899-11ea-936d-bfce1c7aeb22.PNG)
![Voicemod shortcuts](https://user-images.githubusercontent.com/58550879/76900473-b5f15b00-6899-11ea-844f-dc8b5ae7aeca.PNG)
![Deckboard advanced shortcuts editor](https://user-images.githubusercontent.com/58550879/76900476-b7bb1e80-6899-11ea-8dda-7e1eeb718d0b.PNG)


Hope this was helpful ! :D
