### ISSUE TITLE
[Request] Some requests

### ISSUE THREAD

**Issue by kolfadoff** [rivafarabi/deckboard#39]
Some requests:
1. Rearrangeable Buttons and Boards
2. Import/Export (save to file, usefull for backups)
3. Board Icons Suport
4. More options for key combinations, up to 4 (usefull for editing softwares like photoshop, premiere, after fx. In my case some simple cobinations like Ctrl+Alt+Del doesn't work.)

Great app! Thanks!

**Comment by ZantsuRocks** [comment]
You can backup your buttons/boards copying the file database.db located under "C:\users\%user%\deckboard\"
Actually the buttons already are rearrangeable.

**Comment by kolfadoff** [comment]
> You can backup your buttons/boards copying the file database.db located under "C:\users%user%\deckboard"
> Actually the buttons already are rearrangeable.

Thank you! But I was thinking if the backup processes could be more intuitive, like "File>>Save As" and "Import Boards". 
Yes, the Buttons are already rearrangeable, I didn't notice before the last update. Let's wait for the rearrangeable Boards now. 
Thanks!

**Comment by rivafarabi** [comment]
Noted!

**Comment by kolfadoff** [comment]
Ps. I totaly forgot, the deckboard app could also start minimized to system tray.

Thank you very much!

**Comment by derMiepz** [comment]
+1 for "start minimized to system tray"
Commenting so it doesn't get buried since the last comment is from November 2018 😄
