### ISSUE TITLE
Macro used in multi action causes ctrl+alt keys to be stuck

### ISSUE THREAD

**Issue by Chill1993** [rivafarabi/deckboard#396]
When attempting to use a macro in a multi action event, the ctrl+alt keys become 'stuck' after executing the macro.
![stuck keys](https://user-images.githubusercontent.com/31005697/79476806-bea88e80-8009-11ea-93d1-aa0561b65aa8.png)

**Comment by SirBashchen** [comment]
Same issue exclusive to multi-action, Also affecting command (win), enter and I presume other buttons that aren't alphabetical or numerical.
Using Windows 10.

**Comment by rivafarabi** [comment]
Refer to #522
