### ISSUE TITLE
Deckboard and obs

### ISSUE THREAD

**Issue by Clanger70** [rivafarabi/deckboard#404]
I stream in my outdoor kitchen and gaming using 2 different computers, whats the best way to use Deckboard on my second computer it will not connect to obs, and i have different setups for each location.

**Comment by digitalfiz** [comment]
If you stream from each computer then you are going to need deckboard running on each and configured for their respective purposes and then use the app on your phone/tablet to connect to the one you are using currently.

Sadly deckboard doesnt have any kind of concept of a cloud save or something to sync your board configs to multiple instances of the server app on your desktops so each will need to be configured seperately.

**Comment by Clanger70** [comment]
ok now the issue is obs is not connecting with deckboard, any suggestions. in my log reprt it says not connecting with web socket is there a driver i need

**Comment by digitalfiz** [comment]
Yeah there is a plugin for obs you need to install if you are using pure obs and not something like streamlabs obs. https://obsproject.com/forum/resources/obs-websocket-remote-control-obs-studio-from-websockets.466/

**Comment by Clanger70** [comment]
Thank you so much that was the issue all along appreciate it.
