### ISSUE TITLE
Android does not center Icons in vertical orientation

### ISSUE THREAD

**Issue by mix3d** [rivafarabi/deckboard#408]
The App uses the UI setting that puts the statusbar as an overlay, so part of the icons are covered by the statusbar when in vertical orientation. There is plenty of space at the bottom. 

<img src="https://user-images.githubusercontent.com/1474137/81258028-9816bb80-8fe9-11ea-89c6-5910437bb46c.png" width="300px" />

**Comment by rivafarabi** [comment]
Fixed in v1.9.51
