### ISSUE TITLE
Aplicativo não funciona

### ISSUE THREAD

**Issue by marcospct** [rivafarabi/deckboard#41]
Quando tento conectar a aplicativo android no servidor no computador, o aplicativo diz que não conseguiu conexão! Como resolver? Estou usando a última versão do aplicativo no celular e no pc.

**Comment by BLACKinhoGOD** [comment]
Eu estava com o mesmo problema, tentei ativar o Deckboard pelo firewall desativei o firewall da rede publica e mesmo assim o Deckboard não dava conexão com meu celular, para resolver e muito simples, se você usa ou usou alguma vez programa de VPN como exemplo o RadminVPN ou até mesmo o Hamachi, esses programas deixam em aberto uma rede mesmo quando não estão sendo executados, oque fiz foi apenas desinstalar o Radmin do PC e o Deckboard consegui fazer a conexão com o meu celular, espero que tenha ajudado alguém
