### ISSUE TITLE
Edit board and New board buttons unresponsive in 1.9.4-rc2

### ISSUE THREAD

**Issue by machineabuse** [rivafarabi/deckboard#419]
In the current 1.9.4-rc2, the edit and new board buttons currently register the click but does not launch their interfaces.

![image](https://user-images.githubusercontent.com/8606354/82283598-6a5a4b00-99c9-11ea-8c0e-7aede9ffde46.png)

![image](https://user-images.githubusercontent.com/8606354/82283792-f4a2af00-99c9-11ea-87b0-77448c8997a7.png)

Side note: Thank you for adding the right side modifier scancodes! <3

**Comment by rivafarabi** [comment]
thanks for the info. quick patch for release candidate will be released soon.

**Comment by rivafarabi** [comment]
Fix for this issue is available in [v1.9.41-rc3](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.41-rc3)
