### ISSUE TITLE
2 ideas/request

### ISSUE THREAD

**Issue by redwolfffs** [rivafarabi/deckboard#42]
hi ! i really like your app but actually i just miss 2 things to be a perfect streamdeck like

1 a stop/pause option in the soundboard if is possible to have 3 options it will be perfect (1 play/repeat, 2 play/pause and 3 play/stop)
2 a twitch intégration would be nice  

thanks for your work is a great job !

**Comment by rivafarabi** [comment]
Thanks for the ideas. Have been experimenting with Twitch integration for a while, not coming out soon though.

Successful Twitch function:
- Subs count
- Total view count

Keep supporting me while I code in this dark dungeon! 😀
