### ISSUE TITLE
Unexpected token in JSON at position 15942

### ISSUE THREAD

**Issue by sirNugg3ts** [rivafarabi/deckboard#425]
As the title says

![image](https://user-images.githubusercontent.com/28486181/83047852-de879500-a040-11ea-8797-6a4008daff06.png)

**Comment by pGommes** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/29603439/86525247-275e1500-be5b-11ea-9084-894ed4f0fcf6.png)
