### ISSUE TITLE
[Minor Bug] App White Screen

### ISSUE THREAD

**Issue by christopher-merkley** [rivafarabi/deckboard#426]
If the mobile app is viewing the last board, and that board is deleted, the mobile app will display a blank screen for approx. 10 seconds. During this time, no other boards can be selected either. This bug is not present when the board is not the last board in the list.

Here are screenshots to further help my explanation:

Just an empty board viewed from the desktop application. Note it is the last board on the left side.
![03a342853d345051df934a6c0cdca262](https://user-images.githubusercontent.com/11699523/83218078-174b6b00-a122-11ea-9c08-7866ea988b74.png)

Mobile device currently displaying board.
![Screenshot_20200528-202414](https://user-images.githubusercontent.com/11699523/83218168-58437f80-a122-11ea-8040-60e2f83475d3.png)

The board has now been removed.
![7efb6fca8e57037534e1b40b06a40058](https://user-images.githubusercontent.com/11699523/83218258-980a6700-a122-11ea-806e-58636c83bca0.png)

The app shows a blank display.
![Screenshot_20200528-202436](https://user-images.githubusercontent.com/11699523/83218344-a5bfec80-a122-11ea-96c5-d8a8b1b4dfbd.png)

List is empty too.
![Screenshot_20200528-202447](https://user-images.githubusercontent.com/11699523/83218365-b3757200-a122-11ea-9971-8724edf11d72.png)

Mobile app ver. 1.9.5
Android version 7.1.1
Desktop app ver. 1.9.31

**Comment by rivafarabi** [comment]
Fixed in mobile app v1.9.51
