### ISSUE TITLE
Mark as abandoned

### ISSUE THREAD

**Issue by TTSKarlsson** [rivafarabi/deckboard#427]
As this is premium, closed source, software and very little works as expected of it, and no fixes or feedback to the customers are made, this project should be marked as abandoned to not mislead people and waste their money and time.

**Comment by digitalfiz** [comment]
He released a new version 11 days ago and as a follower of the project I see a good amount of activity from the dev and users, so how exactly is that abandoned? and he tends to respond to issues in batches. Not sure how much you expect from something that's free or $2.99 if you got pro...

**Comment by TTSKarlsson** [comment]
Yeah I'm probably wrong then, haven't seen any fix in a few months, or feedback. Will close this just to be sure not to inflame anything.
