### ISSUE TITLE
1.9.41-rc3 can not set image for buttons?

### ISSUE THREAD

**Issue by kriogenic** [rivafarabi/deckboard#428]
Since the latest update when I bring up the New Button or Edit Button window and select the image button, I am never prompted to select an image and the button seems to do nothing.

I tried running as admin as well and still same results.

**Comment by machineabuse** [comment]
Just verified, the image button no longer brings up the choose file dialog. That said if you need to you should still be able to add an image if you click on the graphic of the button itself.

![image](https://user-images.githubusercontent.com/8606354/83355529-92b35380-a392-11ea-9fe2-a3e3734046b1.png)

I normally add graphics this way, which is probably how I didn't notice this until you pointed it out.

**Comment by kriogenic** [comment]
That is just the thing, there is no longer any graphic there for me to click on
![image](https://user-images.githubusercontent.com/389938/83355630-fe51ec80-a3a3-11ea-9af9-58d193a6d46b.png)

**Comment by rivafarabi** [comment]
thanks for the info. I will look into this issue.

**Comment by rivafarabi** [comment]
The bug fix for this issue is available in [v1.9.41-rc4](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.41-rc4)
