### ISSUE TITLE
Streamlabs Toggle Mute Audio Control Does not Toggle

### ISSUE THREAD

**Issue by harfmil** [rivafarabi/deckboard#430]
Streamlabs 0.22.1 and Deckboard 1.9.31 (and 1.9.41-rc6)

Streamlabs OBS Audio Control - Device Selected - Toggle Mute

It will successfully mute the device, but tapping it again will not unmute. 

![image](https://user-images.githubusercontent.com/66324338/83640472-2b57f800-a57a-11ea-9fb4-55ef5c694594.png)

**Comment by hargossath** [comment]
hi, same issue here, even in the 1.9.41 rc version, the toggling never worked, it just mutes the device

**Comment by rivafarabi** [comment]
Thanks for the info. This issue has been solved in stable release version [1.9.50](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.50)
