### ISSUE TITLE
Samsung galaxy A5 / Windows 10 / Can't connect to computer via USB

### ISSUE THREAD

**Issue by ardz** [rivafarabi/deckboard#437]
Refuses to connect via USB. The phone is connected and recognised by Windows. Any tips/pointers?

Thanks

**Comment by ardz** [comment]
I've paid for the pro version of the app.

Thanks.

**Comment by rivafarabi** [comment]
Have you installed ADB as stated in the [instruction page](https://github.com/rivafarabi/deckboard/wiki/Troubleshoot)?

**Comment by ardz** [comment]
Apologies didn't realise you needed adb for to work; have got an Android SDK installed and it works after running "adb devices".

Thanks.
