### ISSUE TITLE
Unable to show interface using System Tray icon

### ISSUE THREAD

**Issue by kingcailan** [rivafarabi/deckboard#444]
In order to show Deckboard's interface, I must exit the app from system tray, then relaunch the app. 

Expected behavior: Rightclicking the Deckboard icon, then clicking the Deckboard option should show the interface. left clicking the icon should do the same.

Actual behavior: both actions do nothing, as does opening Deckboard's desktop shortcut.

Only known workaround is to force close the app using the tray icon then relaunch.

**Comment by rivafarabi** [comment]
This issue has been fixed in [v1.9,53](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.53)
