### ISSUE TITLE
[Feature Request] Toggle Scene Filter

### ISSUE THREAD

**Issue by Madcore** [rivafarabi/deckboard#450]
An option to let toggle scene filter visibility (not source filter).

Why? To take advantage of some of the options the **move transition** plugin have, like activate source transforms and movement when filter is activated/visible.

**Comment by ivanchukov** [comment]
It would be perfect!

Right now u can set a hotkey in obs. Do not set trigger to "enable/disable". Use the first one where is "none/use a hotkey" and enable all filters.
Then set hotkeys. I use something like CTRL+Numpad_0. And make keyboard macro button in deckboard.

**Comment by rivafarabi** [comment]
The current OBS websocket plugin doesn't support scene filter yet. But the latest v1.9.52 support source filter toggle.

Once the OBS websocket plugin support this feature, It will be added to Deckboard.
