### ISSUE TITLE
 Bug on color background

### ISSUE THREAD

**Issue by pGommes** [rivafarabi/deckboard#453]
I have the images of the icons in png, sometimes it happens that the chosen color goes back to black so I have to remove the image and choose again to normalize the background color.

![Screenshot_4](https://user-images.githubusercontent.com/29603439/86422341-3e620300-bcb3-11ea-8a0f-ca6293962f0c.png)
![Screenshot_5](https://user-images.githubusercontent.com/29603439/86422344-415cf380-bcb3-11ea-94e8-52caf5306959.png)

**Comment by Yurlyn** [comment]
I have this issue too. It happens as well when changing the label text

**Comment by rivafarabi** [comment]
Do you mind sharing the screen record showing the steps to produce this
specific issue?

**Comment by Yurlyn** [comment]
I can't make a recording atm but these are the steps I'm taking:

1. Make any button and set the parameters (I just tested it with an Open Website action) or modify an existing button;
2. Restart the app;
3. Change the label of the button from step 1.

**Comment by rivafarabi** [comment]
Fixed in version 1.9.52
