### ISSUE TITLE
Deckboard Pro 6x3

### ISSUE THREAD

**Issue by Smallinger** [rivafarabi/deckboard#454]
Hey is it possible to add a 6x3 view in the pro app ?

i have a long smartphone and have more space right and left over that can be used.

![Screenshot](https://i.imgur.com/5LTRTMh.jpg)

**Comment by JordynY** [comment]
Honestly, it'd be great to just have a custom that allows up to the maximums you can get working

**Comment by rivafarabi** [comment]
Custom grid added in [v1.9.61](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.61)
