### ISSUE TITLE
Once minimized, It won't restore it without restarting it

### ISSUE THREAD

**Issue by henriquearake1** [rivafarabi/deckboard#459]
I've installed it on my laptop that is running a Windows 10. But when I close it (clicking on the "x"), it won't restore it unless I shut it down and restarted back again (just deckboard, not the whole computer).

**Comment by Danak-UY** [comment]
I have the same problem, it leads me to not closing the app never which is annoying

**Comment by rivafarabi** [comment]
This issue has been fixed in [v1.9,53](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.53)

**Comment by henriquearake1** [comment]
Excellent!
