### ISSUE TITLE
disable brightness control?

### ISSUE THREAD

**Issue by f2bacon** [rivafarabi/deckboard#462]
could there please be an option to remove the brightness control and just let system brightness handle it? it's odd when i have my tablet at the lowest brightness and then i open the app and its bright as hell so i have to go into settings and raise and lower the brightness. and even then it's bright.

**Comment by qwksilver** [comment]
#455 , #421 , Android
Are Related

My issue is the 20% thing, on startup it goes where it wants, about 20%, the setting I give it doesn't help.   
It's also Wildly changed from the brightness in the system and the brightness in the settings.  If i go up a level and back to the slider control position it should have defaulted to it is a lot brighter then when I first enter the deck.

I prefer the idea here to just let the system manage brightness, and disable in app control.

I can also confirm that the high and low of the slider in the app, doesn't correspond to what's actually available in system brightness.

I would suggest the merging of all three of these issues and deal with it once and for all.

**Comment by rivafarabi** [comment]
I've brought back in-app brightness setting and "Use system brightness" toggle setting in client app version 3.1.4
The "Brightness" setting will be shown when you toggle off "Use system brightness". With both of these settings, you can freely choose between app or system controlled brightness.

Please feel free to open another ticket if you face the issue with this feature.

Closing this.
