### ISSUE TITLE
Deckboard 1.9.50 detect nothing automatically

### ISSUE THREAD

**Issue by roukmoute** [rivafarabi/deckboard#465]
Hi,

I've just installed deckboard 1.9.50 and it detects nothing automatically.

Here it is few screenshots ;

- From the wifi:
![image](https://user-images.githubusercontent.com/2140469/87987345-cd0db700-cade-11ea-9bc7-49c56b605204.png)

From the USB:
![image](https://user-images.githubusercontent.com/2140469/87987554-1eb64180-cadf-11ea-9284-badc01193a0f.png)

And my firewall is deactivated:
![image](https://user-images.githubusercontent.com/2140469/87987834-91bfb800-cadf-11ea-8049-9f14e351552b.png)
![image](https://user-images.githubusercontent.com/2140469/87987909-b2880d80-cadf-11ea-82a8-52a3acf643ff.png)

I also tried in root mode but it changes nothing.

I have currently the latest version on ondroid 1.9.51:

![image](https://user-images.githubusercontent.com/2140469/87988037-eebb6e00-cadf-11ea-9aad-9ebd76acc598.png)

Any idea?

It works only if I put my IP:
![image](https://user-images.githubusercontent.com/2140469/87988469-a6e91680-cae0-11ea-9344-0d1c5c1d58ce.png)
![image](https://user-images.githubusercontent.com/2140469/87988483-acdef780-cae0-11ea-9377-718b502f94cc.png)
![image](https://user-images.githubusercontent.com/2140469/87988536-ca13c600-cae0-11ea-9baa-24f0127c5d32.png)

**Comment by rivafarabi** [comment]
Can you send the log.log file located in `C:\Users\%USER%\AppData\Roaming\Deckboard` ?

**Comment by roukmoute** [comment]
```txt
[2020-07-19 23:26:46.186] [error] db:28 C:\Users\conta\AppData\Local\Programs\Deckboard\resources\database.db is not found.
[2020-07-19 23:45:07.265] [error] adb:36 Error: Command failed: adb start-server
error: could not install *smartsocket* listener: cannot bind to 127.0.0.1:5037: Une seule utilisation de chaque adresse de socket (protocole/adresse réseau/port) est habituellement autorisée. (10048)
could not read ok from ADB Server
* failed to start daemon *
error: cannot connect to daemon

    at ChildProcess.exithandler (child_process.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
[2020-07-20 23:08:08.402] [error] adb:36 Error: Command failed: adb start-server
error: could not install *smartsocket* listener: cannot bind to 127.0.0.1:5037: Une seule utilisation de chaque adresse de socket (protocole/adresse réseau/port) est habituellement autorisée. (10048)
could not read ok from ADB Server
* failed to start daemon *
error: cannot connect to daemon

    at ChildProcess.exithandler (child_process.js:299:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

**Comment by rivafarabi** [comment]
For anyone experiencing this issue. Please update to version 1.9.52.

In the previous versions, the IP address list in _Possible IP Addresses_  modal has been filtered. The list only shows the addresses with _192.168.xxx.xxx_ pattern.

This filter has been disabled in the latest version. So user can try connecting the app through all IP addresses that was hidden before.

Let me know if the issue still occurs
