### ISSUE TITLE
[Feature Request] add 7x4 Board

### ISSUE THREAD

**Issue by MetalFusions** [rivafarabi/deckboard#469]
Nice app, but I really need a 7x4 board.
I'll be so happy if you add that :)

**Comment by rivafarabi** [comment]
Custom grid size layout (with max width/height: 15), is in development right now. Will drop a beta release next week. 
![image](https://user-images.githubusercontent.com/4427494/88457619-29dbe980-ceb2-11ea-8815-2952b7eb27e7.png)

**Comment by MetalFusions** [comment]
Thanks bro, you're the best !

**Comment by rivafarabi** [comment]
Thanks for waiting. You can try the beta version [v1.9.60-rc1](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.60-rc1) which includes the custom grid size.
