### ISSUE TITLE
Support for discord

### ISSUE THREAD

**Issue by ObiwanKenoob** [rivafarabi/deckboard#47]
It would be lovely to be able to mute my mic / headphones on discord through the app! With similiar functionality as for OBS.. instead of having to create a hotkey in discord, and macroing it on the app..

Not sure if possible, but would be really neat if it is!

**Comment by cheycron** [comment]
You can create a hotkey on discord for that, and then register a keyboard macro in deckboar that runs on discord app.  I don´t try it but i think it should work.

**Comment by Tekkharibo** [comment]
I'm on linux I think it's bit differente however windows
The keybinding work if discord app is focused
