### ISSUE TITLE
Deckboard Windows App not Opening after update

### ISSUE THREAD

**Issue by Danak-UY** [rivafarabi/deckboard#470]
The windows app just updated automatically on windows start, but after that, the app didn't open, either from the system tray, closing and executing from .exe file, or even restarting the computer.
The app its supposedly running but if I can't open the app to scan for my device i can't connect my phone.

**Comment by rivafarabi** [comment]
Thanks for the feedback and it is indeed a bug. Will be realeasing the patch soon.


FYI try double clicking the Deckboard icon on the system tray. It should show the app window

**Comment by Danak-UY** [comment]
Ok, thanks for the double click tip
