### ISSUE TITLE
OBS scene is null?

### ISSUE THREAD

**Issue by Mitchfynde** [rivafarabi/deckboard#478]
![null](https://user-images.githubusercontent.com/69119725/89129069-a2553280-d4d0-11ea-93e5-3a7a302a1c97.png)

I have no idea what caused this. I didn't change anything that I'm aware of.

**Comment by seekinsoul** [comment]
I have the same issue. I think it happened with the most recent update.

**Comment by Mitchfynde** [comment]
> I have the same issue. I think it happened with the most recent update.

I thought it would have fixed itself, but I'm still having the issue. Dang.

**Comment by rivafarabi** [comment]
Do you mind to share the log.log file located in (C:\Users\%USER%\AppData\Roaming\Deckboard)?

**Comment by Mitchfynde** [comment]
[log.log](https://github.com/rivafarabi/deckboard/files/5030609/log.log)

**Comment by rivafarabi** [comment]
may I know which version of OBS Studio and OBS Websocket plugin currently installed on your PC?

**Comment by Mitchfynde** [comment]
OBS Studio 25.0.8 64 bit
How do I check the Websocket?

**Comment by rivafarabi** [comment]
It seems you have OBS Websocket plugin version 4.4.0 or below
I suggest you to install the latest version of the plugin.
You can download it [here](https://github.com/Palakis/obs-websocket/releases/tag/4.8.0)

**Comment by Mitchfynde** [comment]
> It seems you have OBS Websocket plugin version 4.4.0 or below
> I suggest you to install the latest version of the plugin.
> You can download it [here](https://github.com/Palakis/obs-websocket/releases/tag/4.8.0)

FIXED!! Thank you so much!
