### ISSUE TITLE
[Request] unlimited boards in pro/free &more

### ISSUE THREAD

**Issue by Sarge1992** [rivafarabi/deckboard#48]
it would be cool if we could have unlimted boards for making more elaborate deck layouts with submenus and the like perhaps as pro feature?

currently the app wont recognize more than 6 boards (im a niche user i know)

also if instead of scrolling over to the next board when you press a switch board button if it instead just instantly switched with no transition animation but thats a minor change

finally background images for buttons

note (not a bug or request but could you also tell me the corner radius for buttons id like to make some 3d buttons for my decks but i dont know what corner radius your using to make my buttons fit inside maybe a template or something you could provide?)

**Comment by Sarge1992** [comment]
sorry background images for boards not buttons

**Comment by rivafarabi** [comment]
OK I'll check em later. Thanks for the info. and for the boards background I'll put on suggestion list for now.

**Comment by DakodaPlays** [comment]
I know most of the stuff in this request is done but it would be cool for a wide screen mode for the pro app that adds an extra 4 buttons for phones with a longer screen like the Samsung Note's would be nice to have it 6 X 4 on my Note 9

**Comment by Sarge1992** [comment]
definatley what dakoda mentioned i use s 7 inch tablet and having the ability to have more buttons to use the extra screen space would be nice perhaps even the ability to choose a custom number of buttons per row/colloum
