### ISSUE TITLE
Reset layout on program start

### ISSUE THREAD

**Issue by toolewdpersona** [rivafarabi/deckboard#486]
Every time I run the program on a PC, layout = 4x3, when I set it to 9x4
I am using the program version 1.9.60-rc1
(pro version purchased)

![изображение](https://user-images.githubusercontent.com/49842912/90309762-ef370100-def3-11ea-8ac2-ba3eb2d4651f.png)

~sorry for my English

**Comment by rivafarabi** [comment]
Thanks for the report. this issue has been fix in version [1.9.60-rc2](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.60-rc2)
