### ISSUE TITLE
Not saving the resolution of the program window

### ISSUE THREAD

**Issue by toolewdpersona** [rivafarabi/deckboard#489]
It would be convenient if at a new start of the program, the previous resolution of the program window was preserved.

that is:
this is my changed resolution window program
![изображение](https://user-images.githubusercontent.com/49842912/90652157-811d7180-e246-11ea-924f-91f7f14a7b50.png)

and here is how it looks after restarting the program (window resolution is reset)
![изображение](https://user-images.githubusercontent.com/49842912/90651608-e02eb680-e245-11ea-8f3e-8a960a0acd5a.png)

**Comment by rivafarabi** [comment]
Thanks for the feedback. This feature will be included in this week's beta release. Stay tuned!

**Comment by rivafarabi** [comment]
Sorry for the late update. This feature is available in latest version [1.9.61](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.61)
