### ISSUE TITLE
[Bug] Open OBS studio in Deckboard Error and some other programs

### ISSUE THREAD

**Issue by AngelicDivine** [rivafarabi/deckboard#50]
I am getting this error when i wish to open OBS studio in Deckboard, and with stremalabs chatbot

**OBS studio errors**
Error 1 - Failed to find local/en-US.ini
Error 2 - Failed to load locale

**Streamlabs Chatbot errors**
Will not load locale state
 i try to load it via the app and it opens it but its like it loads it in a new state like if you reinstall/install the program. but when i load it normal from desktop it loads my state

( note - I only use 1 HHD in my pc so i know its not a directory error )

**Comment by Chris-FireFox** [comment]
This could be an issue with deckboard not using the prober location to launch the program from resulting in OBS not being able to find the prober files it needs

**Comment by ASavageProgrammer** [comment]
Another version of this batch : 

@echo off
cd "C:\Program Files\obs-studio\bin\64bit\"
obs64.exe
exit

This is more simple i guess, but this is the same ;)

**Comment by Johan140911** [comment]
I dont understand the solution of @CharleyEGervais, pls can explain me?

**Comment by Johan140911** [comment]
The @CharleyEGervais Method, don't work for me

**Comment by rivafarabi** [comment]
Solved by running this .bat file
`cd C:\Program Files\obs-studio\bin\64bit && start "OBS Studio" "C:\program files\obs-studio\bin\64bit\obs64.exe"`

**Comment by techmeav** [comment]
We can use this command in case you do not want to see the command prompt:-
`cd C:\Program Files\obs-studio\bin\64bit && start "OBS Studio" "C:\program files\obs-studio\bin\64bit\obs64.exe" && exit`
 save it in a bat file and then run this bat file in deckboard
Hope this helps for those who do not want to have their command prompt visible
Bye :)

**Comment by Johan140911** [comment]
So Thanks :)

**Comment by billyjbryant** [comment]
This would be easily solved if you could specify the running directory for the application. There should be a feature correction here rather than a workaround.

**Comment by AlokinVetob** [comment]
@echo off

START "OBS" /D "C:\Program Files (x86)\obs-studio\bin\64bit" "obs64"

exit 

This is mine and it closes the bat :) Hope it helped :)

**Comment by al-dank** [comment]
I fixed this by installing the Commands extension and simply making the action:
cd C:\Program Files\obs-studio\bin\64bit && start "OBS Studio" "C:\program files\obs-studio\bin\64bit\obs64.exe"

runs flawlessly like a typical launch shortcut.
