### ISSUE TITLE
Add the ability to have different images when an Icon is off or on

### ISSUE THREAD

**Issue by Slipfar** [rivafarabi/deckboard#501]
For example Follower only chat and Follower chat off can have different icons

**Comment by digitalfiz** [comment]
Welcome to the show here are few others that ask the same as you :P #451 #415 #391 #383 #475

**Comment by Slipfar** [comment]
Lets hope this issue/suggestion gets resolved then

**Comment by rivafarabi** [comment]
Still in the kitchen. Hope to include it in the next month beta
![image](https://user-images.githubusercontent.com/4427494/92346975-bf48db00-f0f8-11ea-832e-7a00cbca6f77.png)

**Comment by Slipfar** [comment]
Epic, thanks!
