### ISSUE TITLE
[error] obs:fetchScenes { error: 'invalid request type',...} : Can't scan OBS scenes and contents from Deckboard

### ISSUE THREAD

**Issue by Matsuki-Ritashi** [rivafarabi/deckboard#508]
Hello, I have a problem since the full update of OBS Studio and Deckboard.

**ERROR from logs:** [error] obs:fetchScenes { error: 'invalid request type',

**OBS Studio _correctly connected_ version:** 25.0.8 (64 bit)

**Deckboard pro _completely reinstalled as administrator on my windows administrator profile version_ :** 1.9.61 (64 bit)

I have already :

- Installed for all windows profiles **even if there is only one account** on my pc
- Installed for "**me only" with the only account and administrator** of my computer.
- Completely **uninstalled Deckboard**.
- Deleted the **contents of the cache in "Roaming"**.
- Deleted the **"Deckboard" folder in User which contains the "extensions" "database.db" "settings.json" files**

To perform my tests I have:

- **Save the "Deckboard" folders** of the "Roaming" and "User"
- **Tried after a complete and clean reinstallation** to use the "OBS scene" buttons
- **Change the port and password for the OBS connection** before reusing the default configuration

All Deckboard Pro features works. **Except those with OBS souces and scenes.**

![image](https://user-images.githubusercontent.com/71344236/93244599-48f84880-f78a-11ea-9112-b88ea20c0f10.png)

Features:

-Streaming control: Works ✅
- Audio Device Control: Works ✅
- Select scene: Return "null" in the box ❌
- Toggle source: Return "null" in the "source" box ❌
- Toggle Filter: Return "null" in the "scenes" box ❌
- Set transition: works ✅

After I restore my Deckboard buttons backup in the "user" file, the OBS connection is established, and the buttons work, while editing, the application is unable to tell me which scene it is. So I deduce that the application manages to read the scenes and the routing is correct.

![image](https://user-images.githubusercontent.com/71344236/93244787-8d83e400-f78a-11ea-8d13-68fe684679e0.png)
![image](https://user-images.githubusercontent.com/71344236/93244789-8f4da780-f78a-11ea-8e3e-5ef57e73ec25.png)

I think the problem is scanning the OBS scenes in the app. Could not make new buttons for. But we can use the ones that had already been configured a year ago, when the buttons were working.
I got the logs when I returned "null" and wrote in the "WHY" "IS" "IT" box to have three possible error messages in the logs.

```
[2020-09-15 20:07:05.007] [error] adb:startDeviceTracker Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2020-09-15 20:07:11.216] [error] obs:fetchScenes { error: 'invalid request type',
  'message-id': '4',
  status: 'error',
  messageId: '4' }
[2020-09-15 20:07:18.501] [error] obs:fetchScenes { error: 'invalid request type',
  'message-id': '129',
  status: 'error',
  messageId: '129' }
```
A little later, I tried to add a button for an OBS scene by simply clicking on the return "null" and having a trace in the logs:
![image](https://user-images.githubusercontent.com/71344236/93244599-48f84880-f78a-11ea-9112-b88ea20c0f10.png)

```
[2020-09-15 20:26:34.702] [error] adb:startDeviceTracker Error: spawn adb ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2020-09-15 20:27:00.260] [error] obs:fetchScenes { error: 'invalid request type',
  'message-id': '6',
  status: 'error',
  messageId: '6' }
[2020-09-15 20:27:15.268] [error] obs:fetchScenes { error: 'invalid request type',
  'message-id': '131',
  status: 'error',
  messageId: '131' }
```

I would like to know if I am an isolated case and especially to find a solution to continue to be able to add OBS buttons and to benefit from the application.

Thanks in advance for your answers, hoping there is a solution to my problem (:

**Comment by rivafarabi** [comment]
It seems you have OBS Websocket plugin version 4.4.0 or below
I suggest you to install the latest version of the plugin.

**Comment by Matsuki-Ritashi** [comment]
I feel so silly that I forgot to update the plugin haha ​​Sorry, thanks again !! I will make a financial contribution when I have received my pay! :D
