### ISSUE TITLE
Saving doesn't do anything.

### ISSUE THREAD

**Issue by ZaHecc** [rivafarabi/deckboard#51]
I have tried to use this program in the past and it's been about a year or so since looking for alternatives for Elgato's Streamdeck. This sure looks promising but this time I can connect to my phone, unlike last time I downloaded this. With that aside, before I was able to make 2 buttons with custom images and today I tried to edit and add more than 2. It wasn't letting it update to the image I was trying to upload OR try to add more button to the program. I've since tried seeing if even deleting my button present would do anything and GUESS WHAT... They deleted. Now I have no buttons and no way to add more. I was really expecting this to be further updated revisiting this a year later.

**Comment by rivafarabi** [comment]
May I know which version you using (both on your PC and mobile device)?

**Comment by ZaHecc** [comment]
The most recent version for both downloaded today...

**Comment by rivafarabi** [comment]
If you have installed older version of desktop app on your computer
(version 1.2.3 or older), try delete database.db in
C:/Users/%USERNAME%/deckboard

**Comment by ZaHecc** [comment]
Holy crap, it worked!
Thank you so much!
