### ISSUE TITLE
Spotify dont works

### ISSUE THREAD

**Issue by FrankDev14** [rivafarabi/deckboard#510]
Hello, I bought the PRO version today and when I will put spotify into deckboard I go to options and login. Get sucessful login, but the account dont appear, and cant control spotify with the deck. Solutions? or is a bug?

**Comment by rivafarabi** [comment]
Do you mind sharing the log.log file located in `C:\Users\%USER%\AppData\Roaming\Deckboard`?

**Comment by FrankDev14** [comment]
Solved, i use one account that the program cant get it for profile problems. But i spotify controls dont works, only works if use media control
