### ISSUE TITLE
Support for resizing buttons

### ISSUE THREAD

**Issue by Bluetopia** [rivafarabi/deckboard#511]
After recently getting a Asus Zenbook 15, I realized that I could use Deckboard instead of the not-particularly-customizable ScreenPad app for the touchpad.  

The only problem is that the buttons are just a smidge too small at the screenpad's 1000x500 resolution.  Each button ends up about 1cm x 1cm on the screen.

![IMG_20200921_212453](https://user-images.githubusercontent.com/24968231/93837362-d092fb00-fc53-11ea-9f95-7fb355c17493.jpg)

4 rows by 9 columns seems to work well, though I'd really like to be able to increase the size of the buttons so I'm not as liable to misclick a button.

I noticed there was a post asking for this back in 2018, I'm curious if any progress has been made as I can't seem to find icon size as an option in any of the settings.

Thanks!

**Comment by rivafarabi** [comment]
First of all, wow. Never crossed my mind using the app like this, not even when developed this feature couple months ago.

And thanks for the feedback. This will be noted for next beta release.

**Comment by Bluetopia** [comment]
As of 1.9.80, I can use the zoom @ 110% to fill the ScreenPad with a 9x4 grid.
