### ISSUE TITLE
Drag buttons to different boards

### ISSUE THREAD

**Issue by MisterMorgue** [rivafarabi/deckboard#513]
It would be amazing if you could drag buttons that you've already created to different boards that you have. It would make organising buttons and such far easier! Or even just add an option to switch what board the button is on in the edit screen.

**Comment by rivafarabi** [comment]
Dragging buttons to different boards currently is not available. But, you Copy/Cut and Paste a button from one board to another. The options can be seen by right clicking the button.

**Comment by MisterMorgue** [comment]
I did notice that after I'd posted this, thank you!
