### ISSUE TITLE
[NEW FEATURE] Spotify Integration coming soon

### ISSUE THREAD

**Issue by rivafarabi** [rivafarabi/deckboard#52]
Just as the title said, Spotify integration will be supported in Deckboard. It will come out in v1.2.63

![czignron8i](https://user-images.githubusercontent.com/4427494/48851949-e4af0c80-edde-11e8-8c5f-32de10118fe3.gif)

**Comment by TheManiacHS** [comment]
my Deckboard dont do anything on my app
