### ISSUE TITLE
New feature (dual stage images) not working in 1.9.70-beta.0

### ISSUE THREAD

**Issue by derMiepz** [rivafarabi/deckboard#521]
When replacing the already existing "Not Active" image, you can't set an image for "Active". (Check the mouse cursor not changing)
When setting an "Active" image before changing or removing the "Not Active" image, both images get replaced

Video: https://streamable.com/3figs9

**Comment by rivafarabi** [comment]
Thanks for the info. It seems the bug only occurs when the user pick the GIF file.
Will be fixed in the next beta release.

P.S. the android app version that supports this feature (v1.9.70) will be regularly rolled-out, so there will be a quite gap between desktop app and mobile app release time.

**Comment by derMiepz** [comment]
Awesome thanks!

**Comment by rivafarabi** [comment]
This issue has been fixed in version [1.9.70-beta.1](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.70-beta.1)

**Comment by derMiepz** [comment]
Can confirm that it works as intended and shows correctly on desktop and mobile. Thanks for the quick fix! ❤
