### ISSUE TITLE
Icons not displaying properly on my tablet device

### ISSUE THREAD

**Issue by Deuzius** [rivafarabi/deckboard#525]
This issue started occurring 2 days ago. I'm on the same Wifi network, the buttons work, but the default icons have.... become something else.

This is a preview of my Deck Pro on the tablet.

![Screenshot_20201008-185624](https://user-images.githubusercontent.com/22702599/95490333-63dc6800-0998-11eb-942e-d98e14eba0c2.png)

This is a preview of my Deck software on PC.
![image](https://user-images.githubusercontent.com/22702599/95490424-81113680-0998-11eb-875f-bac857facfe8.png)

**Comment by rivafarabi** [comment]
The bug fix for this issue has already been included in [v1.9.71](https://play.google.com/store/apps/details?id=com.rivafarabi.deckboard.pro). Let me know if you still face the same issue.

**Comment by Deuzius** [comment]
Fixed in latest release. Thank you
