### ISSUE TITLE
[BUG] Voicemeeter extension, can't add any action.

### ISSUE THREAD

**Issue by PifLyon** [rivafarabi/deckboard#546]
Hi, I'm using 
-Deckboard 1.9.61 on windows 10 2004, 
-voicemeeter extension 1.1.0 installed from deckboard's PC in-app extension menu
-Android tablet with Deckboard PRO.

On windows, I click the + to add a button, select _any_ action on voicemeeter choices, then **nothing** else happens. I can't validate anything ("Add" button is greyed).

I saw somewhere to use 1.0 extension instead, but I don't see it in the App's extension menu, I don't know what I should do.
Can you help ?
![2020-11-04 17_13_46-deckboard](https://user-images.githubusercontent.com/33943609/98136465-403a0e00-1ec1-11eb-8d3b-731dbf5ee720.png)

**Comment by chrisbadley** [comment]
Theres a post by the developer on another thread regarding this saying to downgrade back to 1.0.0 until the next release.

**Comment by chrisbadley** [comment]
Uninstall 1.1.0 and download the 1.0.0  .asar file and place it inside this directory C:\Users\XXX\deckboard\extensions

Download here > https://github.com/rivafarabi/voicemeeter-control/releases/tag/v1.0.0

**Comment by PifLyon** [comment]
Thank you very much Chris !
Unfortunatly, although there are more parameters, it does not work, I can't choose a strip/bus other than 0. As shown on the picture attached. 
![deckboard-strip-value](https://user-images.githubusercontent.com/33943609/98443780-f8f48d00-210d-11eb-8e75-8765039501a1.png)
I don't know if I miss something. I already use, beside, macro-buttons that works 
![deckboard-strip-value-macrobutt](https://user-images.githubusercontent.com/33943609/98443818-3bb66500-210e-11eb-9030-2dda569b9153.png)

**Comment by chrisbadley** [comment]
This is probably the same issue as yours: https://github.com/rivafarabi/voicemeeter-control/issues/2

This is a hotfix for it:

https://github.com/rivafarabi/voicemeeter-control/pull/4/commits/b1d559b8613b71ed9190b74a5fb4603a78a568e4

**Comment by PifLyon** [comment]
Thanks Chris. The issue described is the good one, but the way to fix it (edit a file in text editor) is impossible as there is no file to edit in deckboard/extensions/ except a 40Mo file (.asar). I hope a future version will work straight out of the box as I like to recommend Deckboard. I'm gonna ask in the other thread what file they are talking about. :)

**Comment by chrisbadley** [comment]
Ok, here is what to do. Delete the .asar file from deckboard/extensions folder. Then create a new one folder inside deckboard/extensions/voicemeeter-control

The download this zip [here] (https://www.transfernow.net/JJl3UH112020) and extract the files into it. This zip contains a corrected version of the source of 1.0.0 and should work straight away after restarting deckboard.

**Comment by PifLyon** [comment]
Hi Chris,
You the man ! It works. Thank you very much. 
I made 2 button (mute & unmute) as there is no "toggle" button on deckboard yet. If you know (or are ?) the developper, please suggest it.
Thank you again. :)

**Comment by rivafarabi** [comment]
The extension has been updated to version [1.2.0](https://github.com/rivafarabi/voicemeeter-control/releases/tag/1.2.0)
This update include the fix for disappearing dropdowns in version 1.1.0

**Comment by PifLyon** [comment]
Ah ah, one day after... I uninstalled and installed the new version 1.2.0. **Everything is OK**.
Thank you Very Much !
_PS out of topic  : Mistake I guess in english translation, when clicking on the little USB icon at the top right, it says "Not connected device". I think it should be "**No** device connected" _

**Comment by rivafarabi** [comment]
> _PS out of topic : Mistake I guess in english translation, when clicking on the little USB icon at the top right, it says "Not connected device". I think it should be "**No** device connected" _

Noted!

**Comment by ShooterMcLuvin** [comment]
> Hi Chris,
> You are the man ! It works. Thank you very much.
> I made 2 buttons (mute & unmute) as there is no "toggle" button on deckboard yet. If you know (or are ?) the developper, please suggest it.
> Thank you again. :)

I would like some assistance with this as I am trying to use deckboard with voicemeeter currently but cannot figure out how to set the "unmute" as there is no option for "Unmute" in the dropdown... Can you tell me how you were able to do this? Please and thank you!

**Comment by PifLyon** [comment]
Hi @ShooterMcLuvin , here is what you want :

![image](https://user-images.githubusercontent.com/33943609/125709000-f589d4f0-a5b8-4f2c-bcff-0f719200a19b.png)

As far as I know, you must have 2 separate buttons, one for Mute, one for UnMute.
