### ISSUE TITLE
[bug] my friend cant get it to work 

### ISSUE THREAD

**Issue by AngelicDivine** [rivafarabi/deckboard#55]
When my friend installed it she went to grab the IP but it tells her it cant up tan it 

What should she do?

**Comment by rivafarabi** [comment]
- Try using different IP address listed in Possible IP Addresses option, in case your friend has virtual machine installed.
- Allow connection from firewall setting
- Make sure both PC and device not connected to VPN

**Comment by AngelicDivine** [comment]
Alright it seems we cant get it to work its ok

She said once we get it to work she will use it i showed it to her on my end and she cant wait to use it thanks so much for the massive work you have put into this

**Comment by rivafarabi** [comment]
Thanks. And I am sorry that I can't help you this time.
