### ISSUE TITLE
[FEATURE REQUEST] Start minimized to system tray

### ISSUE THREAD

**Issue by hexandcube** [rivafarabi/deckboard#550]
When Deckboard runs at startup, the window appears, and you have to manually close it. It's very annoying.
Would've been great if Deckboard started minimized to the system tray.

**Comment by ZantsuRocks** [comment]
Duplicate of #24

**Comment by LoungeLizard65** [comment]
Add this line to your batch file and it will simulate closing the window.  A timeout is added to let Deckboard fully start.  

powershell (ps Deckboard).CloseMainWindow()

Cheers.
