### ISSUE TITLE
Twitch will not take emotes commands via deckboard

### ISSUE THREAD

**Issue by rbz205** [rivafarabi/deckboard#554]
I use deckboard app to show emotes on my Twitch channel. 

For example I will use multi-action

1. Type "Emote123"
2. Keyboard Macro "Enter"

It used to send the appropriate emote. Now Twitch only receives "Emote23" instead of "Emote123". I am not sure where the issue is coming form. 

I do other multi-action and it works still. 
 
1. Type "!rule"
2. Keyboard Macro "enter"

**Comment by chrisbadley** [comment]
You can just use a twitch send chat action and add the text for your emote within the send field. You do not need an enter command.

**Comment by rbz205** [comment]
Ok, thanks that is a good alternative.
