### ISSUE TITLE
[BUG] I can't update it to v1.9.80 when I give next the app closes and it doesn't update

### ISSUE THREAD

**Issue by RobloxWinner** [rivafarabi/deckboard#567]
**Describe the bug**

**To Reproduce**
3. Fill a value to '...'

**Expected behavior**

**Screenshots**

**Server App (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 1.9.0]

**Client App (please complete the following information):**
 - OS: [e.g. Android 9]
 - Version [e.g. 1.9.60]

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

**Additional context**

**Comment by XsFrozdY** [comment]
If it's installed "Only for me", try installing it "for all users" or vice versa, that allowed me to install it.

**Comment by Boldbuilder** [comment]
> If it's installed "Only for me", try installing it "for all users" or vice versa, that allowed me to install it.
> 
> It's a temporary fix at least.

I have the same issue and I tried installing it "for all users" and "Only for me" and still doesn't allow me to install it. any idea what's wrong? Oh, I've tried running as administrator too. still don't work.

**Comment by ewayenzo** [comment]
I have the same issue, after the last update when i click on install for me or all users it closes after a few seconds. it crashes after this state.
![image](https://user-images.githubusercontent.com/34748254/99905484-4ad21100-2cd1-11eb-97d7-dfe345b0b389.png)

**Comment by ewayenzo** [comment]
UPDATE: i fixed it by saving the databases located in "C:\Users\%USER%\AppData\Local\Programs\Deckboard" and "C:\Users\%USER%\deckboard" then uninstalling and downloading the new setup in 1.9.81, reinstalling it then uploading databases again.
You may have to reconnect to spotify if you're using it tho.

**Comment by rivafarabi** [comment]
Thanks for the info. It is confirmed as a bug. The patch will be available in several hours

**Comment by rivafarabi** [comment]
The fix for this issue has been included in [v1.9.82](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.82). Just run the installer as usual while the server app is closed. 

I apologize for this issue.
