### ISSUE TITLE
[BUG] updater progress about 30% then <poof> disappears & starts a loop

### ISSUE THREAD

**Issue by zeenewbian** [rivafarabi/deckboard#578]
**Describe the bug**

**To Reproduce**
3. Fill a value to '...'

**Expected behavior**

**Screenshots**

**Server App (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 1.9.0]

**Client App (please complete the following information):**
 - OS: [e.g. Android 9]
 - Version [e.g. 1.9.60]

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

**Additional context**

**Comment by rivafarabi** [comment]
Closed because of duplicate issue. Please refer to issue #567

**Comment by zeenewbian** [comment]
so the 1.9.82 updater still is bugged?

**Comment by rivafarabi** [comment]
> so the 1.9.82 updater still is bugged?

The update also fix the auto update installer. So it will work for future update releases

**Comment by zeenewbian** [comment]
ok - exactly which "database" files do i need to copy to replace after the
uninstall/reinstall? there are 2 ".db" files in 2 locations i can find but
do i need to copy/save any other files? ,json?

**Comment by rivafarabi** [comment]
The database.db file and other installed extensions won't be affected by reinstall/uninstalling the app. So it will be fine.

**Comment by zeenewbian** [comment]
well, fyi, they are affected if you use revo uninstaller so i will just try
the supplied uninstaller. to be safe then all i have to do is have copies
of the .db files (2 in 2 different locations)?

**Comment by rivafarabi** [comment]
If you want to make sure and want to make the backup of the file, just backup all the files located in `C:/Users/%USERNAME%/deckboard`

**Comment by zeenewbian** [comment]
thank you
