### ISSUE TITLE
[BUG] Board order, 

### ISSUE THREAD

**Issue by Yurlyn** [rivafarabi/deckboard#598]
**Describe the bug**
1. **The board order still gets scrambled.** I can't set an order as it will mess up the moment I restart Deckboard or when I add a new board or delete a board. This has been an issue for a long time, at least since version 1.4.0. Currently running server version 1.9.82.
2. **OBS Studio scenes missing.** Despite being connected to OBS Studio (v26.0.2) I can't set Toggle Scene or Toggle Source as it gives me a null on the scene selection. See screenshot.
3. **Remember window size.** I guess, this could also be a feature request but switching between control and edit modes on the server resizes the window and it won't remember the previous window size. Could this be fixed? Even if it's just a one-size-fits-all thing.

**To Reproduce**
1A. Set board order
1B. Add or delete a board or restart Deckboard

2A. Try adding a Toggle Scene or Toggle Source button.
2B. Try selecting a scene in the settings.

3A. Pressing "Start" on Deckboard after setting a certain size for the editor.
3B. Resizing the control window and then press the "X" to stop the control mode.
3C. Repeat.

**Expected behavior**

**Screenshots**
Problem 2:
![image](https://user-images.githubusercontent.com/42919979/100859059-10b1fd80-348f-11eb-91e0-300067a28b26.png)

**Server App (please complete the following information):**
 - OS: Windows 7 Ultimate 64bit
 - Version: Version 1.9.82

**Client App (please complete the following information):**
 - OS: Android 8.0.0
 - Version: 1.9.80

**Required files**
[database & log.zip](https://github.com/rivafarabi/deckboard/files/5628533/database.log.zip)

**Additional context**

**Comment by bean5** [comment]
I am not experiencing this. Has this been fixed?

**Comment by Yurlyn** [comment]
Not everyone had this experience. But this long-standing bug was finally squashed (at least for me) with the June update this year.
