### ISSUE TITLE
Wait Times between Keys in Macro

### ISSUE THREAD

**Issue by BloodSteyn** [rivafarabi/deckboard#60]
I've been using ROCCAT Power-Grid for a few years now but it's no longer available or supported. One feature it had was the ability to place "Wait / Pause" times between Keypresses in a macro.

Could we have an "Advanced Macro Editor" that could include the ability to have wait times added between key press (up/down) or even between the press and release of the keys?

ROCCAT used a text box with commands like these 

**Legend**
- ; - End of Command
- d X - key down
- u X - key up
- p X - press key (doesn't always work with ED, d & u is a better option)
- t abc - Text (doesn't work well with long text, break it up)
- 123; - Wait time before executing next command
- SPACE - Spacebar
- BACK - Backspace

It would allow me to write a macro with pauses that would coincide with the animations happening in a game, so it would only execute the next step when it would be relevant. Like so:

> d 1; 50; u 1; 50; d E; 50; u E; 50; d E; 50; u E; 50; d SPACE; 50; u SPACE; 50; d S; 50; u S; 50; d SPACE; 50; u SPACE; 50; d Q; 50; u Q; 50;d Q; 50; u Q; 50; d 1; 50; u 1;

The numbers indicate the Wait time in milliseconds between actions, like Down "1", Wait 50ms; Up "1"; Wait 200ms; Next Step.

You can read a post I made about Power-Grid here for some ideas -  https://www.reddit.com/r/EliteDangerous/comments/9wbapy/psa_roccat_powergrid_no_longer_available_from/

Your App is the next best thing I've come across and would gladly buy the Pro version if we could have a Textbox like Advanced Macro editor.

Thanks, keep up the great work.

**Comment by rivafarabi** [comment]
Thanks for the request! Noted for future release

**Comment by rivafarabi** [comment]
It's done. I'm going to release it this weekend.

**Comment by BloodSteyn** [comment]
Wow, that was the quickest turnaround I've ever encountered. Well done, looking forward to testing it.

**Comment by rivafarabi** [comment]
Added in version 1.2.63!
