### ISSUE TITLE
[BUG] Can't switch boards on 7-inch touch screen monitor

### ISSUE THREAD

**Issue by L3xXxSpooky** [rivafarabi/deckboard#623]
**Describe the bug**
I can't switch between boards when using Deckboard. For example, I have my mainboard and a soundboard, and I made a button where it would switch between the two and it doesn't work.

Also, I am using this only on Windows, not on a mobile device. I have a second small 7-inch touch screen monitor that I am using, could that be the problem because everything else works fine on it.

**To Reproduce**
Have Deckboard on my touch screen monitor (not mobile device)
Make a button to switchboards
Press the button
Nothing happens

**Expected behavior**
I'm expecting that the button will switch between my two boards

**Server App (please complete the following information):**
 - OS: Windows 10 Pro OS build 19041.450 or Version 2004
 - Version 1.9.84

**Client App (please complete the following information):**
I am using a 7-inch touch screen monitor as my screen

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`) <--- won't let me up load it
- log.log [log.log](https://github.com/rivafarabi/deckboard/files/5744119/log.log)

**Comment by rivafarabi** [comment]
Fixed in [v2.0.5-rc3](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.5-rc3)
