### ISSUE TITLE
[BUG] Missing fonts on System Dialogs Arch Linux

### ISSUE THREAD

**Issue by luccacondratiuk** [rivafarabi/deckboard#624]
**Describe the bug**
I've installed the snap version, on Arch Linux (KDE Plasma) and Manjaro KDE, and in both cases, when a system dialog is opened, the fonts doesn't load (picture)...

**I've tried**
`rm -f /var/cache/fontconfig/*`
`rm -f ~/.cache/fontconfig/*`
`rm -f ~/snap/deckboard/common/.cache/fontconfig/*`
`fc-cache -r`
and reboot

And I've tried to run the appImage, but it didn't work as it says in [Issue 609](https://github.com/rivafarabi/deckboard/issues/609)

**Screenshots**
![bug-deckboard](https://user-images.githubusercontent.com/28022104/103238752-6660b500-492a-11eb-8f33-f8fba41213c0.png)

**Server App:**
 - OS: [Arch Linux]
 - Version [e.g. 1.9.61] - (Maybe publish the newest version in snap?)

**Comment by rRobis** [comment]
Not sure, but I guess that's a problem with missing fonts on your system, since, on my Manjaro Arch Linux KDE Plasma, it shows everything properly. I have no idea how to check required fonts, but if someone knows how, he could post the list here.

**Comment by luccacondratiuk** [comment]
> Not sure, but I guess that's a problem with missing fonts on your system, since on my Manjaro Arch Linux KDE Plasma, it shows everything properly. I have no idea how to check required fonts, but if someone knows how, he could post the list here.

humm, maybe could be a missing dependecie... as I said, the newest stable version publish here is 1.9.84, and the snap version still in 1.9.61...

But @rRobis, could you please, list the fonts contained in this following directories:
`ls /snap/deckboard/3/gnome-platform/usr/share/fonts`
`ls /usr/local/share/fonts`
`ls /usr/share/fonts`

maybe I could install the missing font

**Comment by luccacondratiuk** [comment]
So, my workaround was:
Edit the file `~/snap/deckboard/3/.config/fontconfig/fonts.conf` , and added the following line `<dir>/home/MYUSERNAME/.local/share/fonts<dir>`
And then installed (globally) the following google fonts:
 - Lato
 - Montserrat
 - Noto Sans JP
 - Nunito
 - Open Sans
 - Oswald
 - Raleway
 - Roboto
 - Roboto Mono
 - Rubik
 - Source Sans Pro
 - Ubuntu
 - Ubuntu Condensed
 - Ubuntu Mono

Don't know exatly wich one solved the problem... but it worked! lol

But still if possible @rivafarabi, upgrade the font dependencies should solve the problem.
If it helps, for me the `/snap/deckboard/3/gnome-platform/usr/share/fonts` directory was empty...

**Comment by deimidis** [comment]
Thanks, it didn't worked for me. I couldn't installed rubik font, maybe that was the problem

**Comment by deimidis** [comment]
I installed ttf-rubik but still I don't have characters in the file menu. I don't have the folder at /snap/deckboard/3/gnome-platform/usr/share/fonts 

I tried to create a symbolic link to /usr/share/fonts, but it did't worked

**Comment by luccacondratiuk** [comment]
Fixed on AppImage [1.9.95](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.95)
Thx @rivafarabi  for the amazing work!
