### ISSUE TITLE
[FEATURE REQUEST] Open minimized on Startup

### ISSUE THREAD

**Issue by MarcosKlender** [rivafarabi/deckboard#625]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem but it's an useful feature.

**Describe the solution you'd like**
Start Deckboard minimized when Windows starts.

**Describe alternatives you've considered**
An option in General Settings called "Open Minimized" near the "Open on Startup" feature. 

**Additional context**
Please. (:

**Comment by rZiMiZ** [comment]
Haahaha, oh yeah!

**Comment by ZantsuRocks** [comment]
Duplicate of #24
