### ISSUE TITLE
[FEATURE REQUEST]Switch icon for macro

### ISSUE THREAD

**Issue by LegendsIta** [rivafarabi/deckboard#630]
Hi, is it possible to implement a toggle keyboard shortcuts system with 2 icons?
For example at the first pressure the icon or the color changes so that you understand that it is active, and at the second pressure it returns as it was before!
At each press it will always execute the same key combination, but it will change the icon or the color shown!

**Comment by panoc** [comment]
I would like that too, pasically i would like to have to option for 2 state icons on every command / button.
