### ISSUE TITLE
[BUG] Max. amount of buttons that show up are 12 (3x4)

### ISSUE THREAD

**Issue by Emmanuel-Grunn** [rivafarabi/deckboard#638]
**To Reproduce**
1. Make a grid in deckboard server, bigger than 3x4
2. Open the free app on the phone and connect via Wlan / USB
3. The grid is 3x4 on the phone

**Expected behavior**

**Server App (please complete the following information):**
 - OS: Windows, Pop OS

**Client App:**
 - OS: Android 6.0

**Comment by rivafarabi** [comment]
To display board with grid size larger than 4x3, you need to use PRO version of the app.

This limitation is described on the ADD/EDIT BOARD modal when the user tries to set the width larger than 4 or height larger than 3
![image](https://user-images.githubusercontent.com/4427494/106268975-6d971d80-625e-11eb-9444-a1e21e03299b.png)
