### ISSUE TITLE
[BUG] Type Text skips double characters

### ISSUE THREAD

**Issue by thetomatoplanet** [rivafarabi/deckboard#640]
**Describe the bug**
When using the Type Text on words with two characters next to each other, which are the same, like bague**tt**e or pi**zz**a, one of the characters get skipped. Result would be bague**t**e or pi**z**a.

**To Reproduce**
Try it with baguette:
1. Choose action Type Text
2. Set "baguette" as text
3. Try it
4. It wrote "baguete" instead of "baguette"

**Server App (please complete the following information):**
 - OS: Windows
 - Version 1.9.84

**Client App (please complete the following information):**
 - OS: Android 7
 - Version 1.9.80

[log.log](https://github.com/rivafarabi/deckboard/files/5920546/log.log)
[database.zip](https://github.com/rivafarabi/deckboard/files/5920562/database.zip)
**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

**Comment by MysTerioNSoull** [comment]
Confirmed and replicated.

**Comment by bean5** [comment]
Is this still occurring?

**Comment by thetomatoplanet** [comment]
Luckily not! Forgot this issue exists 😂
