### ISSUE TITLE
Mac OS Release

### ISSUE THREAD

**Issue by Danak-UY** [rivafarabi/deckboard#645]
Are you planning to release the server app to Mac OS?

**Comment by rivafarabi** [comment]
Both server and client apps for macOS and iOS are done and ready to go.

The problem is within Apple Developer program registration, still on
progress.

I hope for all Mac and iPhone users to wait a little bit longer

**Comment by Danak-UY** [comment]
Thanks, perfect!
I actually use the Android and Windows apps but would like to use it in my mac book for work too.

**Comment by biketalks** [comment]
any information about the MacOS client?
