### ISSUE TITLE
Button for Screenshots

### ISSUE THREAD

**Issue by enocvt** [rivafarabi/deckboard#659]
I want to be able to take screenshots that save automatically to a folder. Windows 10 has "Windows Key+Prt Sc" shortcut, but Deckboard don't pick the Print Screen key press.

Maybe Deckboard could have some sort of "Special keys" section in the Advanced Keyboard Macro, or the ability to write the name of the key, or simply a new type of button that can take screenshots with a press.

**Comment by rivafarabi** [comment]
Thanks for the feedback. This feature has just been included in the latest version ([v1.9.86](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.86))

**Comment by enocvt** [comment]
What a timing! Thanks!

**Comment by Tarikus252** [comment]
Hi. I want to actually simulate the PrintScreen pressing because I’m using ShareX to take screenshots. Is there any way now to do this?
