### ISSUE TITLE
Button Placement bug

### ISSUE THREAD

**Issue by Revenger** [rivafarabi/deckboard#66]
There's a bug with the button placement when you move it.
Other icons are being rearranged which they shouldn't be.
They should ONLY move once the button is dropped into place until then they shouldn't move just by moving a button over the board which is what's happening.

[Video here](https://youtu.be/IloDYit5iqM)

The proper way this should work is as follows:
If the space is blank it should just move there.
If the space is occupied it should swap buttons.
There could be a toggle in the options that if a space is occupied it  swaps as above or pushes all icons from the right to the end of the deck over one and slots the icon in between if there is a free space.

The way the moving works well you can see in the video it's not working well at all.

**Comment by rivafarabi** [comment]
Noted.

**Comment by Toploader** [comment]
Bumping this. It's the only thing that's stopping me from selling on my Streamdeck and using Deckboard exclusively, as it's next to impossible for me to arrange by buttons on each screen in the way I wish.

Great work on Deckboard overall :)

**Comment by rivafarabi** [comment]
Closing this, due to latest version 3 not using the same grid system
