### ISSUE TITLE
No Data in Slobs Audio Toggle

### ISSUE THREAD

**Issue by SheeshGaming420** [rivafarabi/deckboard#664]
![bug](https://user-images.githubusercontent.com/75099606/109542006-80398800-7a92-11eb-85a8-6b0461dabd8d.png)

**Comment by rivafarabi** [comment]
Thanks for the feedback. The bug has been fixed in [v1.9.87](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.87)
