### ISSUE TITLE
[BUG] The "Start" button doesn't work

### ISSUE THREAD

**Issue by enocvt** [rivafarabi/deckboard#665]
**Describe the bug**
The in-window mode doesn't work.
When I click on "Start"(for using the buttons directly from the Deckboard window) the Boards zone disappear, but the Buttons remain in Edit mode.

**To Reproduce**
1. In the main window, click on "Start"
2. The buttons remain in Ediit mode

**Expected behavior**
The buttons should look and function like in the mobile app, when pressed the actions activate.

**Server App**
 - OS: Windows 10 1909
 - Version 1.9.86

**Client App**
 - OS: Android 5
 - Version 1.9.80

[log.log](https://github.com/rivafarabi/deckboard/files/6081193/log.log)
[database.zip](https://github.com/rivafarabi/deckboard/files/6081195/database.zip)

**Additional context**
2 or 3 versions ago it worked perfectly, but since the last update this function broke.

**Comment by rivafarabi** [comment]
Thanks for the feedback. The bug has been fixed in [v1.9.87](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.87)
