### ISSUE TITLE
[BUG] Error with Soundpad extension

### ISSUE THREAD

**Issue by PingouinMaudit** [rivafarabi/deckboard#666]
I wanted to install the SoundPad extension but as soon as I restart Deckboard, I get a Javascript error.

"Uncaught Exception:
Error: connect ENOENT\\.\pipe\sp_remote_control
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)"

1. Install SoundPad extension
2. Restart Deckboard
3. See error

**Expected behavior**
I don't know but maybe it's due to my config.

![image](https://user-images.githubusercontent.com/80108585/110121436-ac207a80-7dbe-11eb-9fad-45a99f295542.png)

**Server App (please complete the following information):**
 - OS : Windows 10
 - Version : 1909
 - Operating system version : 18363.1379

**Client App (please complete the following information):**
 - OS: [e.g. Android 9]
 - Version [e.g. 1.9.60]

**Required files**

[Deckboard.zip](https://github.com/rivafarabi/deckboard/files/6090742/Deckboard.zip)

**Comment by PingouinMaudit** [comment]
The bug no longer exists since the last update.

**Comment by CladValentine** [comment]
I still have the bug.
