### ISSUE TITLE
[BUG] Macros doesn't works

### ISSUE THREAD

**Issue by dams333** [rivafarabi/deckboard#697]
I have created macros for my soundboard but they don't seem to work. To be sure, I added a macro to do CTRL + ALT + DEL and it doesn't work either. The bug is not due to my soundboard but to the fact that the macros do not run

Here is a picture of one of my macros (the key combination is correct):
https://prnt.sc/11amv4i

Server:
 - OS: Windows
 - Version 1.9.90

Client:
 - OS: Android
 - Version 1.9.80

File:
- [log.log](https://github.com/rivafarabi/deckboard/files/6297792/log.log)

**Comment by dblock110** [comment]
same problem! cant even send F5 to microsoft edge!

**Comment by dams333** [comment]
My issue is from 2021 and was fixed (I don't remember exactly but if I closed it, it was working). I invite you to make another issue and completing it to the maximum

**Comment by Eloren1** [comment]
Macros do not work at all. Even though media controls are fine.
