### ISSUE TITLE
Android Bug with buttons

### ISSUE THREAD

**Issue by KostisM900** [rivafarabi/deckboard#706]
I am dealing with a problem. I am a premium user. After the update the boards that I have designed 4x1 or 3x1 are zoomed in the app and I cant tap them.

![Screenshot_2021-04-18-17-56-26-145_com rivafarabi deckboard pro](https://user-images.githubusercontent.com/60107027/115150102-96fe6300-a06f-11eb-909e-c40c713c9159.png)

**Comment by rivafarabi** [comment]
Thanks for the info. It seems the bug only affected the boards that have a single row of buttons

**Comment by huzt02** [comment]
I have a similar problem with 5x3 grids

**Comment by Ceroden** [comment]
Yep, I get a similar issue on a 5x2 grid

**Comment by rivafarabi** [comment]
Thanks for the feedback. This bug has been fixed in client app version 1.9.93
