### ISSUE TITLE
[BUG] Board Switching not working

### ISSUE THREAD

**Issue by Audric1320** [rivafarabi/deckboard#707]
**Describe the bug
When I click on a button to switch board nothing happens

**Expected behavior
Switching boards

**Screenshots**

**Server device (please fill in the following information):**
- Windows 10 20H2
- Deckboard Server 1.9.92
- Deckboard Server 2.0.0 beta-1

**Client application (please fill in the following information):**.
- Android Xiaomi Mi8 Lite (Android 10QKQ1.190910.002) (MIUI 12.0.3)
- Deckboard App (pro) 1.9.91

[log.log](https://github.com/rivafarabi/deckboard/files/6331748/log.log)
[log.old.log](https://github.com/rivafarabi/deckboard/files/6331749/log.old.log)

[database.zip](https://github.com/rivafarabi/deckboard/files/6331752/database.zip)

**Comment by rivafarabi** [comment]
Thanks for the feedback. This bug has been fixed in client app version 1.9.93
