### ISSUE TITLE
Can't connect ("Not connected to local network.")

### ISSUE THREAD

**Issue by ijase94400** [rivafarabi/deckboard#71]
Hello,

I got the program yesterday, when I try to connect it tells me "Not connected to local network."
I have only one network, I don't have VPN, I allowed the rule on firewall (http://prntscr.com/lqc5he)
I tried everything, please help me.

Thanks,

**Comment by TAnthrax** [comment]
Are you getting any error popups when you launch deckboard?

**Comment by rivafarabi** [comment]
Solved in v1.2.642
