### ISSUE TITLE
[BUG] volume control OBS Studio

### ISSUE THREAD

**Issue by FFzOmega** [rivafarabi/deckboard#726]
sorry to bother but...when i try to decrease the volume it freezes on -16.6 db, i can icrease as much as i want but not decrease

i expect when i press the button to decrease the volume but just doesn't happen

i'm using version 1.9.94.

**Comment by rivafarabi** [comment]
Thanks for the info. Will look into it

**Comment by rivafarabi** [comment]
Fixed in [v1.9.95](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.95)
