### ISSUE TITLE
Ability to set background image instead of colour

### ISSUE THREAD

**Issue by nbs3000** [rivafarabi/deckboard#74]
Hi, it would be nice if we could set a background image to go behind the buttons. If there is a concern about the amount of data to sync, it could be limited to smaller tileable textures.

On a related topic, I can't get the background colour to appear on my Nexus 7. It shows when I set it on my PC but the background is always white on the Nexus 7. Is that a known issue?

**Comment by rivafarabi** [comment]
I absolutely that idea. Of course there will be size limitation for the image itself.
And thanks for pointing the bug. It seems only occur to default board on fresh installed desktop app, not the rest of the new created boards. I'm going to release the patch soon.

**Comment by nbs3000** [comment]
Confirmed that the background color works fine after creating a 2nd board!
