### ISSUE TITLE
does not connect to the network

### ISSUE THREAD

**Issue by henriqsena** [rivafarabi/deckboard#75]
![deckboar 1](https://user-images.githubusercontent.com/45789934/49973676-3a2d9380-ff1d-11e8-8134-89764b8d42cf.jpg)
![deckboar 2](https://user-images.githubusercontent.com/45789934/49973686-3d288400-ff1d-11e8-9e80-133f7996a841.jpg)

some problem prevents me from connecting, already tried everything, but the same problem still occurs, even allowing access to the network.

**Comment by rivafarabi** [comment]
What connection do you have? wireless or cabled LAN? Is there any connection listed on ipconfig through cmd?

**Comment by henriqsena** [comment]
@rivafarabi do not use any settings in CMD, and my connection is via cable.

**Comment by codingneko** [comment]
Same error here, Also connected via Ethernet, the error seems to be on the program itself, not the network because it doesn't even wait to show the macros to throw the error, the moment you open up Deckboard it just throws the error, presumably because it's trying to update on its own but can't. Also interesting, the phone does connect to the Deckboard app and the macros update on the phone but when you click them they do nothing.

**Comment by rivafarabi** [comment]
Ok, it appears that the error only occurs when using ethernet cable, not wireless lan. I'll put this on todo list for now.

**Comment by TAnthrax** [comment]
I'm getting the same error on Windows 10 LTSB build 1607 using an Intel l211 NIC. If there is any info I can contribute to help get this solved let me know!

**Comment by rivafarabi** [comment]
Solved in ver 1.2.642

**Comment by BlissNomad** [comment]
Im still having this same issue. i cannot find the solution

**Comment by felps18** [comment]
PRA QUEM TA TENDO ESSE PROBLEMA, APERTA A TECLA WINDOWS E A TECLA R, vai abrir um painelzinho pequeno, vc digita "CMD" sem as aspas, e vai abrir o teu promp de comand, nele vc digita "ipconfig" e ele vai listar alguns numeros, vc pega e copia o teu "endereco IPv4" deve ser algo tipo "10.0.0.141" ai vc vai no aplicativo instalado no celular e digita esse numero onde ta escrito "local IP Adress" e clica embaixo "connect via WLAN" ele vai conectar no aplicativo do teu pc, deu certo comigo > 20/06/2020
