### ISSUE TITLE
[BUG] Icon of Active/Inactive toggle (for OBS Control)

### ISSUE THREAD

**Issue by AnMin25** [rivafarabi/deckboard#761]
**Describe the bug**
On client app, the icon of inactive and active for toggling OBS control is the same even if i set them different

**To Reproduce**
1. Add a new button
2. Click on 'Action'
3. Select 'OBS STUDIO' -> 'Audio Source Control/Toggle Source'
4. Set different icon for inactive and active
5. Select 'Add'
6. On client app, toggle the button
7. See error

**Expected behavior**
The icon of that button will change according to the active/inactive state

**Screenshots**
![image](https://user-images.githubusercontent.com/89156119/129947054-456b5162-6f9c-4d88-af4e-e472a1d8482a.png)

**Server App:**
 - OS: [Windows]
 - Version [e.g. 1.9.96]

**Client App:**
 - OS: [Android 4.4.2]
 - Version [1.9.95]

**Additional context**
I haven't tried all OBS Control toggles

**Comment by rivafarabi** [comment]
Fixed in [v1.9.98](https://github.com/rivafarabi/deckboard/releases/tag/v1.9.98)
