### ISSUE TITLE
Ability to use PNG alpha channel (transparency) for button images

### ISSUE THREAD

**Issue by nbs3000** [rivafarabi/deckboard#77]
Hi,
I'd like to design my own button images, however I would like the buttons to be a different shape (e.g. round). I was hoping I could use PNG files with transparency, however Deckboard currently shows the transparent regions as black. It would be great if we could optionally use transparency for the buttons!

To make this work, it would also be necessary to turn off the drop-shadow effect around the square button tiles.

The "hit box" of the buttons could remain as a square.

**Comment by rivafarabi** [comment]
Love the idea. I'll put this on to do list for now.

**Comment by sheikmansoorg** [comment]
Hi,
In previous versions I used pngs and It used to paint the alpha with nice vibrant orange color, it looked good with the BG color. After almost 4 months I updated the app, now for pngs it is showing the alpha as black color, it doesn't go very well with the BG. Please add a feature to use PNGs and select BG color for buttons as well.

Besides, Hey amazing app, I totally love it.
Thanks.

**Comment by nbs3000** [comment]
Just for info, this is how I'm currently using Deckboard. As a workaround I've set the background for not (yet) having PNG transparency I've set the background to black, but it would be cool to put a carbon fiber texture in the background (see my other enhancement) and use PNGs with transparency to make round buttons.
![image](https://user-images.githubusercontent.com/28044056/50629334-09e17f80-0f34-11e9-8b38-56a3bab45f42.png)

**Comment by rivafarabi** [comment]
> Hi,
> In previous versions I used pngs and It used to paint the alpha with nice vibrant orange color, it looked good with the BG color. After almost 4 months I updated the app, now for pngs it is showing the alpha as black color, it doesn't go very well with the BG. Please add a feature to use PNGs and select BG color for buttons as well.
> 
> Besides, Hey amazing app, I totally love it.
> Thanks.

I'll put this as bug for now. Will fix this ASAP. thanks for the info

**Comment by rivafarabi** [comment]
New version 1.2.64 fix the transparency issue and now you can change button color as a bonus. 

enjoy 😁
