### ISSUE TITLE
[BUG] Error occurrs when I open "New Button" Dialog

### ISSUE THREAD

**Issue by sBurmester** [rivafarabi/deckboard#783]
**Describe the bug**
When I try to open the "NEW BUTTON" dialog an error occurrs. 

**To Reproduce**
1. Go to a board
2. Click a free tile
3. See the error

**Expected behavior**
No error oocurrs

**Screenshots**
![image](https://user-images.githubusercontent.com/13117013/136823294-cbff34ef-cdfe-4b79-825b-1ce410e22aeb.png)

**Server App (please complete the following information):**
 - OS: Windows
 - Version 10 (10.0.19043.1110)

**Client App (please complete the following information):**
 - OS: Android 11
 - Kernel-Version 4.14.190-perf+

**Required files**
- database.db [database.zip](https://github.com/rivafarabi/deckboard/files/7323974/database.zip)
- [log.log](https://github.com/rivafarabi/deckboard/files/7323979/log.log)

**Additional context**
-

**Comment by bean5** [comment]
I see a similar error on Windows 10 and on Ubuntu snapcraft version. A similar popup occurs on snapcraft version when editing a button and when creating a button.

**Comment by rivafarabi** [comment]
Certain module that caused that error has been taken out in version 3. Closing this.
