### ISSUE TITLE
Suggestion: 32-bit Windows client

### ISSUE THREAD

**Issue by DoctorGnario** [rivafarabi/deckboard#80]
I would love a windows based client app. I have a Microsoft Nextbook tablet and would like to run a client from that instead of an Android device.

**Comment by sayig18** [comment]
You could use an android emulator on your netbook for now

**Comment by T321us** [comment]
I agree. While an emulator works it is not quite as seamless. Having a Windows client would be amazing.

**Comment by tiagolo** [comment]
I agree too. A Windows Client would be great for when I don't want to unlock my phone for a quick action

**Comment by T321us** [comment]
I actually made a windows client a few months back. I could dust it off and distribute it if @rivafarabi has no objections.

It was not quite as polished as it should be but it worked.

**Comment by T321us** [comment]
Some examples of the Windows client I created: https://imgur.com/a/n3hBhVP. There are a few updates that need to be done but it works...

**Comment by rivafarabi** [comment]
> Some examples of the Windows client I created: https://imgur.com/a/n3hBhVP. There are a few updates that need to be done but it works...

Fantastic. and yeah sure, you can share it :)
