### ISSUE TITLE
Bypass Screen Timeout [Android]

### ISSUE THREAD

**Issue by b0tt3dk** [rivafarabi/deckboard#802]
Is it possible to make the app so it bypasses the screen timeout most tablets/phones have. 
It keep turning off my screen every 30 mins.

I know other apps can do it :)

Cheers. And thx for an awesome app

**Comment by hexandcube** [comment]
Deckboard settings on the phone > Turn on the "Keep screen wake up" option

**Comment by b0tt3dk** [comment]
wow i have completely missed that. tyvm.
