### ISSUE TITLE
I can't connect my phone to my PC

### ISSUE THREAD

**Issue by Gopinho** [rivafarabi/deckboard#814]
**Describe the bug**
Always i try to use my phone to connect to my pc it does't work

**To Reproduce**
1. Go to the app on the phone
2. Click on try to scan the "Wi-Fi" QR code
3. See error

**Expected behavior**
Connect my phone to my PC

**Server App (please complete the following information):**
 - OS: Windows 10
 - Version: 1.9.99

**Client App (please complete the following information):**
 - OS: Android 8 / Android 10
 - Version 1.9.981

**Comment by bean5** [comment]
Did you check your firewall settings? The app has a few instructions on this if you click around.
