### ISSUE TITLE
[FEATURE REQUEST] Better audio control

### ISSUE THREAD

**Issue by Clad-Valentine** [rivafarabi/deckboard#815]
**Is your feature request related to a problem? Please describe.**
Recently a great plug in allowed obs user to split the audio sources without using voicemeeter for a better audio control. But when I tried to use the deckboard to mute/unmute or increase/decrease audio of one of the specific source the only things I was able to select were Desktop Audio Device, Mic/Aux Audio Device aka the base on OBS.

**Describe the solution you'd like**
I would like to add button on the deckboard to interact directly with the audio sources in the audio mixer.

**Describe alternatives you've considered**
Continue to use Voicemeeter which come with less control and precision

**Additional context**
I send you a picture of what I would like to control with the possibility to add a deckboard button for each source
![Capture](https://user-images.githubusercontent.com/97226814/148370981-68ae722f-f67f-42c4-8060-3d058ab63cf7.PNG)

**Comment by MajuTo** [comment]
Hello, same here, would be really nice to have toggle on all audio source in audio mixer

**Comment by rivafarabi** [comment]
Version 3 has slider input for OBS audio control. Try it!
