### ISSUE TITLE
Click Twice, App not always respond (and Latency ?) [BUG]

### ISSUE THREAD

**Issue by Oblyat** [rivafarabi/deckboard#820]
When i use the app, it takes 1 or 2 second before te sound begin.
Many times, i need to click on the app (on my computer) for have the sound (like if app should be not active)
(i always have this trouble for 2 years ago)

**To Reproduce**
It's normal way, juste use a song in the app.

1 - create new button
2 - use "play audio"
3 - choose your sound (i use .wav sound)
4 - close the app (for do like when i turn on the app)
5 - turn on the app (don't click on the app window)
6 - i connect my app with wifi
7 - i use my phone for play music (not working)
8 - i click on my app (on my computer)
9 - i play again the song and it works (but i had to click 2 times)
10 - after ~20 minutes, i try to play a song again but i had to go again at n°8

**Expected behavior**
i expect my app don't need to be click ans have a lower latency (under 1 sec)

**Server App (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.19042

**Client App (please complete the following information):**
 - OS: Android
 - Version 6.0.1 and 11RKQ1.200826.002   (i tried with 2 different phones)
 
 
 
(i change database.db to database.log because github dont want .db file)
 
[log.log](https://github.com/rivafarabi/deckboard/files/7841904/log.log)
[database.log](https://github.com/rivafarabi/deckboard/files/7841907/database.log)

**Comment by Oblyat** [comment]
Finaly, the big problem is needing to click 2 times for have a sound, maybe not the latency.

**Comment by VIPKaiser** [comment]
Yes I also have this problem. You need to click audio buttons TWICE! It's highly irritating.

**Comment by VIPKaiser** [comment]
Is this even still being worked on? 2 years since last update? The extensions no longer work for example SoundPad extension just says it's never running so cannot be used. I bought the pro version of this and have recommended it to people. It's such a shame as it has the potential to be an amazing product!

**Comment by Oblyat** [comment]
> Yes I also have this problem. You need to click audio buttons TWICE! It's highly irritating.

Yes, i was a long time thinking it's a problem of latency but when i have write this issue i discover it's probably juste this problem (click twice)

**Comment by Oblyat** [comment]
> Is this even still being worked on? 2 years since last update? The extensions no longer work for example SoundPad extension just says it's never running so cannot be used. I bought the pro version of this and have recommended it to people. It's such a shame as it has the potential to be an amazing product!

I always have my app update, but i always have some trouble... And yes, i really love this app to, thath why i take tame to write on the github ^^

**Comment by Oblyat** [comment]
i have found a solution for the double click.
You can put this option in the program (like on the screen)
after that i have put a song button for play nothing, like this i can stop the sound if i make a mistake (of if i jus't want the begin of my song, i can stop it)
![image](https://user-images.githubusercontent.com/97478985/149631875-8b11e4d6-6fab-4c36-ad8c-ea166c42f2cb.png)

**Comment by Oblyat** [comment]
i have found a solution for the double click.
You can put this option in the program (like on the screen)
after that i have put a song button for play nothing, lik
![Sans titre-1](https://user-images.githubusercontent.com/97478985/149631884-a3362b67-4697-4f68-b265-da373fd4be5f.png)
e this i can stop the sound if i make a mistake (of if i jus't want the begin of my song, i can stop it)

**Comment by Oblyat** [comment]
for stop the sound, i put a .png in te "audio file"
![image](https://user-images.githubusercontent.com/97478985/149631989-e5c3cd35-98c7-4fc1-a22c-baa66e4e6932.png)

**Comment by Oblyat** [comment]
Now i will look if the second problem is resolve :
...
8 - i click on my app (on my computer)
9 - i play again the song and it works (but i had to click 2 times)
10 - after ~20 minutes, i try to play a song again but i had to go again at n°8

**Comment by VIPKaiser** [comment]
Thanks! That worked for me, no more having to double tap the button for sounds! It's a shame the developer doesn't appear to be doing anything with this anymore. There are lots of updates needed.

**Comment by Oblyat** [comment]
For today, it look like my second problem (app stop working after ~20 minutes) should be resolved.
I already have my app on "run as administrator" i don't know if it help but now my app works so, it's fine for me.
