### ISSUE TITLE
Account Logins don't work

### ISSUE THREAD

**Issue by schousda** [rivafarabi/deckboard#829]
**Describe the bug**
I can't log in to any of Twitter, Twitch or Spotify.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Acconts'
3. Click on 'Spotify' or 'Twitch'
4. See error:
503 Server Error
Error: Server Error
The service you requested is not available at this time.
Service error -27.

5. Click on 'Twitter'
6. Nothing happens

**Expected behavior**
I should be able to add my credentials for the login

**Server App (please complete the following information):**
 - OS: Windows 11
 - Version 2.0.0 beta 2

**Comment by Jmasilva** [comment]
On windows 10 app version 1.9.99, i can log on twitch however when i try to log in on spotify the credentials window just pop up and then closes itself after a second.
