### ISSUE TITLE
[BUG] Server uninstallable on Linux PopOS 21.10

### ISSUE THREAD

**Issue by LeeReitz** [rivafarabi/deckboard#853]
**Describe the bug**
Unable to install from deb.
```
dpkg: dependency problems prevent configuration of deckboard:
 deckboard depends on libnode64; however:
  Package libnode64 is not installed.
 deckboard depends on libicu66; however:
  Package libicu66 is not installed.
```

libnode64 is replaced with libnode72 in 21.10 repos
I believe libicu66 is replaced with libicu67 in 21.10 repos

**To Reproduce**
1. `sudo dpkg -i deckboard_2.0.1_amd64.deb`

**Server App (please complete the following information):**
 - OS: Linux PopOS (Ubuntu based OS)
 - Version 21.10

**Comment by Yowlen** [comment]
Can confirm this is also an issue in Ubuntu's latest LTS release, 22.04, and its derivatives. Except while 22.04 uses libnode72, it's using libicu70 instead of 66/67.

**Comment by maximoosemine** [comment]
I had the same dependency issues as described above on Pop!_OS 22.04 LTS. This issue should be fixed, but here's the workaround I used in the meantime. Ignore security warnings at your own risk.

Basically, we need to install the missing dependencies manually.

First, add the following to `/etc/apt/sources.list`:
```
deb http://security.debian.org/debian-security buster/updates main
deb http://security.ubuntu.com/ubuntu focal-security main
```
Next, run `sudo apt update --allow-insecure-repositories`, then run `sudo apt install libnode64 libicu66`.
Just to make sure things are working, run `sudo apt --fix-broken install`

Next install Deckboard using `sudo dpkg -i <deb path here>`
