### ISSUE TITLE
[BUG] I need help to fix programs not showing up on "Run Programs" on the Actions Button?

### ISSUE THREAD

**Issue by Praisegames** [rivafarabi/deckboard#856]
**Describe the bug**
 "Run Programs" on the Actions Button? Does not work for me on ZorinOS 16.1 (Ubuntu Base)

**To Reproduce**
I didn't do anything.

**Expected behavior**
Actions Button to Choose the Action you want for example Run Programs Does not show anything in the list

**Screenshots**
![1  Errors](https://user-images.githubusercontent.com/81829126/169179322-c9f47fc1-795b-4dff-89cf-4af1efb49908.png)
![2  Actions](https://user-images.githubusercontent.com/81829126/169179325-cbe35dae-6485-4e20-ba4c-c0e871ae8772.png)

**Client App (please complete the following information):**
 - OS: ZorinOS 16.1 (Ubuntu Base)
 - Version 2.0.1

**Required files**
[Database - Log.zip](https://github.com/rivafarabi/deckboard/files/8721867/Database.-.Log.zip)

**Comment by IAmSegfault** [comment]
I had this same issue when using the snap based version. Using either the .deb version or the appimage will fix it.
