### ISSUE TITLE
[BUG] - Sort Board in app.

### ISSUE THREAD

**Issue by AudricSan** [rivafarabi/deckboard#859]
**Describe the bug**
I can give an order to all my boards, but each time I edit or add a new board, the order is completely changed.

**RESOLVE**
to correct the bug, I went into the database saved as a .DB file on my computer.
And I changed the type of the column "sort" from "varchar" to "integrate".

![image](https://user-images.githubusercontent.com/29382102/170529522-cef6b426-ed2a-4b4e-a659-b1f6ba191590.png)

**Comment by AudricSan** [comment]
Après quelques tests le fait de mettre la ligne en INTGER empêche l'application mobile de se charger correctement..
Je suis donc repassé sur un format varchar avec des nombres à 3 chiffres.

![image](https://user-images.githubusercontent.com/29382102/171698256-354a12bf-1fa5-415c-8627-978761929540.png)

**Comment by AudricSan** [comment]
Ce qui a permis de résoudre le problème de tri.

--> je me demande donc s'il ne serait pas plus facile de passer la colonne en intégré et de la rendre compatible avec l'application mobile.. ??

**Comment by rivafarabi** [comment]
Thanks for the info. You can check out the latest release [v2.0.2](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.2)

The new release is using a new column "order" to sort the boards. Will remove the "sort" column completely on the next release.

**Comment by AudricSan** [comment]
thank you !
