### ISSUE TITLE
Multiple actions per button

### ISSUE THREAD

**Issue by Azzurite** [rivafarabi/deckboard#86]
It would be nice to be able to define multiple actions happening on a single button press.

**Mockups:**

Button with a single action currently, note the added + button
![1](https://user-images.githubusercontent.com/2777158/50480466-64cb2200-09dc-11e9-98ae-73d408a892fb.png)

After clicking the +, two actions can be defined. Actions are scrollable.
![2](https://user-images.githubusercontent.com/2777158/50480506-9348fd00-09dc-11e9-8b1b-13e078afa571.png)

I just bought the pro app, thanks for making this app!

**Comment by aqQnm0** [comment]
That would be a great feature! 

PS. Just bought the Pro App after seeing that Twitch Integration is coming. With that and multi-action buttons this app would be the ultimate Streamdeck killer @Rivafarabi

**Comment by Yurlyn** [comment]
The program Touch Portal has this plus it can add delay between the actions too. TP just doesn't look as nice as Deckboard and is also more restrictive. It does have a few features a lot of other solutions, including Elgato's Streamdeck, lack such as global configurable grid.

If Deckboard gets multiple actions per button and configurable grid per page (I saw something like that is already on its way in the next update or at least half of February) it will be definitely an app that can get rid of all its (overpriced) competitors. I actually bought a tablet for this (and MacroDeck, but I stopped using that one) so I don't have to use my phone anymore. It was 80 euro and has more features than Elgato's pricey product. Keep it up with Deckboard <3

**Comment by digitalfiz** [comment]
Yes it would be nice to be able to hit a single button to do things like mute mic and hide camera or switch scenes and start a playlist on spotify for instance your stream is starting scene and a playlist for stream starter music. This could be a very useful feature.

**Comment by Frensiow** [comment]
Yes that would be an amazing feature!

**Comment by mix3d** [comment]
Isn't this already done now with multi action buttons?
