### ISSUE TITLE
[BUG] When copying/exporting the board with high (~>50) number of buttons the resulting board is empty

### ISSUE THREAD

**Issue by woodmin** [rivafarabi/deckboard#863]
When copying/exporting the board with high (~>50) number of buttons the resulting board is empty.

1. Create 15 x 9 board
2. Fill with buttons
3. Copy or export/import
4. See result - empty board

Expected behavior - proper copy of the board with all buttons.

OS: Windows 10
Deckboard Version 2.0.1

**Comment by rivafarabi** [comment]
Can you provide the log.log file? (located in C:\Users\USER\AppData\Roaming\Deckboard)

**Comment by woodmin** [comment]
Just duplicated the board and result came out empty. See log attached.
[log.log](https://github.com/rivafarabi/deckboard/files/8832594/log.log)

**Comment by rivafarabi** [comment]
Thanks for the info. The bug should be fixed in the latest release [v2.0.2](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.2)
