### ISSUE TITLE
spotify login

### ISSUE THREAD

**Issue by Yayayas** [rivafarabi/deckboard#870]
I have login to spotify but it doesn´t connetect to app and if Itry again, only appears a white window and in a few seconds it close

**To Reproduce**
1. Go to 'setting.'
2. Click on 'accounts'
3. Fill a value to 'login'

**Screenshots**
![Deckboard_20220628113816](https://user-images.githubusercontent.com/39446709/176169790-0d3ad03b-4eec-4677-ab93-df0c7edaf1a0.png)

**Server App (please complete the following information):**
 - OS: 10
 - Version 2.0.2

**Comment by rivafarabi** [comment]
Login dialog has been fixed in auth server side
