### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Kruge** [rivafarabi/deckboard#873]
A section of the screen is a black or flashing box in landscape mode. Box size seems to have a width of screen width - screen height.

Landscape works as expected. But opening the setting menus forces landscape and cause the screen glitch, tile, and flash.

Issue started upon updating to version 2.0.0, and is effecting multiple tablets.

Client App: 2.0.0
OS: Lineage 19 (Android 12)

![Screenshot_20220711-223918_Deckboard PRO](https://user-images.githubusercontent.com/4617913/178397790-67ee7a1c-abbb-4684-bf4e-1c75d9663a12.png)

![Screenshot_20220711-223947_Deckboard PRO](https://user-images.githubusercontent.com/4617913/178397799-fb3dc497-8782-441c-ab3e-670ae83f76e5.png)

**Comment by rivafarabi** [comment]
Hi. Sorry for the experience. Do you mind sharing the screen capture video
for me to analyze?

Thank you

**Comment by Kruge** [comment]
2.0.1 has fixed all the issue. Thank you!
