### ISSUE TITLE
[BUG] Changing Spotify accounts

### ISSUE THREAD

**Issue by OhCrunchyBacon** [rivafarabi/deckboard#877]
**Describe the bug**
I logged into one of two of my Spotify accounts. one using free one is paid. I want to switch from my free account to my paid account but when i logout and try to login to my other account it automatically logs me back into the free Spotify account.

**Expected behavior**
To be able to change Spotify accounts.

**Server App (please complete the following information):**
 - OS: Windows 10
 - Version 2.0.2

**Client App (please complete the following information):**
 - OS: Samsumg Tab A
 - Version 2.0.1

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

**Comment by Alexmagbrot** [comment]
yes, it happends to me too
