### ISSUE TITLE
[BUG] Import is not loading file

### ISSUE THREAD

**Issue by HeroLeam** [rivafarabi/deckboard#880]
**Describe the bug**
I import a file, but nothing happens, I click the import button several times and it stays the same, it doesn't go any further.

**To Reproduce**
1. Go to Settings
2. Click on Export / Import Boards
3. I click import
4. I select the file
5. Select the option "all boards"
6. Finally click on the import button
7. It does not report any errors, simply nothing happens.

**Screenshots**

**Server App (please complete the following information):**
 - OS: Windows
 - Version 2.0.2

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`) no have
![image](https://user-images.githubusercontent.com/92167805/181396466-dd4cb79c-7f4d-4606-8679-5762a8c7229e.png)

- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

[log.log](https://github.com/rivafarabi/deckboard/files/9204390/log.log)

https://user-images.githubusercontent.com/92167805/181396642-d423b78f-7d66-476f-844d-b441a15380ba.mp4

**Comment by MrDakCol** [comment]
Have the issue here too. Cant import a Board froma JsonFile

**Comment by rivafarabi** [comment]
This issue has already been fixed in version [2.0.3](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.3)
