### ISSUE TITLE
Print Screen Key Macro Support [FEATURE REQUEST]

### ISSUE THREAD

**Issue by Cardinal-23** [rivafarabi/deckboard#882]
I am trying to use a macro to control my ShareX shortcuts, but the keyboard macro option doesn't support using the print screen key, which would be needed for a number of shortcuts

**Comment by rivafarabi** [comment]
The PRINTSCREEN keypress support has been added in version [2.0.4](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.4)
