### ISSUE TITLE
[FEATURE REQUEST] Let rotate 180 degree

### ISSUE THREAD

**Issue by Shirobachi** [rivafarabi/deckboard#884]
**Is your feature request related to a problem? Please describe.**
Hey, I have old phone what is always connected to changing cable and deckboard run non-stop. Unfortunately changing port in on the bottom. Would be possible to add feature what will let me rotate buttons 180 degrees?

**Describe the solution you'd like**
Let add to setting new button sth like rotate 180 degree. When on whole app would be rotated

Thanks for your product it's already great and can be even better :))

**Comment by Shirobachi** [comment]
I see it's possible now, so I close the issue, thanks a lot! <3

**Comment by rivafarabi** [comment]
Hope you like it
