### ISSUE TITLE
Unable to conect to OBS 28

### ISSUE THREAD

**Issue by lendechy** [rivafarabi/deckboard#887]
Right now deckboard can´t be connected to OBS 28 beta, probably cuz new integrated web-socket.

**Comment by Delirya** [comment]
I've noticed this too. Tried tweaking port/IP settings but it didnt help

**Comment by Donzii** [comment]
different OBS websocket versions. OBS v28 have a new socket-version
see: https://github.com/obsproject/obs-websocket#client-software

**Comment by rivafarabi** [comment]
OBS v28 support is halfway done. Estimated this weekend as beta release.

**Comment by rivafarabi** [comment]
Just released [2.0.5-rc2](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.5-rc2).

Keep in mind that in this release deprecate OBS v27+Websocket plugin v4.9 support in favor of OBS v28 integrated websocket plugin.

Waiting for your feedbacks

**Comment by JasonSD24** [comment]
Hi @rivafarabi

I just installed the 2.0.5-rc2 version, and it's working perfect in my side. 

Thanks for the quick resolution of this!

**Comment by Gavark** [comment]
Works for me. Thanks !

**Comment by Delirya** [comment]
Working for me, too. Thank you for updating it so fast!

**Comment by PtrpanBR** [comment]
Working version, thank you very much.

**Comment by rivafarabi** [comment]
The update for OBS will be added in stable release around the end of this month. I am closing this issue. Thank you all for the feedback.
