### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jakeyboii111** [rivafarabi/deckboard#889]
**Describe the bug**
When pressing discord buttons they do not work

**To Reproduce**
3. Fill a value to '...'

**Expected behavior**

**Screenshots**

**Server App (please complete the following information):**
 - OS: Windows
 - Version 2.0.4

**Client App (please complete the following information):**
 - OS: iPhone IOS 15.6
 - Version: ?

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

**Additional context**
The discord buttons don't work when i press them, have i missed a step to connect the app to discord?

**Comment by Yurlyn** [comment]
You'll have to log in on the Discord developer website and make a new app/whatever they call it. Once you've done that you can link the Deckboard Discord plugin to your Discord through the developer page (copy some tokens from the page into the plugin).

I believe the plugin has a link to its github page explaining it. Not sure.

**Comment by jakeyboii111** [comment]
Hey man,
Thanks so much, I watched a youtube video on how to do it, and it worked.
Thanks anyways.

Jake

**Comment by jakeyboii111** [comment]
> You'll have to log in on the Discord developer website and make a new app/whatever they call it. Once you've done that you can link the Deckboard Discord plugin to your Discord through the developer page (copy some tokens from the page into the plugin).
> 
> I believe the plugin has a link to its github page explaining it. Not sure.


Actually do you think you could do a walkthrough. I just removed the thing from discord dev web and i now forgot how to link it again. i have gone through everything. i now cannot find the video again now either so im stuck.

**Comment by Yurlyn** [comment]
Here is the GitHub for it: https://github.com/aislandener/discord-deckboard .

Basically, you need to go to your Discord Developer page here: https://discord.com/developers/applications and make a new application (top right next to your avatar once you've logged into the page).
![image](https://user-images.githubusercontent.com/42919979/188289300-cca33f2f-1df7-4157-87ca-bcbb57488088.png)

Once its made you'll end up in the application's settings page (click on it under "My Applications" if not). Click the OAuth2 page on the left (1) and add a new redirect (2) and copy the Client ID (3):
![image](https://user-images.githubusercontent.com/42919979/188289462-f36f1792-a4cb-42b5-b8c2-7f1aaf2214e1.png)

Keep this page open and switch over to Deckboard and go to Settings -> Extensions -> Configs and Discord Deckboard will be there if installed ((re)install it if it's not there). Paste the "Client ID" you copied from the web page above into the Client ID text area in Deckboard and click Save on the bottom right but don't click away the settings:
![image](https://user-images.githubusercontent.com/42919979/188289494-985ca6f4-dbd6-40ce-889a-e9b5ac78ce36.png)

Then go back to the webpage and copy the Client Secret. If you can't see it click on "Reset Secret". Then copy that into Deckboard where it says "Client Secret (not distribute)". Also, never share this with anyone! Once again hit save and restart Deckboard while you have the Discord app open on your system.

Once Deckboard has reopened Discord will prompt you to authorize the API. Do so and once you've done it an access token will be shown in a pop up in Discord. Copy this code by clicking on "Copy".

Then in Deckboard go back to Settings -> Extensions -> Configs and paste your copied code into "Access Token (not distribute)". Again, don't share this code with anyone! Hit save and your all set up and you can now use the Discord Deckboard extension.

**Comment by jakeyboii111** [comment]
Awesome, thanks!

**Comment by rivafarabi** [comment]
The built-in Discord integration is available in version [v2.0.5-rc3](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.5-rc3).

More macros coming soon.

**Comment by NirokTwitch** [comment]
![image](https://user-images.githubusercontent.com/62898758/203154595-2d10bbc3-4247-43d8-8c31-fe6e2a5e5056.png)
hello, I have another problem I have nothing in my "config" window yet I have the plugin installed how can I do?

**Comment by NirokTwitch** [comment]
![image](https://user-images.githubusercontent.com/62898758/203154804-8ad95590-7466-463f-b889-c38584b8caca.png)
