### ISSUE TITLE
[BUG] OBS wont connect

### ISSUE THREAD

**Issue by Nickinatorz** [rivafarabi/deckboard#892]
OBS wont connect, I've set everything up as the documentation said.
The error message 'OBS disconnected' will pop up every second. No way to connect OBS whatever port im trying.
Just using IP 127.0.0.1, also tried using the public IP, but that doesnt work either.

**Screenshots**
![image](https://user-images.githubusercontent.com/111529997/185463357-bd3b4344-1afb-45da-ba01-d0de1630313c.png)
![image](https://user-images.githubusercontent.com/111529997/185463388-6279c1c9-e355-43ea-be2c-ad54c0a6ff23.png)
![image](https://user-images.githubusercontent.com/111529997/185463411-f4e03641-41e9-41ba-9fe0-7c2ec8f5883d.png)

**Server App (please complete the following information):**
 - OS: Windows
 - Version 2.0.4

**Client App (please complete the following information):**
 - OS: iOS 15

**Required files**
- database.db
wont upload is not supported by Git.

- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)
[log.log](https://github.com/rivafarabi/deckboard/files/9376384/log.log)

**Comment by rivafarabi** [comment]
May I know which version of OBS and OBS websocket plugin are you using
right now?

**Comment by Nickinatorz** [comment]
> 

Sure!
OBS: v27.2.4
Websocket: v5.0.1

**Comment by Nickinatorz** [comment]
> Sure! OBS: v27.2.4 Websocket: v5.0.1

Nvm, that was the issue, didnt see that websocket 5.0.1 uses different method.
Downgraded to v.4.9 and that fixed the issue, its connecting now.

**Comment by Reyhans13** [comment]
Ah, now I know what was the issue. Thanks for the downgrade tips.
