### ISSUE TITLE
[BUG] Rendering Problem Has Returned.

### ISSUE THREAD

**Issue by Kruge** [rivafarabi/deckboard#893]
**Describe the bug**
The rendering bug as described in [Bug #873 ](https://github.com/rivafarabi/deckboard/issues/873) has returned in app version 2.0.2. 

A section of the screen is a black or flashing box in landscape mode. Box size seems to have a width of screen width - screen height.

Portrait works as expected. But opening the setting menus forces landscape and cause the screen glitch, tiling, and flashing.

Only tested on one tablet this time. Please let me know if any other information would be useful.

**Client App:**
Client App: 2.0.2
OS: Lineage 19 (Android 12)
![Screenshot_20220818-152907_Deckboard PRO](https://user-images.githubusercontent.com/4617913/185478882-1cc5c6d2-dbec-471a-a8c1-f76c7f634e99.png)
![Screenshot_20220818-152847_Deckboard PRO](https://user-images.githubusercontent.com/4617913/185478892-e16df93a-7209-45b7-ab37-7298718a995f.png)

**Comment by rivafarabi** [comment]
After some deep investigation, it seems this bug only appears on devices
that use Lineage OS.

Will fix it as soon as possible.

Thank you for the info

**Comment by rivafarabi** [comment]
Version 2.0.3 has just released on Google Play Store. It should fix the
issue above. Let me know if the issue persists.

**Comment by Kruge** [comment]
Thank you for the fast fix! 2.0.3 does fix the issue.
