### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 1noken1** [rivafarabi/deckboard#897]
Describe the bug
I i can't connect deckboard with obs. It just logs out all the time

** To Reproduce**

I try to connect deckboard to obs (27.2.4 -64 bit) and I get a red label that says: obs studio disconnected.
I've tried different websocket ports (4444, 4445, 4455) and it doesn't work, I don't know what I'm doing wrong. i also tried websocket 4.9.1 and 5.0.1

Screenshots
It just shows "obs studio disconnected."

Server App (please complete the following information):

OS: Windows 10 pro
Version 2.0.4
Client App (please complete the following information):

OS: iOS
Version: iOS 15.6.1

**Comment by rivafarabi** [comment]
What version of OBS are you using?

**Comment by 1noken1** [comment]
v. 27.2.4 . now i try again port 4455 and it seems to work but i cant connect it to ipad

**Comment by rivafarabi** [comment]
For the connection issue, have you tried all the instructions in this page
<https://github.com/rivafarabi/deckboard/wiki/Troubleshoot>?

**Comment by 1noken1** [comment]
yes. I have all like that. Im using the port 4455. the deckboard in firewall is allowed. I have to install ADB if I'm using iOS (iPad or iPhone)

**Comment by GAMINGPUG2121** [comment]
Same issue here. Is there any information on when it's going to be fixed? Also, Slobs connects just fine. For me at least.

**Comment by AverageDood** [comment]
I can confirm this exact same issue happens with OBS V28, now that OBS WebSockets has been integrated into the program. Deckboard is simply spamming disconnection messages. Tried both ports 4444 and 4455

**Comment by rivafarabi** [comment]
This will be next month's priority. For the time being, you can use OBS v27
and Websocket plugin v4.9.0

**Comment by rivafarabi** [comment]
Just released [2.0.5-rc2](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.5-rc2). 

Keep in mind that in this release deprecate OBS v27+Websocket plugin v4.9 support in favor of OBS v28 integrated websocket plugin.

Waiting for your feedbacks.

**Comment by AverageDood** [comment]
The RC you just published has connected to OBS instantly and without a problem

**Comment by rivafarabi** [comment]
The update for OBS will be added in stable release around the end of this month. I am closing this issue. Thank you
