### ISSUE TITLE
[FEATURE REQUEST] See when a filter is on/off on an audio filter

### ISSUE THREAD

**Issue by GuitoonDev** [rivafarabi/deckboard#899]
Currently, when I toggle an audio filter on my microphone (like a reverb effect), I can't see if it's enabled or not in the UI of the app. This behaviour is already available for enabled current state with scenes or visibility element in a scene.
But sometimes, I forgot I enable a filter on my mic and I have no feedback for that (I can't listen my mic because of the audio delay on OBS and I don't have money for a GO XLR).

It would be very nice, to see the current activation state of an audio filter for an audio source (or for any other filter by the way).

**Comment by rivafarabi** [comment]
Sorry it took me so long. The feature available in [v2.0.5-rc1](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.5-rc2) as release candidate/beta and client version v2.0.4
