### ISSUE TITLE
Background button

### ISSUE THREAD

**Issue by graph-kgrondin** [rivafarabi/deckboard#9]
We actually can change text color and text background, but not the button background itself.

**Comment by rivafarabi** [comment]
The reason I chose not to have background color customization is to reduce the size of the data synced  to the device and process the device should handle for each buttons. But I'll reconsider this in the near future.

**Comment by Revenger** [comment]
What can be done with this is have a transparent text background that one could set the opacity.
I was looking for something like this as the text is white and the default icon of the keyboard is white so background on the text with adjusted opacity would help.
