### ISSUE TITLE
Error "Advance Keyboard Macro" and other

### ISSUE THREAD

**Issue by UnisonRU** [rivafarabi/deckboard#90]
Error "Advance Keyboard Macro".

Screenshots:

https://cdn1.savepice.ru/uploads/2019/1/5/87ad7781a414b682f7370b3af12bec93-full.png
https://cdn1.savepice.ru/uploads/2019/1/5/b9c125c03dbf5e6566b0f86b374d7458-full.png
https://cdn1.savepice.ru/uploads/2019/1/5/986b442a5cdc2a53b60c4d254688966c-full.png

Add the ability to turn on and off the microphone.

**Comment by soifased** [comment]
![WhatsApp Image 2019-05-10 at 09 52 33](https://user-images.githubusercontent.com/50482177/57528875-d65f9900-7309-11e9-94c6-4908efc77900.jpeg)

**Comment by rivafarabi** [comment]
Thanks for the info. I will look into it. By the way, is your keyboard macro has any delay included?

**Comment by soifased** [comment]
Yes. Delay 100 ms.

at the end of the line also needed the "enter" to end the command.

The macro makes the command to press the "y" key (which enables the game
command prompt), delay of 100ms and the command " /channel 1" fired with
(enter).

Em sex, 10 de mai de 2019 14:59, Riva Farabi <notifications@github.com>
escreveu:

**Comment by rivafarabi** [comment]
version 1.4.1 has just been released. It fix the issue for "type text" action inside Advance Keyboard press action, the cause for this error.
