### ISSUE TITLE
[BUG] Deckboard not quitting properly in Linux

### ISSUE THREAD

**Issue by Yowlen** [rivafarabi/deckboard#900]
**Describe the bug**
Deckboard refuses to close properly when quitting via the taskbar icon's menu.

**To Reproduce**
1. Open up Deckboard.
2. Click the system tray icon and select "Quit"
3. Deckboard will refuse to exit from the system tray.

**Server App (please complete the following information):**
 - OS: Ubuntu 20.04 and 22.04 (Tested on both)
 - Version 2.0.2 and 2.0.4 (tested both `.deb` (Ubuntu 20.04) and `.AppImage` (20.04 and 22.04) installation methods)

**Client App (please complete the following information):**
N/A (bug affects server no matter the connected clients)

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)
Uhh, no idea where to get the logs for Linux. Sorry.

**Additional context**
Interestingly, when testing the AppImage format, the hangup would only occur when the relevant `libnodeXX` package for the distro was installed. For Ubuntu 22.04, `libnode72` wasn't installed by default for me, and so Deckboard quit just fine when used via AppImage, but when I installed that package, Deckboard exhibited the behavior again just like before with `libnode64` in Ubuntu 20.04.

Edit: It might not be as related as I thought. I hadn't reinstalled libnode but it still hung on exit this time.

**Comment by sebahhh** [comment]
I have exactly the same bug in Pop OS 22.04 using AppImage.

If you try to open another instance, it works OK and close as expected. It seems to happen only in the first launch.
