### ISSUE TITLE
Unable to Connect to obs studio v28

### ISSUE THREAD

**Issue by HugoPod** [rivafarabi/deckboard#904]
I've already download the 2.0.5-rc2 however it still doesnt work

**Comment by rivafarabi** [comment]
Did you make sure the IP address and password (if applicable) match the settings on the OBS?

**Comment by edusaraivac** [comment]
Hi! Same here. Had an update today of OBS to version 28.0.1 and can't connect with deckboard. IP address, port and password are matching. I'm using deckboard 2.0.4.

**Comment by Saxostevesaxo** [comment]
Hi, im getting same issue, updated to OBS 28.0.1 and it wont connect.

**Comment by HugoPod** [comment]
> Did you make sure the IP address and password (if applicable) match the settings on the OBS?
Yes I did make sure

**Comment by LinuxGamesTV** [comment]
You need Websocket plugin 4x Cpmpat
