### ISSUE TITLE
[BUG] Discord integration not properly logging in 

### ISSUE THREAD

**Issue by CelestialKitsune** [rivafarabi/deckboard#905]
**Describe the bug**
Connecting your Discord account results in a blank page and the login process is never properly finished

**To Reproduce**
1. Go to `Settings > Accounts`
2. Click on Login in for the Discord account
3. Enter your credentials
4. Authorize Deckboard to access your Discord account
5. Observe what happens after the automatic redirection to localhost:3000

**Expected behavior**
The authorization page to properly close and to actually allow Deckboard to interact with my Discord account

**Videos**

https://user-images.githubusercontent.com/30158363/190913875-d2ab321a-f774-483b-b1f3-f34d855f4d39.mp4

**Server App (please complete the following information):**
 - OS: Windows 10
 - Version 2.0.5-rc3

**Requires files**
[database.zip](https://github.com/rivafarabi/deckboard/files/9594249/database.zip)
[log.log](https://github.com/rivafarabi/deckboard/files/9594250/log.log)

**Comment by rivafarabi** [comment]
Thanks for the information. I've just fixed the authentication scope issue
as stated in the log file. Please try again and let me know.

**Comment by Celestial-Panda** [comment]
I've just tried and unfortunately the same issue happens. Same error in the log file as well.
```
[2022-09-18 17:32:42.757] [error] discord:auth Error: Error response: invalid_scope
    at new t (D:\Applications\DeckBoard\resources\app.asar\dist\main\index.js:1:137657)
    at D:\Applications\DeckBoard\resources\app.asar\dist\main\index.js:1:32838
    at D:\Applications\DeckBoard\resources\app.asar\dist\main\index.js:1:31693
    at Object.next (D:\Applications\DeckBoard\resources\app.asar\dist\main\index.js:1:31798)
    at i (D:\Applications\DeckBoard\resources\app.asar\dist\main\index.js:1:30504)
```

**Comment by ChmielON** [comment]
I have the exact same error and problem with connecting to Twitch.

**Comment by Dlay2017** [comment]
Same here.. please resolve.. i just bought the pro app for android and i am not able to use it in any way.. :-(
