### ISSUE TITLE
[BUG] Discord, Spotify and Twitch connection problem

### ISSUE THREAD

**Issue by ChmielON** [rivafarabi/deckboard#907]
Problem connecting to Twitch. I enter the password and login to twitch and he gets info that something went wrong. Password and username are correct.

https://user-images.githubusercontent.com/114238689/192004817-b3f7b01b-fc11-4936-9bf9-b3b92848219f.mp4

Similar problem with Spotify. After attempting to connect, the window disappears and Spotyfi is not connected.

https://user-images.githubusercontent.com/114238689/192005651-83246475-a5bd-461a-a42a-7f8283605d4d.mp4

Could not connect Discord. After attempting to authorize, a white window appears.

https://user-images.githubusercontent.com/114238689/192006867-c6a35d09-9455-4330-9ffe-98ab62603911.mp4

Discord - 2.0.5-rc3
Windows 11

**Comment by jehfersom93** [comment]
On opera i have the same problem.. so i find this if help..

Small workaround:

Open opera://browserjs
Press "Disable browser.js..."
Login

**Comment by 0xShutdown** [comment]
I have the same problem!

**Comment by 0xShutdown** [comment]
[log.log](https://github.com/rivafarabi/deckboard/files/9676164/log.log)

**Comment by ChmielON** [comment]
> Do you mind sending me the log.log file? It is located in `C:\Users\USER\AppData\Roaming\Deckboard`

[log.log](https://github.com/rivafarabi/deckboard/files/9677081/log.log)

**Comment by longopy** [comment]
I have the same problem with Spotify
