### ISSUE TITLE
Java Local Network Issue &  Spotify Problem

### ISSUE THREAD

**Issue by TheManiacHS** [rivafarabi/deckboard#91]
![deckboard fehler](https://user-images.githubusercontent.com/46262798/50713180-5502ac00-1074-11e9-9e2f-02199ac0d2b0.JPG)
!!2 Problems in 1 thread because they may be related!!
Hellou :)
First things First....Absolutely GREAT Programm...bought the Pro Version.

Now to my Problem:
-I got the Java Issue with the Local Network (see Screenshot)
-Spotify Icons are doing Nothing , Account Connected.

PC runs on newest Win10, connected VIA LAN-Cable.
Specs:
-Intel Core i7 8700k @OC
-16GB DDR4 3000 CL15
-ASUS ROG Maximus X Hero
-Samsung 850 EVO 250GB
-ASUS Strix GTX 1080

Probs again 4 the Program
Greetz from Germany
TheManiacHS.

**Comment by rivafarabi** [comment]
It seems there's an issue where the app can't detect network from cable connection. 

For development purpose, can you run ipconfig on command prompt and see the listed. network interface? Is eth0 is the only network interface listed?

**Comment by rivafarabi** [comment]
IP address issue solved in ver 1.2.642
