### ISSUE TITLE
OBS 28 [BUG]

### ISSUE THREAD

**Issue by NightmareShark** [rivafarabi/deckboard#910]
The OBS Thing is not working with OBS 28 Version

**Comment by DeltaAlpha0** [comment]
Download Beta version 2.0.5-rc3

**Comment by ChmielON** [comment]
Download Web Socket from https://obsproject.com/forum/resources/obs-websocket-remote-control-obs-studio-using-websockets.466/
Dont instal  Deckboard beta 2.0.5

**Comment by PlanetOfCoding-real** [comment]
But Websocket is Pre-Installed? And it dont work to install other versions?

**Comment by ChmielON** [comment]
I know, but it doesn't matter. I had the same issue. I downloaded this plugin and was able to connect to OBS

**Comment by PlanetOfCoding-real** [comment]
Okay! Thank you <3
