### ISSUE TITLE
[FEATURE REQUEST] folders

### ISSUE THREAD

**Issue by DeltaAlpha0** [rivafarabi/deckboard#911]
It doesn't take a source from a folder, but it turns off the folder as a whole, it would be interesting to organize the stream and make it less chaotic.

![image](https://user-images.githubusercontent.com/41399279/192634334-434068f8-78ff-46a0-9db8-9173fe39b4c2.png)

**Comment by rivafarabi** [comment]
The OBS' group/folder support has been added in version [2.0.57](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.57)
