### ISSUE TITLE
Can´t Login in any Service [BUG]

### ISSUE THREAD

**Issue by NightmareShark** [rivafarabi/deckboard#912]
I can´t Login in Any Service (Twitch, Discord, Spotify)

![image](https://user-images.githubusercontent.com/109388773/192786386-9607d579-90da-4889-bc51-fbacd68f6f04.png)

**Comment by UzhasOrion** [comment]
I have the same issue but just with Twitch

**Comment by rivafarabi** [comment]
There seems an issue on Twitch side. Some of the users reported the same issue and there is an ongoing discussion online that some third party software, like Stream Deck, or browsers face this issue.

Reference:

- [Reddit Post](https://www.reddit.com/r/Twitch/comments/xm7how/something_went_wrong_when_trying_to_log_into/)
- [Elgato Stream Deck](https://help.elgato.com/hc/en-us/articles/9483466519181-Elgato-Stream-Deck-Issues-with-Twitch-Login-Authorization-September-2022-)

**Comment by rivafarabi** [comment]
The authentication flow for Twitch has been revised in the latest release version [2.0.5](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.5).
