### ISSUE TITLE
[BUG] Can't login with Twitch

### ISSUE THREAD

**Issue by UzhasOrion** [rivafarabi/deckboard#913]
**Describe the bug**
When i try to connect my Twitch account it shows the message:
"something went wrong, try  again "

**To Reproduce**
1. Go to 'settings'
2. Click on 'accounts'
3. select 'twitch'
4. See error mentioned before "something went wrong, try  again "

**Expected behavior**
i should be able to login with any problem, i just installed my deckboard yesterday.

**Server App (please complete the following information):**
 - OS: Windows -Windows Feature Experience Pack 120.2212.4180.0-

**Client App (please complete the following information):**
 - OS:  Android 11 RKQ1.200826.002
 - Phone: Redmi note 9s
 - MIUI Global 12.5.5  (RJWMXAT)

**Required files**
- I dont know how to add the requested files on this tool, sorry!

**Additional context**
i will try to use the same windows version with a previous deckboard version.

**Comment by yvanb26** [comment]
Hi, i have the same error

**Comment by rivafarabi** [comment]
As stated in #912, there seems an issue on Twitch side. Some of the users reported the same issue and there is an ongoing discussion online that some third party software, like Stream Deck, or browsers face this issue.

Reference:

[Reddit Post](https://www.reddit.com/r/Twitch/comments/xm7how/something_went_wrong_when_trying_to_log_into/)
[Elgato Stream Deck](https://help.elgato.com/hc/en-us/articles/9483466519181-Elgato-Stream-Deck-Issues-with-Twitch-Login-Authorization-September-2022-)

**Comment by Dlay2017** [comment]
For it seems to be an issue with 2FA.. the window for 2FA doesnt show up. On the normal twitch.tv page 2FA works..

**Comment by rivafarabi** [comment]
The authentication flow for Twitch has been revised in the latest release version [2.0.5](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.5).

**Comment by ChmielON** [comment]
> The authentication flow for Twitch has been revised in the latest release version [2.0.5](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.5).

Now is working well. But what happened to the connection with discord?
