### ISSUE TITLE
[BUG] just started - will execute macro only once

### ISSUE THREAD

**Issue by zeenewbian** [rivafarabi/deckboard#915]
i mostly use DB for Elite Dangerous gaming & even earlier today (2022-10-02) it was working fine as it has since i bought Pro. 
but this evening (i am UTC -4) it started executing a macro only once - cf it would toggle a HUD but then would not toggle again to go back to the previous HUD

i have reinstalled the Windows x64 server - no change

i also had a macro set up to move through my browser tabs that also no longer works at all - but the macro to go to my desktop works & even toggles back to the browser and cycles just fine

i have exhausted my troubleshooting ability & am ready to give up

i run DB on a Samsung SM-T820 Galaxy Tab S3 tablet running Android 9 and connect to my computer via WiFi

i installed it on my phone (a Pixel 3a running Android 12) but it has the same issue there - macro goes once then stops

it doesn't crash - it just no longer works as it has for so very long

**Comment by ZAMHome** [comment]
I confirm. Macros (button combinations) stopped working properly in version 2.0.5. I had to install version 2.0.4 and block outgoing connections for the application through the firewall so that the application would not be updated automatically.

**Comment by rivafarabi** [comment]
I apologize for the delay.

Just released an update for Windows release ([v2.0.51](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.51)) that fix in-game keypress macro control.

**Comment by jwterry** [comment]
I know this is closed, but I cannot get Deckboard to work with Elite  Dangerous.
