### ISSUE TITLE
Macros no longer work correctly in RedM after latest update

### ISSUE THREAD

**Issue by FuzzyFreaks** [rivafarabi/deckboard#917]
I use Deckboard for RedM rp /emote macros, as of the latest update they no longer register correctly ingame - it'll open the text entry window, but the actual keystrokes won't be entered into it, instead they are registered as ingame keystrokes leading to my character walking around like a weirdo.

I've tried various changes to the macros but nothing seems to work, and I can't roll it back to a working version due to the auto-update feature.

**Comment by RedVoltGaming** [comment]
i have the same issue with fiveM

**Comment by RedVoltGaming** [comment]
is there somewhere to get the older version for now ?

**Comment by ZAMHome** [comment]
I confirm. Macros (button combinations) stopped working properly in version 2.0.5. I had to install version 2.0.4 and block outgoing connections for the application through the firewall so that the application would not be updated automatically.

**Comment by rivafarabi** [comment]
Closing this due duplicate issue (#915)
