### ISSUE TITLE
[BUG] Spotify Playback controls not working

### ISSUE THREAD

**Issue by thebob2713** [rivafarabi/deckboard#919]
**Describe the bug**

**To Reproduce**
3. Fill a value to '...'

**Expected behavior**

**Screenshots**

**Server App (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 1.9.0]

**Client App (please complete the following information):**
 - OS: [e.g. Android 9]
 - Version [e.g. 1.9.60]

**Required files**
- database.db (located in `C:\Users%USER%\deckboard`)
- log.log (located in located in `C:\Users%USER%\AppData\Roaming\Deckboard`)

**Additional context**

**Comment by thebob2713** [comment]
It seems my playback isnt working, after signing into spotify (in deckboard)

I also have spot. prem. so shouldnt be an issue based on your homepage.

Thanks

**Comment by thebob2713** [comment]
Sorry - after changing it to multimedia rather than spotify it seems to work

**Comment by ahydronous** [comment]
I have this same problem, whenever I try to play it, Spotify (the desktop app) gives an 'error 404 - device not found'.

Multimedia controls work, but that is not the same as Spotify play control.

**Comment by cfanoulis** [comment]
Hey, you need to connect your spotify account in the settings for it to work
Also, next time, you might wanna fill out the bug template
