### ISSUE TITLE
Small Bugs Found in 1.2.64

### ISSUE THREAD

**Issue by AngelicDivine** [rivafarabi/deckboard#92]
It seems on the decktop ( ha tried to make a pun :D ) the image for the buttons are not showing up but on the app they are example of this bug with be shown at the bottom 

> please note i installed deckboard on my laptop to see if it was just a bad installation but it seems its on all not sure if anyone else is having this issue as well 

It has also come to my attention  when I tried to install it it would not update for some reason i went and fully uninstalled it and reinstalled it to get to update 1.2.64 and when i did it seems my buttons from the last updated stayed i am not sure if i needed to get rid of the something after fully uninstalling it to get a fresh install or not just thought i would put this here for you so you know what i did 

![deckboard_fkrqaaajag](https://user-images.githubusercontent.com/14226973/50736095-a8651f00-1186-11e9-8cd6-6613746ecb23.png)
 

> (update after posting this )

 

It seems when you also make a button to go to a specific board it shows it as ( object Object ) but it still works as a button so no complaints from me 

![deckboard_m9ncbh4esv](https://user-images.githubusercontent.com/14226973/50736261-422dcb80-1189-11e9-8743-166fd5380809.png)

( update )

Audio Device Control is not showing up when going to it 
It seems after trying to go from testing Audio Device ( with OBS imputs ) it seems to mess up and trying to add other things does not work ( i keep having to restart )

> I tested it with 1.2.64 and also with 1.2.641

![deckboard_pxfh37hok0](https://user-images.githubusercontent.com/14226973/50740304-9604d880-11ba-11e9-8276-fc6141be132e.png)

if you need me to i will test this on the laptop and add what i find on this post

**Comment by rivafarabi** [comment]
Thanks for reporting the bug in switch board input. 

As for the first bug, the one the button button not showing up, is it the new created button on latest version or previous one?

**Comment by rivafarabi** [comment]
version 1.2.641 fixed the switch board input.

**Comment by AngelicDivine** [comment]
its new

**Comment by AngelicDivine** [comment]
here is the board export 
[bad board.zip](https://github.com/rivafarabi/deckboard/files/2741730/bad.board.zip)

**Comment by AngelicDivine** [comment]
also here is what i found in the log 

[2019-01-10 06:53:26.358] [error] { status: 'error',
  description: 'An exception occurred from the underlying WebSocket.',
  code: 'SOCKET_EXCEPTION',
  error: 'An exception occurred from the underlying WebSocket.' }
[2019-01-10 06:53:26.361] [error] Error: closed before the connection is established
    at WebSocket.close (C:\Program Files\Deckboard\resources\app.asar\node_modules\ws\lib\WebSocket.js:271:21)
    at C:\Program Files\Deckboard\resources\app.asar\node_modules\obs-websocket-js\es5\Socket.js:65:30
    at Generator.throw (<anonymous>)
    at step (C:\Program Files\Deckboard\resources\app.asar\node_modules\obs-websocket-js\es5\Socket.js:5:191)
    at C:\Program Files\Deckboard\resources\app.asar\node_modules\obs-websocket-js\es5\Socket.js:5:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

[2019-01-10 06:53:26.361] [error] { status: 'error',
  description: 'An exception occurred from the underlying WebSocket.',
  code: 'SOCKET_EXCEPTION',
  error: 'An exception occurred from the underlying WebSocket.' }

**Comment by rivafarabi** [comment]
fixed in ver 1.2.643
