### ISSUE TITLE
[BUG] "downloading cool stuff"

### ISSUE THREAD

**Issue by AstroSzefPL** [rivafarabi/deckboard#920]
"downloading" prompt is always 0%

![image](https://user-images.githubusercontent.com/111984302/195145485-f1d022e0-bb99-468d-aa09-46cb1b3e80ac.png)

**Comment by rivafarabi** [comment]
There was a missing release for linux distribution in version 2.0.51. I've just updated a new version ([v2.0.52](https://github.com/rivafarabi/deckboard/releases/tag/v2.0.52)) including some fixes.

Just open the app as usual to get the auto update. If the issue still persist, just reinstall the latest version of the app mentioned above.

**Comment by lucasnijssen** [comment]
I have the same issue on my mac and reinstall doesn't work ether
