### ISSUE TITLE
[BUG] Deckboard trying to connect to many ports

### ISSUE THREAD

**Issue by PifLyon** [rivafarabi/deckboard#922]
Hi, since I updated to 2.0.52 (yesterday), Deckboard tries to connect successively to ports 50xxxx in loop (50917, 50918, 50919, 50896, 50900, 50904, etc...)

All was fine just before the update (and even working during the update).
I did not make any change to OBS nor websocket settings.  The config is 127.0.0.1 port 4444. Restarted computer, I tried with & without password, I tried to change port in Deckboard's config, nothing helps. It seems not to take care of these settings. 

Looks like this release includes some "debug/prototype" fonctions you forgot to remove ;)

I can't use Deckboard anymore as it attempts to connect in loop to what it wants, generating endless alerts.

OBS 27.2.4
DeckBoard 2.0.52
Windows 10 Home 64bits - 21H2

**Comment by rivafarabi** [comment]
Have you updated the obs websocket plugin to version 5?

**Comment by PifLyon** [comment]
Hi. I updated websocket to 5.0.1 (as 4.7) and now it works again.

I did not see any alert of this update being mandatory turning Deckboard 2.0.51 to 2.0.52 (But updates are made automatically without prompt, so I don't know if I could be alerted).

Thank you Rivafarabi and congratulations for Deckboard :)
