### ISSUE TITLE
[BUG] Type Text - Linux

### ISSUE THREAD

**Issue by Gadgetroch** [rivafarabi/deckboard#924]
Hi,

When i use type text function, nothing working.

I have tried, by press the button, or by launching with android, nothing works.

All other things works.

PS : how can i put a keyboard shortcut on one button ?

**Comment by rivafarabi** [comment]
what key combination you tried?

**Comment by hakaitech** [comment]
+1 i tried to use it to type in an ssh command

**Comment by rivafarabi** [comment]
closing this due to version 3 has different behavior for Type Text action
