### ISSUE TITLE
cant connect deckboard to obs 27.2.4 [BUG]

### ISSUE THREAD

**Issue by osa409** [rivafarabi/deckboard#925]
I cant connect my deckboard program to obs 27.2.4

I just redownload the 27.2.4 version of the obs studio and still deckboard program in windows still does not connect.
I even redowload and installed the websocket that comes in the tutorial

Windows 10 Pro
Obs 27.2.4
deckboard 2.0.55

my socket is the same, I dont use a password and my ip is correct, I have done everything as the tutorial says. It used to work so well and now im stuck like this

**Comment by rivafarabi** [comment]
You need OBS websocket plugin version 5 if you want to keep the current version OBS. Or install the latest OBS (version 28).

**Comment by osa409** [comment]
Yessss thats the correct answer! thank you so much! its works perfectly now!!!
