### ISSUE TITLE
[FEATURE REQUEST] Key On/Off State Toggle

### ISSUE THREAD

**Issue by Mormaleon** [rivafarabi/deckboard#932]
**Describe the solution you'd like**
I really would like to see an  toggle feature that is available as either an Keyboard/Advanced Keyboard Macro that is not incorporated into obs/stream-labs etc that you can press an button such as (V) it turns on and stays on until you turn it off again this is for team voice chat witch by default has no ability in game to have turned on all the time as it only uses push to talk

End result an key press function that can hold an on/off state.

I apologizes if this is already in there but have not been able to find it (NOT INCULCATED IN OBS) an general use on/off state macro

**Comment by Moshtaf** [comment]
Currently, the only reason that I use Touch Portal instead of Deck board is this. I want to add the Discord mute/unmute hotkey as a  Keyboard Macro and see its status. The Discord extension is not that easy to config, and even the extension does not support the toggle feature.
