### ISSUE TITLE
[function keys on mac do not read in keyboard macros & advanced keyboard macros. command, control, option, shift

### ISSUE THREAD

**Issue by SomayaArt** [rivafarabi/deckboard#933]
[function keys on mac do not read in keyboard macros & advanced keyboard macros. command, control, option, shift

when using photoshop combination shortcuts like   Command+T, I get the result (T only )
I use the macro keyboard macro and advanced keyboard macro, also tried combined actions. I rerally love this app and appreciate your awesome work !

not sure what to do with this issue so far. I'm on mac os and using my  iphone

**Comment by narwold** [comment]
I'm having this same issue.
