### ISSUE TITLE
[BUG] Macro when pressed, remains pressed shift/ctrl/alt

### ISSUE THREAD

**Issue by rZiMiZ** [rivafarabi/deckboard#935]
When i use the macro buttons, something like "CTRL+B", when i press this, the CTRL remains pressed... or if i press macro "SHIFT+ALT+T", SHIFT and ALT remains pressed....

![image](https://user-images.githubusercontent.com/86168684/204050353-277dabb2-3db6-440e-a165-b96b07b119cc.png)

Windows
2.0.56

Android

**Comment by ThisIsTheOldGuard** [comment]
I can advise you to use "Advance Keyboard Macro" to record a macro
