### ISSUE TITLE
[BUG] Unable to connect to Twitch - Application Error

### ISSUE THREAD

**Issue by Delirya** [rivafarabi/deckboard#936]
**Describe the bug**
When I click on the Login button, for Twitch, it attempts to load https://deckboard-service.herokuapp.com/twitch/auth but instead of the usual permissions page, it presents an application error "an error occured in the application and your page could not be served"

**To Reproduce**
1. Go to 'Settngs -> Accounts'
2. Click on 'Twitch Login'
3. website https://deckboard-service.herokuapp.com/twitch/auth opens

**Expected behavior**
Twitch permissions page to load, to connect deckboard to stream account.

**Screenshots**
![Screen Shot 11-30-22 at 12 14 PM](https://user-images.githubusercontent.com/42555594/204864973-babbc4ce-887d-4ace-bca4-166d0993c30c.PNG)

**Server App (please complete the following information):**
 - Windows
 - Version 2.0.56

**Client App (please complete the following information):**
 - Android 12
 - Version 2.0.5 Build 20032

**Required files**
- database.db (unable to upload, not supported file format)
[log.log](https://github.com/rivafarabi/deckboard/files/10125653/log.log)

**Additional context**

**Comment by Delirya** [comment]
Actually, I just noticed that the twitch icon isn't there in the application itself. I only have OBS and streamlabs options

![Screen Shot 11-30-22 at 03 05 PM](https://user-images.githubusercontent.com/42555594/204897457-e7d5f804-4560-4440-a1b3-eedb123e0f33.PNG)

**Comment by rivafarabi** [comment]
Thanks for bringing this to my attention. The issue has been resolved. It
should be back to normal now.
