### ISSUE TITLE
[BUG] Streamer.bot Configs not showing in Deckboard

### ISSUE THREAD

**Issue by miguelfabio** [rivafarabi/deckboard#938]
*Already posted this thread on the streamerbot-deckboard git, but I'm reposting here hoping someone can help.*

I installed the Streamer.bot extension directly from the app, in the Extension tab, and followed the instruction to restart the app. However, it doesn't show the streamer.bot configurations to set the server connection, so I can't connect Deckboard to Streamer.bot. I have already tried to run Deckboard as Admin and reinstall the SB extension, but it doesn't work as well. Any hint of what I can do to make it work? I can see the option to Execute a SB Action, but nothing shows in the action field. I'll attach the pictures below. I'm using Deckboard version 2.0.57, SB version 0.1.14 and Windows 10 Home version 21H2 and build 19044.2251.

SB extension installed
![image](https://user-images.githubusercontent.com/119859063/205637724-9fa38901-75a4-4a1f-a1f8-25e9b8539014.png)

SB extension configs not showing
![image](https://user-images.githubusercontent.com/119859063/205637764-d9e9a9ac-918f-4c52-bac6-82bf0a24aaea.png)

I'm able to create a button with the SB Actions and select the "Execute Action", but none action shows in the list
![image](https://user-images.githubusercontent.com/119859063/205637955-9249cc7c-4e5a-4c4c-a2be-10d750b69e82.png)

Here are some test actions I created in SB
![image](https://user-images.githubusercontent.com/119859063/205637996-37d96696-9c32-4c96-86cf-bf2fff55e103.png)

Any help is appreciated!

**Comment by rivafarabi** [comment]
It is indeed a bug where the app cannot generate extensions' default settings.

As temporary fix, you can add these lines below in `settings.json` located in `C:\Users\USER\deckboard`

```
{
	"streamerbot-deckboard": {
		"address": {
			"descriptions": "Example: 127.0.0.1",
			"name": "Address",
			"type": "text",
			"value": "127.0.0.1"
		},
		"port": {
			"descriptions": "Example: 7474",
			"name": "Port",
			"type": "text",
			"value": "7474"
		}
	}
}
```

**Comment by miguelfabio** [comment]
@rivafarabi Worked like a charm, thank you very much!
