### ISSUE TITLE
[BUG] Missed configs

### ISSUE THREAD

**Issue by ociobits** [rivafarabi/deckboard#939]
**Describe the bug**
All the configurations have been dissapeared, I can't create/modify anyone.

**Expected behavior**
I was expecting to configure the Discord extension.

**Screenshots**
![image](https://user-images.githubusercontent.com/36764034/205889885-7750e6c2-c3b8-49a4-938c-e7e02b595766.png)
![image](https://user-images.githubusercontent.com/36764034/205889916-5af83f89-b597-4bc4-b1fd-decc634fa8d1.png)

**Server App (please complete the following information):**
 - Windows 10 22H2 19045.2311

**Client App (please complete the following information):**
 - OS: iPadOS 16.1.1

**Required files**
- database.db: https://mega.nz/file/K9gXgLwL#_WvqvQMDUkr7kUy0ecZZm1EJqNuqtWVjUbA5ZG3pW1A
- log.log: https://mega.nz/file/K4xFnCgC#BtEw6FNIFz9xmRIQqrronFROnstl94LCEsjzhA67PTQ

**Comment by rivafarabi** [comment]
It is indeed a bug where the app cannot generate extensions' default settings.

As temporary fix, you can add these lines below in `settings.json` located in `C:\Users\USER\deckboard`

```
{
	"discord-deckboard": {
		"discordAccessToken": {
			"descriptions": "Access Token in OAuth2 App",
			"name": "Access Token (not distribute)",
			"type": "text",
			"value": null
		},
		"discordClientId": {
			"descriptions": "Client ID in OAuth2 App",
			"name": "Client ID",
			"type": "text",
			"value": null
		},
		"discordClientSecret": {
			"descriptions": "Client Secret in OAuth2 App",
			"name": "Client Secret (not distribute)",
			"type": "text",
			"value": null
		}
	}
}
```

**Comment by ociobits** [comment]
Thank you so much, it worked! My settings.json was completely empty.
