### ISSUE TITLE
Add Support to Scene FIlters

### ISSUE THREAD

**Issue by Sharemess** [rivafarabi/deckboard#940]
I'm often using deckboard for streaming, but some of my effects uses scenes filters other than source filters

sould be great to have the option to toggle scenes filters so i could make complex effects on stream and i bet other people would be happy too

a good example is that my issue today that i use a brb (be right back) screen and i use the VHS Filter with some logos for VHS effect like a paused movie, and i can't toggle them because theres no support 
![image](https://user-images.githubusercontent.com/119972166/206009945-3ba2a473-d9c3-4e98-a90b-f67152eafff2.png)

**Comment by Yurlyn** [comment]
I was wondering how triggered some of my scene filters xD But I did that by using the scene inside another scene (in my case it's to change my layout's colors. The scene is in every main scene for easy access if I want to change the color without having to use studio mode). But this way I'm able to trigger the scene's filters. Native support would be better but still, this is a nice workaround I didn't expect until I saw it pop up in the list of filters I could change lol.
