### ISSUE TITLE
[BUG] Spotify starting the music on the wrong Device

### ISSUE THREAD

**Issue by SvNawesome** [rivafarabi/deckboard#945]
**Describe the bug**
Spotify: Stopping and starting Spotify from a Deckboard Button, starts the music with the wrong device. (Switches from currently active to something else, in my case "FireTv Stick")

**To Reproduce**
1. Create a toggable Play/Pause Spotify button,
2. Have multiple Devices in Spotify which you can switch to.
3. Stop the music (stops the music for the currently active device)
4. Start The music (starts the music on the wrong device)

**Expected behavior**
Stopping and starting the music on the same Device

**Server App (please complete the following information):**
 - OS: Windows 10 
 - Version 22H2

**Client App (please complete the following information):**
 - OS: Android 11
 - Version Oxygen OS 11.0.8.1

**Required files**
[Bug.zip](https://github.com/rivafarabi/deckboard/files/10259820/Bug.zip)

**Comment by SvNawesome** [comment]
Additional Info it swaps the active device the moment i stop the music through the button.

**Comment by mafraqs** [comment]
Same for me, it always switches to a specific other device - in my case "Denon AVR-X1300W". Also when using "next" or "prev" title.
