### ISSUE TITLE
Spotify Shortcuts not Working

### ISSUE THREAD

**Issue by TheManiacHS** [rivafarabi/deckboard#95]
Hello Again,
The Netowrk Fix works fine :D 
but after all the Spotify Integration will not work...everysthing is connected and still no raction from my Spotify app @windows

greetz

**Comment by rivafarabi** [comment]
Thanks for the info. I will look into it soon.

**Comment by rivafarabi** [comment]
it seems the spotify API won't work if no device active at the time. To make it start just play any track on your spotify windows app until spotify icon popup on deckboard app

![spotify](https://user-images.githubusercontent.com/4427494/50972906-4ad02a00-151a-11e9-8066-ec1ecbaa4dbd.PNG)

**Comment by TheManiacHS** [comment]
Icon is showing but still no reaction from the board :/

**Comment by rivafarabi** [comment]
what macro action did you failed to run?

**Comment by TheManiacHS** [comment]
every Spotify button doesnt run....no play prev next or play (song)

**Comment by TheManiacHS** [comment]
@DakodaPlays how did you got it working ?

**Comment by DakodaPlays** [comment]
@TheManiacHS working? this doesn't work for me as of the newest update as said above

**Comment by TheManiacHS** [comment]
i meant before update :D

**Comment by DakodaPlays** [comment]
on version 1.2.6 it just worked nothing i did differently but broke when i got 1.2.7

**Comment by DakodaPlays** [comment]
@rivafarabi any luck on a fix for this soon?

**Comment by rivafarabi** [comment]
> @rivafarabi any luck on a fix for this soon?


spotify fix will be coming tomorrow. Sorry for slow update.

**Comment by TheManiacHS** [comment]
@rivafarabi aftewr Update still no Reaction...do i have to start it in any Special way ??

**Comment by digitalfiz** [comment]
Can confirm still not working.

**Comment by TheManiacHS** [comment]
Half a year ago i heard smthng about an changed API

**Comment by digitalfiz** [comment]
So I was wrong actually. The update popup makes you think the app updated but you still have to download the update and install it for it to be updated. Can confirm its working for me now.

**Comment by TheManiacHS** [comment]
@digitalfiz can we contact directly .... im freaking out here...its not working

**Comment by DakodaPlays** [comment]
working like perfectly now <3

**Comment by rivafarabi** [comment]
> @digitalfiz can we contact directly .... im freaking out here...its not working

Make sure you logged in to Spotify and you need to play any track on spotify player to trigger Spotify API to get working on Deckboard. 

There should be green spotify icon beside OBS and Streamlabs icon on the app that indicates that the API is working.

**Comment by TheManiacHS** [comment]
@rivafarabi VERY stupid question ... is Spotify Premium Recommended ? 
Yeah the API and everything is Showing up as you said but it doesnt Work.

**Comment by rivafarabi** [comment]
> @rivafarabi VERY stupid question ... is Spotify Premium Recommended ?
> Yeah the API and everything is Showing up as you said but it doesnt Work.

The Spotify API documentation page stated only Premium user can utilize their playback control API

**Comment by ShadowCreator250** [comment]
> 
> 
> > @rivafarabi VERY stupid question ... is Spotify Premium Recommended ?
> > Yeah the API and everything is Showing up as you said but it doesnt Work.
> 
> The Spotify API documentation page stated only Premium user can utilize their playback control API

Can you please make it visible in the Desktop App, that for the Spotify playback macros Spotify Premium is needed? Would be really great!

**Comment by ExaRox24** [comment]
hello there same problem

**Comment by ardae17** [comment]
i have pruım it doenst work

**Comment by davisddpro** [comment]
°It isnt working again no button works but the spotify API logo is on and says playing but i cant do anything and the the spotify login is stuck when i press login it just opens a new white window and closes in like 2 seconds and it keeps repeating so i cant login. Pls fix this soon as this is litteraly the best option for me rn!

**Comment by Fr4nckyDumpi** [comment]
For my part, I use version 1.9.99 and Spotify Prenium, I have access to commands such as : 
- Like Song
- Play a selected playlist

But I can't use other buttons like : 
- Play / Stop
- Next / Previous music
- Increase sound / Decrease sound

One idea ?

**Comment by DaanMeijers** [comment]
Hello! Started using deckboard today. Almost everything works, except the "add track to playlist" button. Play and like toggle with spotify integration work just fine. But when i want to select a playlist it says "no data available"

**Comment by DaanMeijers** [comment]
ah shit, this one is closed
