### ISSUE TITLE
Keyboard Macro with multiple keys

### ISSUE THREAD

**Issue by schousda** [rivafarabi/deckboard#950]
Hello,

i try to send the shortcut CONTROL+SHIFT+S to NAPS2.
But i only can set up CONTROL+S or SHIFT+S. The combination of 3 keys seems not to work.

Is this a bug or am i doing something wrong?

Maybe i have to use the Advanced Keyboard Macro, but i didn't get how this works, since i don't see there an option to trigger the correct app.

My System:
Windows 11
Deckboard 2.0.57 Pro

**Comment by rivafarabi** [comment]
Have you tried to toggle the input method from **Combination input** to **Sequence input**? You can toggle it by clicking the keyboard icon on the right side of **Keypress** field.

![image](https://user-images.githubusercontent.com/4427494/209966072-71d9521b-1351-46c8-8808-2d1c33ea7c09.png)

Once you toggle **Sequence input**, you can enter the keys one at a time to make the combination you desire.

![image](https://user-images.githubusercontent.com/4427494/209966315-67c557ec-8bdc-45ee-9fc6-98504381156d.png)

**Comment by schousda** [comment]
Thank you.
This is the solution.
