### ISSUE TITLE
Is it possible to open this up in a web browser?

### ISSUE THREAD

**Issue by tomdevlive** [rivafarabi/deckboard#956]
Can I open the decks in a web browser? Or do I have to get the phone app to do that?

**Comment by schousda** [comment]
You can use the "Start" Button on top of the Deckboard software. Then you can use the buttons from your computer.

**Comment by tomdevlive** [comment]
So are you saying No it is not possible? I would like to access Deckboard via a Web Browser, on my computer and not my phone,. Similar to hgow you can with Bitfocus Companion.
