### ISSUE TITLE
Elite Dangerous

### ISSUE THREAD

**Issue by jwterry** [rivafarabi/deckboard#957]
I am trying to set up Deckboard to use with Elite Dangerous, but without success. Whatever I do ED doesn't respond to Deckboard. The keyboard bindings are set in ED but when I try to activate via Deckboard the game fails to respond. 
Any help appreciated.

Terry

**Comment by jwterry** [comment]
Sorted, just had to run DB as Admin.

**Comment by jrequiroso** [comment]
Might I suggest closing this issue since it has been sorted for you @jwterry?
