### ISSUE TITLE
[BUG] Install on popOS failed: libnode64 and libicu66 is not installed

### ISSUE THREAD

**Issue by DrahoFr** [rivafarabi/deckboard#958]
Hi there,

I can't install this application on my PopOS 22.04 (up to date).

I tried from the .deb paSelecting previously unselected package deckboard.
(Reading database ... 455207 files and directories currently installed.)
Preparing to unpack deckboard_2.1.0_amd64.deb ...
Unpacking deckboard (2.1.0) ...
dpkg: dependency problems prevent configuration of deckboard:
 deckboard depends on libnode64; however:
  Package libnode64 is not installed.
 deckboard depends on libicu66; however:
  Package libicu66 is not installed.

dpkg: error processing package deckboard (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 deckboard
ckage:

The strange thing, is that I did install already on this computer, but since an update, it doesn't work anymore.

**Comment by Thelvaen** [comment]
Libs have been updated on PoPOS!, and the deb requires specific, older versions of those 2 libs.

**Comment by DrahoFr** [comment]
I managed to install old libs but it broke all the atp so I back.
Too bad, I love this app :/

**Comment by Thelvaen** [comment]
You might want to close this bug and mention your issue in #617 it's basically the same issue, and having only one bug active with multiple inputs in it is more enticing for a dev to fix than having 50 bugs open with only 1 user each time.

**Comment by DrahoFr** [comment]
Ok I agree
