### ISSUE TITLE
Ubuntu22.04 has libnode72, whereas deckboard requires libnode64 - Compatibility issue

### ISSUE THREAD

**Issue by UsmanMaqbool** [rivafarabi/deckboard#960]
Thanks a lot Rivafarabi for the amazing work. I tried to install deckboard on my Ubuntu 22. Unfortunately, for both Snap and Deb are not working due to this possible conflict.
```
dpkg: dependency problems prevent configuration of deckboard:
 deckboard depends on libnode64; however:
  Package libnode64 is not installed.
```

Thanks in advance, and keep doing this amazing work.

**Comment by Helge102** [comment]
It's the same with Debian sid.
Deckboard depends on libnode64, but for libnode108 are available and installed.
Another dependency is libicu66, but I have libicu72 and libicu63 installed.
The dependencies would have to be adjusted.

The AppImage works.
https://github.com/rivafarabi/deckboard/releases/tag/v2.1.1

But i would also like a working .deb
