### ISSUE TITLE
[BUG]error A Javascript error occurred in The Main Procces

### ISSUE THREAD

**Issue by SakatoProject** [rivafarabi/deckboard#962]
every time I start using the application, it always starts with an error like the one in the picture.

![Screenshot 2023-02-17 232844](https://user-images.githubusercontent.com/125687554/219722678-b25cb3e8-c317-416e-a769-82dfc6cccb61.png)

this Deckboard version 2.1.1

how to fix it?

**Comment by Gsimken** [comment]
Same issue here, downgrade to 2.1.0 to "fix it", its very annoying that exception, every time i openned a button appears
