### ISSUE TITLE
[BUG] Keyboard Macro

### ISSUE THREAD

**Issue by HowlingMayhem** [rivafarabi/deckboard#966]
**Describe the bug**
The action Keyboard Macro does not work.

**To Reproduce**
1. Click an empty square on the server app to make a new button.
2. Set Action to Keyboard Macro.
3. Make the keypress any combination that works in your desired program - Firefox, SLOBS, etc.
4. Use dropdown for Run on... and choose your desired program.
5. Click Add.
6. Either tap on the button on the client app, or click Start on the server app and then click the button.
7. The keyboard macro will not perform, on either the client app or the server app.

**Expected behavior**
I expected the keyboard macro to work in my desired programs. For example, I started by setting custom macros in Streamlabs OBS to turn on or off Studio Mode, then a macro to transition. When neither button worked, I tried making a button to open a new tab in Firefox, again to no avail.

**Server App (please complete the following information):**
 - OS: Win 10 19044.2604
 - Version 2.1.1

**Client App (please complete the following information):**
 - OS: Android 8.1.0
 - Version 2.1.0 Build 10035
 
**Required files**
[Required files.zip](https://github.com/rivafarabi/deckboard/files/10887362/Required.files.zip)

**Comment by dblock110** [comment]
im also having this problem! i just want to run deckboard on PC. just trying to send the WIN key doesnt do anything.
all keyboard macros not functioning!
please help

**Comment by Eloren1** [comment]
Same lol. Media controls work, but Macros don't.

**Comment by Eloren1** [comment]
Same. Media controls work, but Macros don't.

**Comment by rivafarabi** [comment]
May I know which combination of macro and the app you are using?
