### ISSUE TITLE
Example Extension does not work

### ISSUE THREAD

**Issue by DakodaPlays** [rivafarabi/deckboard#97]
the example extension you have gives back this error 

![img here](https://i.imgur.com/TCLnTFZ.png)

**Comment by AngelicDivine** [comment]
How do i set up and try to use the example extension?

**Comment by rivafarabi** [comment]
Thanks for testing the sample. Because there's some changes in the app itself, some extension's structure also change. I will make sure to make better documention.

**Comment by DakodaPlays** [comment]
will be nice as i want to make a few extensions but with this i cant :(

**Comment by DakodaPlays** [comment]
Any update on this yet? [link](https://github.com/rivafarabi/deckboard-extension-kit/issues/1) im really wanting this to work so i can start creating some extensions

**Comment by burdoto** [comment]
I would also love to get a description about what is happening as I would love to create an extension.

**Comment by rivafarabi** [comment]
sorry for not giving any update for days. Just had quite busy week. I'll jump to my dark dungeon this weekend to solve this.

**Comment by DakodaPlays** [comment]
Hope to see an update on this soon I'm really excited to get this working

**Comment by DakodaPlays** [comment]
@rivafarabi any update to this yet mate? its been a week sense you said you were going to be :)

**Comment by rivafarabi** [comment]
Still writing the documentation. I'll release the update this weekend.

**Comment by rivafarabi** [comment]
I added some fix in version 1.2.7 and also create sample extension here [https://github.com/rivafarabi/deckboard-power-control](url)

Documentation on wiki will be updated soon.

**Comment by NZX-DeSiGN** [comment]
Works like a charm ! I just wonder how we could access to the debug data (extensionLog method output). It's possible right now ? 

Thank you !

**Comment by DakodaPlays** [comment]
log it into a file :)
