### ISSUE TITLE
[BUG] Twitch Clear Chat Not Working

### ISSUE THREAD

**Issue by osmancitci** [rivafarabi/deckboard#976]
Clear Chat Not Working in Twitch control

**Comment by osmancitci** [comment]
some of the twitch features are not working

**Comment by osmancitci** [comment]
@rivafarabi do you care about it?

**Comment by rivafarabi** [comment]
Sorry, I kinda paused all activities including Deckboard maintainance
during Ramadhan and Eid. Will check this issue next week.

Eid Mubarak 🙏

**Comment by rivafarabi** [comment]
Fixed in [v2.1.3](https://github.com/rivafarabi/deckboard/releases/tag/v2.1.3). You need to sign out and sign in to your Twitch account to get access to this feature, otherwise it won't work.
