### ISSUE TITLE
[BUG] Unable to select executable to run with action Run Program

### ISSUE THREAD

**Issue by tannertechnology** [rivafarabi/deckboard#983]
**Describe the bug**
Run Program does not allow you to run a program on linux. It gives you a populated list of programs it pulls from an undocumented source instead of allowing you to specify an executable. For instance, if I want to run "echo hi" I cannot do this with deckboard as it is not in the list of apps it allows you to pick from. If the feature is Run Program let us specify a path to an executable (program). 

**To Reproduce**
1. Go to 'New Button'
2. Select the Action "Run Program"
3. Not have the option to fill a value, only the option to select from a list you can't add to.

**Expected behavior**
You tell it what program to run (ideally with arguments but that may be asking too much)

**Screenshots**

**Server App (please complete the following information):**
Linux ws-tanner-nix 6.2.12-200.fsync.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 27 09:38:53 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Client App (please complete the following information):**
Pixel 2 XL on Android 11 and 6a on 13

**Comment by tannertechnology** [comment]
A workaround for this bug is to make entries using the DeckBoard GUI and manually replace the details in your database.db. 

It would be fantastic to have a raw text field for this instead of the extremely limited and higher effort solution that is currently in place. Or documentation on the current solution.

**Comment by rivafarabi** [comment]
Haven't tried it personally on Linux, but have you tried the [deckboard-command](https://github.com/borisnliscool/deckboard-commands) extension. It should be available under Downloads in Extension settings

**Comment by tannertechnology** [comment]
That extension does it, thanks!
