### ISSUE TITLE
White screen after connection

### ISSUE THREAD

**Issue by xTwixbar** [rivafarabi/deckboard#987]
I've recently spent some time creating a layout that fits my needs.  Testing it here and there to make sure everything was working, but after disconnecting once, I wasn't able to view it anymore.  Trying to connect now results in my mobile device showing a blank white screen.  I can change settings but that is it.  I've tried both IPs and neither of them work.  I've uninstalled the app on both devices and reinstalled without avail.  I'm running version 2.1.3 on my Windows Computer and version 2.1.0 on my iOS device.  Some assistance would be greatly appreciated as this is the perfect app I've been looking to use.  If you can help but need more information, reach out to me and I'll send what you need.

Thanks,
Twix

**Comment by xTwixbar** [comment]
After deleting a page, everything returned to normal.  Is there a limit to how many pages you can have?

**Comment by rivafarabi** [comment]
Probably there was a bug that affected one of the buttons on the deleted
board.
If you face this issue again, you can send database.db file (located in
C:\Users\%USER%\deckboard)
