### ISSUE TITLE
can't connect to Spotify[BUG]

### ISSUE THREAD

**Issue by craken83** [rivafarabi/deckboard#989]
When I have try to connect my Spotify accont,  that dosen't work and when I look the log of the app, I see he can't reash the folders.
After that I looking the folders and I have seen the missing folders he try to reash.

Is that normal we have this missing folders:
spotify-web-api-node
superagent
dist

I'm on windows 22H2
deckboard in 2.1.3

**Comment by Fuziongg** [comment]
Did you manage to connect it?

**Comment by rivafarabi** [comment]
New authentication method has just been updated in [v2.1.4](https://github.com/rivafarabi/deckboard/releases/tag/v2.1.4)
