### ISSUE TITLE
[Request] "Play Audio" stop 

### ISSUE THREAD

**Issue by Baudrim** [rivafarabi/deckboard#99]
Hi guys!
Would it be possible to stop a sound at any time by pressing it again? 
I really mean via the button the Deckboard sound player that of the "Play Audio" from a choosen mp3

Thank you very much, this app is really great ! :)

**Comment by rivafarabi** [comment]
Thanks for the info. Going to release the patch next week.

**Comment by Baudrim** [comment]
Thank you ! :)

**Comment by rivafarabi** [comment]
Solved in version 1.2.7

**Comment by lucas-mercier** [comment]
not working anymore ):
