### ISSUE TITLE
Cant Connect Deckboard with Spotify !! 

### ISSUE THREAD

**Issue by Todiezao** [rivafarabi/deckboard#994]
I can't connect Deckboard with spotify, I click Settings > Accounts > Spotify Log in and the popup is blank.

can anyone solve it?
Thanks in advance

Heres a PrintScreen.

![imagem_2023-06-23_095950369](https://github.com/rivafarabi/deckboard/assets/83521445/25f9c8ea-1b88-4063-944d-41c5f2ce2508)

![imagem_2023-06-23_100002351](https://github.com/rivafarabi/deckboard/assets/83521445/dc9270ef-943d-4a69-9d2e-1381a1357af8)

**Comment by TheRealDylanH** [comment]
having the same issue. v 2.1.3

**Comment by rivafarabi** [comment]
New authentication method has just been updated in [v2.1.4](https://github.com/rivafarabi/deckboard/releases/tag/v2.1.4)
